import { Scenario } from "@/types";

export const SCENARIOS_BATCH_3: Scenario[] = [
  // =============================================
  // RULE 12: BUNKERS (bg9–bg23) — 15 scenarios
  // =============================================

  {
    id: "bg9",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is in a bunker. Before playing, you rest your club on the sand behind the ball while addressing it. Is there a penalty?",
    choices: [
      "Yes, two-stroke penalty — you must not ground your club in a bunker before a stroke",
      "No penalty as long as you don't press the club down",
      "No penalty — grounding your club is only restricted in penalty areas",
      "One-stroke penalty for grounding the club",
    ],
    correct: 0,
    rule: "Rule 12.2b(1)",
    explanation:
      "Under Rule 12.2b, before making a stroke at a ball in a bunker, you must not touch the sand with your club in the area right in front of or behind the ball, during a practice swing, or on the backswing for a stroke. Setting your club down behind the ball (grounding it) violates this rule and results in the general penalty.",
    tags: ["bunker", "sand", "touching-sand"],
  },
  {
    id: "bg10",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is in a bunker. May you lean on your club while waiting for your turn to play, resting it on the sand?",
    choices: [
      "Yes — you may touch the sand to support yourself, as long as it's not to test the condition of the sand or improve conditions for your stroke",
      "No — you cannot touch the sand with your club for any reason before your stroke",
      "Yes, but only outside the area immediately around the ball",
      "No — leaning on a club always results in a penalty in a bunker",
    ],
    correct: 0,
    rule: "Rule 12.2b(1), Exception",
    explanation:
      "Rule 12.2b lists specific exceptions for when you may touch sand in a bunker without penalty. You may lean on a club for rest or balance, as long as the purpose is not to test the condition of the sand or improve conditions affecting the stroke.",
    tags: ["bunker", "sand", "touching-sand"],
  },
  {
    id: "bg11",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is in a bunker. You remove a small stone that could hurt you if struck by your club. Is there a penalty?",
    choices: [
      "No penalty — loose impediments may be removed anywhere on the course, including bunkers",
      "Two-stroke penalty for moving a loose impediment in a bunker",
      "No penalty, but only because stones are dangerous",
      "One-stroke penalty for touching anything in the bunker",
    ],
    correct: 0,
    rule: "Rule 15.1a",
    explanation:
      "Since the 2019 Rules, you may remove loose impediments (including stones) in a bunker without penalty. This applies everywhere on the course. If the ball moves while removing the loose impediment, the ball must be replaced (one-stroke penalty if you caused it to move).",
    tags: ["bunker", "sand", "loose-impediment"],
  },
  {
    id: "bg12",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is in a bunker. You play your shot and the ball stays in the bunker. Before playing your next stroke, you smooth footprints in the area where your ball was. Is this allowed?",
    choices: [
      "Yes — after playing a stroke from a bunker, you may smooth sand without restriction",
      "No — you cannot smooth sand while your ball is still in the bunker",
      "Only if the smoothing doesn't improve conditions for your next stroke",
      "Yes, but only if you use a rake, not your feet",
    ],
    correct: 2,
    rule: "Rule 12.2b(2)",
    explanation:
      "After making a stroke from a bunker while the ball is still in the bunker, you may smooth sand or soil in the bunker at any time — but only for the care of the course. If the smoothing also improves conditions affecting your next stroke, there is no penalty only if it was done for the sole purpose of caring for the course. However, you must not deliberately improve conditions for your stroke.",
    tags: ["bunker", "sand", "rake"],
  },
  {
    id: "bg13",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is in a bunker. You play a great shot, and the ball lands on the green. May you now rake the bunker?",
    choices: [
      "Yes — once your ball is out of the bunker, you may smooth the sand without restriction",
      "You should wait until the hole is finished",
      "Only if you use the designated rake",
      "No — smoothing sand during a round is not allowed",
    ],
    correct: 0,
    rule: "Rule 12.2b(3)",
    explanation:
      "Once your ball is no longer in the bunker, the restrictions on touching sand in that bunker no longer apply to you. You may (and should, for course care) rake and smooth the bunker at any time.",
    tags: ["bunker", "sand", "rake"],
  },
  {
    id: "bg14",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is in a bunker and you declare it unplayable. You choose lateral relief. Where must you drop?",
    choices: [
      "Within two club-lengths of where the ball lies, not nearer the hole, and the ball must remain in the bunker — one-stroke penalty",
      "Within two club-lengths of where the ball lies, not nearer the hole — the ball may land outside the bunker",
      "Within one club-length of where the ball lies, not nearer the hole, in the bunker — one-stroke penalty",
      "Anywhere within the bunker — one-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 19.3a",
    explanation:
      "When taking lateral relief for an unplayable ball in a bunker, you must drop within two club-lengths of the spot where the ball lay, not nearer the hole, and the ball must come to rest in the bunker. This costs one penalty stroke. If you want to drop outside the bunker, you must use the back-on-the-line option with an additional penalty stroke (two total).",
    tags: ["bunker", "dropping", "relief"],
  },
  {
    id: "bg15",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "Your ball is in a bunker with temporary water (casual water). You want free relief. Where must you drop?",
    choices: [
      "Find the nearest point of complete relief in the bunker, drop within one club-length, not nearer the hole — the ball must stay in the bunker",
      "You may drop outside the bunker at the nearest point of complete relief",
      "No free relief is available in a bunker — you must play it as it lies or take unplayable ball relief",
      "Drop within two club-lengths of the temporary water, anywhere on the course",
    ],
    correct: 0,
    rule: "Rule 16.1c(1)",
    explanation:
      "When your ball is in a bunker with an abnormal course condition (like temporary water), free relief is available — but the ball must be dropped and come to rest in the bunker. If complete relief is not available in the bunker, you may take maximum available relief in the bunker. Alternatively, for one penalty stroke, you may drop outside the bunker on the back-on-the-line.",
    tags: ["bunker", "temporary-water", "casual-water", "free-relief", "dropping"],
  },
  {
    id: "bg16",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is in a bunker with temporary water. You cannot find a spot in the bunker that gives complete relief. What are your options?",
    choices: [
      "Take maximum available relief in the bunker (free), or drop outside the bunker on the back-on-the-line for one penalty stroke",
      "You must play it as it lies if no complete relief exists in the bunker",
      "Take free relief outside the bunker at the nearest point of complete relief",
      "Drop anywhere in the bunker that is drier — free relief",
    ],
    correct: 0,
    rule: "Rule 16.1c(1) and (2)",
    explanation:
      "If complete relief from temporary water is not available in the bunker, you may take maximum available relief in the bunker (the spot with least interference, not nearer the hole) — this is free. Alternatively, you may take back-on-the-line relief outside the bunker for one penalty stroke, dropping on a line from the hole through where the ball lay.",
    tags: ["bunker", "temporary-water", "casual-water", "free-relief", "relief"],
  },
  {
    id: "bg17",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is in a bunker. On your backswing, your club touches the sand. What happens?",
    choices: [
      "General penalty (two strokes in stroke play, loss of hole in match play)",
      "No penalty — the restriction only applies before the backswing",
      "One-stroke penalty",
      "No penalty as long as you complete the stroke",
    ],
    correct: 0,
    rule: "Rule 12.2b(1)",
    explanation:
      "Rule 12.2b prohibits touching the sand with a club on the backswing for a stroke. Touching sand on the backswing results in the general penalty: two strokes in stroke play or loss of hole in match play.",
    tags: ["bunker", "sand", "touching-sand", "backstroke"],
  },
  {
    id: "bg18",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is on the lip of a bunker with part of the ball overhanging the sand. The ball is not touching sand. Is this ball in the bunker?",
    choices: [
      "No — a ball is in a bunker only when any part of it touches the sand or is inside the edge of the bunker on the ground",
      "Yes — if any part of the ball is over the bunker, it's in the bunker",
      "It depends on whether more than half the ball is over the bunker",
      "No — the ball must be completely in the bunker to be in the bunker",
    ],
    correct: 0,
    rule: "Definition of Bunker, Rule 12",
    explanation:
      "A ball is in a bunker when any part of it lies on or touches the sand surface within the edge of the bunker. If the ball is sitting on the lip (on grass) and not touching sand, it is not in the bunker even if it overhangs the sand. You may ground your club normally.",
    tags: ["bunker", "sand"],
  },
  {
    id: "bg19",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "After entering a bunker to play your shot, you trip and put your hand on the sand to steady yourself. Your ball hasn't been played yet. Is there a penalty?",
    choices: [
      "No penalty — touching sand to prevent a fall is not a breach",
      "Two-stroke penalty for deliberately touching the sand",
      "One-stroke penalty for touching the sand near your ball",
      "No penalty, but only if your hand didn't touch sand near the ball",
    ],
    correct: 0,
    rule: "Rule 12.2b(1), Exception",
    explanation:
      "The exceptions to Rule 12.2b allow you to touch sand in a bunker for various reasons, including preventing a fall. The rule penalizes deliberate actions to test conditions or improve conditions for the stroke — not incidental or accidental contact.",
    tags: ["bunker", "sand", "touching-sand"],
  },
  {
    id: "bg20",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "You pick up your ball in the bunker to take an unplayable lie. You choose back-on-the-line relief and want to drop outside the bunker. How many penalty strokes does this cost?",
    choices: [
      "Two penalty strokes total",
      "One penalty stroke — same as any unplayable ball relief",
      "Three penalty strokes",
      "One penalty stroke, plus you lose the right to clean the ball",
    ],
    correct: 0,
    rule: "Rule 19.3b",
    explanation:
      "Under Rule 19.3b, if your ball is in a bunker and you choose to take back-on-the-line relief outside the bunker, the cost is two penalty strokes total (one additional stroke beyond the normal one-stroke penalty for unplayable ball relief). The three options that keep the ball in the bunker each cost one penalty stroke.",
    tags: ["bunker", "relief", "dropping"],
  },
  {
    id: "bg21",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Two players' balls are in the same bunker. Player A plays first and their ball comes to rest near Player B's ball. May Player B rake the area disturbed by Player A's shot before playing?",
    choices: [
      "Yes — Player B may smooth sand disturbed by Player A, as this is caring for the course and does not test conditions for Player B's own stroke",
      "No — no one may smooth sand while another ball is still in the bunker",
      "Only if Player B's ball is not within two club-lengths of the disturbed area",
      "Yes, but only with permission from Player A",
    ],
    correct: 0,
    rule: "Rule 12.2b(2) and (3)",
    explanation:
      "The restrictions in Rule 12.2b apply to each player individually with respect to their own ball. Player B may smooth sand in the bunker at any time for the purpose of caring for the course, as long as it does not improve conditions affecting Player B's next stroke. If Player A's shot created footprints or disturbance away from Player B's ball, Player B may rake that area.",
    tags: ["bunker", "sand", "rake"],
  },
  {
    id: "bg22",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is in a bunker. You dig your feet into the sand to take a firm stance. Is there a penalty?",
    choices: [
      "No penalty — you are allowed to fairly take a stance, including digging your feet in",
      "Two-stroke penalty for deliberately moving sand",
      "No penalty, but you cannot dig in more than one inch",
      "One-stroke penalty for improving your lie",
    ],
    correct: 0,
    rule: "Rule 12.2b(1), Exception",
    explanation:
      "You are entitled to fairly take your stance in a bunker, which includes digging your feet into the sand for stability. This is specifically allowed under the exceptions to Rule 12.2b. However, you may not do more than is necessary to take a fair stance.",
    tags: ["bunker", "sand"],
  },
  {
    id: "bg23",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "Your ball is plugged (embedded) in the steep face of a bunker. Are you entitled to free relief for an embedded ball?",
    choices: [
      "No — embedded ball relief under Rule 16.3 does not apply in bunkers",
      "Yes — embedded ball relief applies everywhere on the course",
      "Yes, but only if the ball is embedded in its own pitch mark",
      "No, unless the Committee has adopted a Local Rule for bunkers",
    ],
    correct: 0,
    rule: "Rule 16.3a",
    explanation:
      "Rule 16.3 (embedded ball relief) only applies in the general area. It does not apply in bunkers, penalty areas, or on the putting green. If your ball is embedded in a bunker, your options are to play it as it lies or declare it unplayable (with penalty).",
    tags: ["bunker", "embedded", "relief"],
  },

  // =============================================
  // RULE 13: PUTTING GREENS (bg24–bg43) — 20 scenarios
  // =============================================

  {
    id: "bg24",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is on the putting green. You pick it up to clean it. While cleaning, you notice a small scuff. May you replace it with a different ball?",
    choices: [
      "No — when you lift a ball on the putting green to clean it, you must replace the same ball",
      "Yes — you may always substitute a ball on the putting green",
      "Yes, but only if the original ball is damaged",
      "No, unless your playing partners agree",
    ],
    correct: 0,
    rule: "Rule 14.1a",
    explanation:
      "When you lift your ball under a Rule that requires replacing it on the same spot (such as lifting on the green), you must replace the original ball. You may only substitute a ball when the Rules specifically allow it (e.g., when a ball is cut or cracked, or when taking relief with a drop).",
    tags: ["putting-green", "lifting", "cleaning", "substituted-ball"],
  },
  {
    id: "bg25",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "You mark and lift your ball on the putting green. Before replacing it, you repair a large ball mark directly on your line of putt. Is this allowed?",
    choices: [
      "Yes — you may repair ball marks and almost any other damage on the putting green at any time",
      "No — you cannot repair damage on your line of putt",
      "Only ball marks from your own ball, not others",
      "Yes, but only before you mark and lift your ball",
    ],
    correct: 0,
    rule: "Rule 13.1c(2)",
    explanation:
      "Under Rule 13.1c, you may repair almost any damage on the putting green, including ball marks, spike marks, club indentations, animal damage, and old hole plugs. This can be done at any time, including on your line of putt.",
    tags: ["putting-green", "ball-marker", "marking"],
  },
  {
    id: "bg26",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "On the putting green, there is a natural blemish in the grass — a small bare spot that has always been there. Can you repair it before putting?",
    choices: [
      "No — natural imperfections and natural wear of the hole cannot be repaired",
      "Yes — you may repair any imperfection on the putting green",
      "Only if it is within one club-length of the hole",
      "Yes, but only with the Committee's permission",
    ],
    correct: 0,
    rule: "Rule 13.1c(2)",
    explanation:
      "While you may repair almost any 'damage' on the putting green (spike marks, ball marks, animal damage, etc.), you cannot repair natural imperfections in the surface or natural wear of the hole. A natural bare spot is a surface imperfection, not damage.",
    tags: ["putting-green"],
  },
  {
    id: "bg27",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your putt stops right on the edge of the hole, with part of the ball hanging over the lip. How long do you have to wait to see if it falls in?",
    choices: [
      "You must reach the hole in a reasonable time, then wait 10 seconds",
      "30 seconds from when the ball stops moving",
      "There is no time limit — you may wait as long as you want",
      "You must play it immediately without waiting",
    ],
    correct: 0,
    rule: "Rule 13.3a",
    explanation:
      "When any part of your ball overhangs the lip of the hole, you are allowed a reasonable time to reach the hole, plus 10 seconds to see if the ball will fall in. If it falls in within that time, it counts as holed with your last stroke. If it doesn't fall in, it is treated as at rest.",
    tags: ["putting-green"],
  },
  {
    id: "bg28",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is overhanging the lip of the hole. You wait 10 seconds and it doesn't fall in. You tap it in. Then the wind blows and the ball would have fallen in if you'd waited longer. What's the ruling?",
    choices: [
      "The ball was at rest after the 10-second waiting period — your tap-in counts as a separate stroke",
      "The ball is considered holed with the previous stroke since wind would have knocked it in",
      "You get to choose which result you prefer",
      "Play must be restarted from the lip of the hole",
    ],
    correct: 0,
    rule: "Rule 13.3a",
    explanation:
      "Once the 10-second waiting period expires (after reasonably reaching the hole), the ball is deemed at rest. Your tap-in counts as an additional stroke. It doesn't matter what might have happened afterward — the Rules set a clear 10-second window.",
    tags: ["putting-green", "wind"],
  },
  {
    id: "bg29",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is overhanging the lip. After 15 seconds it falls into the hole on its own. What's the ruling?",
    choices: [
      "The ball is holed, but you add one penalty stroke to your score for the hole (your last stroke plus one)",
      "The ball is considered holed with your last stroke — no penalty",
      "You must replace the ball on the lip and tap it in with no penalty",
      "Two-stroke penalty and you must replace the ball on the lip",
    ],
    correct: 0,
    rule: "Rule 13.3a",
    explanation:
      "If the ball falls into the hole after the 10-second waiting period (plus a reasonable time to reach the hole), the ball is considered holed. However, one penalty stroke is added to your score for the hole. So if you were putting for par, it would count as a bogey.",
    tags: ["putting-green"],
  },
  {
    id: "bg30",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is on the putting green. Your playing partner's ball is off the green. They ask you to leave the flagstick in. You putt with the flagstick in and your ball hits it. Is there a penalty?",
    choices: [
      "No penalty — any player may choose to putt with the flagstick in, and there is no penalty if the ball hits it",
      "Two-stroke penalty because you putted from the green and hit the flagstick",
      "No penalty, but you must replay the putt",
      "One-stroke penalty for the player who asked you to leave it in",
    ],
    correct: 0,
    rule: "Rule 13.2a(2)",
    explanation:
      "Since the 2019 Rules, there is no penalty if your ball (played from anywhere, including the putting green) hits the flagstick left in the hole. Each player makes their own decision about whether to have the flagstick in, out, or attended.",
    tags: ["putting-green", "flagstick"],
  },
  {
    id: "bg31",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "You ask another player to attend the flagstick while you putt. They remove the flagstick as your ball approaches, but accidentally drop it into the path of your moving ball. Your ball hits the dropped flagstick. What happens?",
    choices: [
      "No penalty to you — the ball is played as it lies (or if on the green, you choose: play as it lies or cancel and replay)",
      "Two-stroke penalty on the person who dropped the flagstick",
      "You must replay the putt — no penalty to anyone",
      "One-stroke penalty on you for not removing the flagstick yourself",
    ],
    correct: 0,
    rule: "Rule 13.2b(2), Rule 11.1b",
    explanation:
      "If someone attending the flagstick accidentally drops it and your ball hits it, the person attending is considered to have deliberately moved the flagstick. If your ball was played from the putting green, you get to choose: play the ball as it lies or cancel the stroke and replay. No penalty to you.",
    tags: ["putting-green", "flagstick"],
  },
  {
    id: "bg32",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball lands on the wrong putting green (a green for a different hole). What must you do?",
    choices: [
      "You must take free relief — you cannot play from a wrong green",
      "Play it as it lies — it's just another part of the course",
      "Take a one-stroke penalty and drop off the green",
      "You may choose to take free relief or play it as it lies",
    ],
    correct: 0,
    rule: "Rule 13.1f",
    explanation:
      "You must NOT play from a wrong putting green. You must take free relief by finding the nearest point of complete relief in the general area (not on any putting green, not nearer the hole) and drop within one club-length. This relief is mandatory and free.",
    tags: ["putting-green", "wrong-green", "free-relief", "dropping"],
  },
  {
    id: "bg33",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is on the putting green. Your caddie marks and lifts it without you asking or authorizing them to do so. Is there a penalty?",
    choices: [
      "No penalty — your caddie is always authorized to mark, lift, and clean your ball on the putting green",
      "One-stroke penalty because only the player can lift the ball",
      "Two-stroke penalty for the caddie acting without authorization",
      "No penalty, but only if the caddie replaces the ball before you arrive",
    ],
    correct: 0,
    rule: "Rule 14.1b",
    explanation:
      "On the putting green, a player's caddie may mark and lift the player's ball without specific authorization. This is one of the few places where the caddie has automatic permission to lift the ball. The caddie may also clean the ball.",
    tags: ["putting-green", "caddie", "marking", "lifting"],
  },
  {
    id: "bg34",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Before putting, you press down on the green with your putter behind the ball to test how firm the surface is. Is this allowed?",
    choices: [
      "No — you must not test the surface of the putting green by rubbing or rolling a ball, or by roughening or scraping the surface",
      "Yes — you can test the surface however you like on the putting green",
      "Only if it's your first putt on this green",
      "Yes, as long as you don't do it on your line of putt",
    ],
    correct: 0,
    rule: "Rule 13.1e",
    explanation:
      "Rule 13.1e prohibits testing the surface of the putting green before or between strokes by deliberately rubbing the surface, rolling a ball to test it, or scraping/roughening the surface. Pressing down behind the ball to test firmness would be considered testing the surface.",
    tags: ["putting-green"],
  },
  {
    id: "bg35",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "Between holes, you roll a ball on the putting green you just finished playing to check the speed. Is there a penalty?",
    choices: [
      "No — the restriction on testing the green surface only applies to the green of the hole being played or any practice green before the round",
      "Yes, two-stroke penalty on the next hole",
      "No, but only if all players in the group have finished the hole",
      "Yes, one-stroke penalty applied to the hole just completed",
    ],
    correct: 0,
    rule: "Rule 13.1e",
    explanation:
      "Rule 13.1e prohibits testing the surface of the putting green of the hole being played. Between holes, you may practice putting or chipping on the green of the hole just completed (Rule 5.5b), which implicitly allows some 'testing.' However, you must not unreasonably delay play.",
    tags: ["putting-green"],
  },
  {
    id: "bg36",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "A fellow competitor's ball is on the putting green and is on your line of putt. You ask them to mark and lift it. Must they comply?",
    choices: [
      "Yes — any player may ask another player to mark and lift their ball on the green if it might help or interfere with play",
      "No — they can refuse unless their ball physically blocks your ball",
      "Only in match play, not stroke play",
      "Yes, but only if both balls are on the green",
    ],
    correct: 0,
    rule: "Rule 15.3b",
    explanation:
      "Under Rule 15.3b, if you reasonably believe another ball on the putting green might help or interfere with play, you may require the other player to mark and lift their ball. The player must comply.",
    tags: ["putting-green", "ball-marker", "marking", "stroke-play"],
  },
  {
    id: "bg37",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "You are putting and accidentally hit your ball twice during the stroke (a double hit). What is the ruling?",
    choices: [
      "No penalty — it counts as one stroke, and you play the ball as it lies",
      "One-stroke penalty and you play the ball as it lies",
      "Two-stroke penalty and you must replay the putt",
      "The stroke doesn't count — replay the putt",
    ],
    correct: 0,
    rule: "Rule 10.1a",
    explanation:
      "Under the current Rules (since 2019), if your club accidentally strikes the ball more than once during a single stroke, there is no penalty. It counts as one stroke, and you play the ball as it lies.",
    tags: ["putting-green"],
  },
  {
    id: "bg38",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "There is sand and loose soil on the putting green on your line of putt. May you brush it away?",
    choices: [
      "Yes — sand and loose soil on the putting green are loose impediments and may be removed",
      "No — sand and soil are part of the course and cannot be moved",
      "Only if the sand came from a bunker shot",
      "Yes, but only with your hand, not your club or towel",
    ],
    correct: 0,
    rule: "Rule 15.1a, Definition of Loose Impediment",
    explanation:
      "Sand and loose soil are loose impediments only when they are on the putting green. You may remove them from the green without penalty. Sand and loose soil anywhere else on the course are NOT loose impediments (except on the green).",
    tags: ["putting-green", "sand", "loose-impediment"],
  },
  {
    id: "bg39",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is on the putting green. You place your putter head on the green in front of the ball to show your caddie the line of putt. Is this allowed?",
    choices: [
      "Yes, as long as you do not press anything down to improve your line and you lift it before the stroke is made",
      "No — placing anything on the green to indicate the line of putt is a penalty",
      "Yes, but only your caddie can do it, not you",
      "No — you cannot indicate the line of putt with any object",
    ],
    correct: 0,
    rule: "Rule 10.2b(2)",
    explanation:
      "You or your caddie may point out the line of putt by touching the putting green, as long as doing so does not improve conditions for the stroke. However, you must not place an object on the green to show the line. Briefly touching the green with a putter to indicate direction is allowed as long as conditions are not improved.",
    tags: ["putting-green", "caddie"],
  },
  {
    id: "bg40",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "In stroke play, you putt from the green and your ball hits another player's ball at rest on the green. The other player had not marked and lifted their ball. Who is penalized?",
    choices: [
      "You (the player who made the stroke) get a two-stroke penalty — it's your responsibility to ask the other player to mark",
      "The other player gets a two-stroke penalty for not marking",
      "Both players get a one-stroke penalty",
      "No penalty to either player in stroke play",
    ],
    correct: 0,
    rule: "Rule 11.1a",
    explanation:
      "In stroke play, when both balls are on the putting green and your putt hits another ball at rest on the green, you (the player who made the stroke) get a two-stroke penalty. The other player's ball must be replaced. It is your responsibility to have the other ball marked before you putt.",
    tags: ["putting-green", "stroke-play"],
  },
  {
    id: "bg41",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "In match play, you putt from the green and your ball hits your opponent's ball, which is also on the green. Is there a penalty?",
    choices: [
      "No penalty to either player — in match play, there is no penalty when a ball played from the green hits another ball on the green",
      "You lose the hole",
      "Two-stroke penalty on you",
      "Your opponent may choose to cancel your stroke and make you replay",
    ],
    correct: 0,
    rule: "Rule 11.1a",
    explanation:
      "The two-stroke penalty for hitting another ball on the green only applies in stroke play, not match play. In match play, there is no penalty. Both balls are played as they lie (the struck ball must be replaced to its original spot).",
    tags: ["putting-green", "match-play"],
  },
  {
    id: "bg42",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "You accidentally step on and move your ball on the putting green while walking to read the line. What do you do?",
    choices: [
      "No penalty — replace the ball on its original spot",
      "One-stroke penalty — replace the ball",
      "No penalty — play it from where it moved to",
      "One-stroke penalty — play it from the new spot",
    ],
    correct: 0,
    rule: "Rule 9.4b, Exception 1",
    explanation:
      "If you accidentally cause your ball to move on the putting green, there is no penalty. You must replace the ball on its original spot (estimated if necessary). This special exception for the putting green was introduced in the 2019 Rules to simplify the game.",
    tags: ["putting-green"],
  },
  {
    id: "bg43",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "Your ball is on the putting green. You lift it, clean it, and replace it. Heavy rain then creates temporary water around your ball. May you take relief?",
    choices: [
      "Yes — free relief from temporary water on the green: place the ball at the nearest point of complete relief, not nearer the hole (may be off the green)",
      "No — once your ball is replaced on the green, you must play it as it lies",
      "Yes, but you must drop the ball, not place it",
      "Only if the temporary water completely covers your ball",
    ],
    correct: 0,
    rule: "Rule 16.1d",
    explanation:
      "You are entitled to free relief from temporary water on the putting green. Unlike relief in the general area, relief on the green is taken by placing (not dropping) the ball at the nearest point of complete relief, which may be off the putting green in the general area. The ball must not be placed nearer the hole.",
    tags: ["putting-green", "temporary-water", "casual-water", "free-relief", "placing"],
  },

  // =============================================
  // RULE 14: PROCEDURES FOR BALL (lr5–lr19) — 15 scenarios
  // =============================================

  {
    id: "lr5",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "You are taking free relief from a cart path. You drop the ball from knee height and it lands in the relief area but then rolls outside the relief area. What do you do?",
    choices: [
      "Drop again from knee height in the relief area. If it rolls out a second time, place the ball where the second drop first hit the ground.",
      "Play the ball where it came to rest, even outside the relief area",
      "Drop again — you may drop as many times as needed",
      "Place the ball at the edge of the relief area closest to where it rolled out",
    ],
    correct: 0,
    rule: "Rule 14.3c(2)",
    explanation:
      "If a properly dropped ball comes to rest outside the relief area, you drop a second time. If the second drop also rolls outside the relief area, you place the ball on the spot where the second drop first hit the ground. You never drop more than twice.",
    tags: ["dropping", "cart-path", "immovable-obstruction", "relief"],
  },
  {
    id: "lr6",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You drop a ball and it comes to rest in the relief area, but it rolls closer to the hole than your nearest point of relief (though still in the relief area). Must you re-drop?",
    choices: [
      "No — as long as the ball comes to rest within the relief area, the drop is valid even if it's closer to the hole than the nearest point of relief",
      "Yes — the ball must not end up closer to the hole than the nearest point of relief",
      "Only if it rolled more than one club-length from where it landed",
      "Yes — you must re-drop and then place if it happens again",
    ],
    correct: 0,
    rule: "Rule 14.3c",
    explanation:
      "The relief area already has the 'not nearer the hole' restriction built in. As long as the ball comes to rest within the properly defined relief area (which by definition is not nearer the hole than the reference point), the drop is valid. The relief area's boundaries, not the nearest point of relief, determine where the ball must come to rest.",
    tags: ["dropping", "nearest-point-relief", "club-length"],
  },
  {
    id: "lr7",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "You need to take a drop. You drop the ball from knee height but accidentally toss it slightly sideways instead of dropping it straight down. What happens?",
    choices: [
      "The drop doesn't count — re-drop correctly without penalty",
      "One-stroke penalty, but the ball is in play",
      "Two-stroke penalty, and you must re-drop",
      "No issue — the direction of the drop doesn't matter",
    ],
    correct: 0,
    rule: "Rule 14.3b(2)",
    explanation:
      "The ball must be dropped straight down from knee height without any spin or direction. If you drop it incorrectly (tossing, spinning, or from the wrong height), the drop doesn't count and you must re-drop. There is no penalty for an incorrect drop as long as you correct it before playing.",
    tags: ["dropping"],
  },
  {
    id: "lr8",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You drop your ball in the wrong place (outside the correct relief area). You realize this before making your next stroke. What should you do?",
    choices: [
      "Pick up the ball and drop it in the correct relief area — no penalty since you haven't played it",
      "You must play it from where it lies with a two-stroke penalty",
      "One-stroke penalty and re-drop in the correct area",
      "Call a rules official to determine the correct spot",
    ],
    correct: 0,
    rule: "Rule 14.5a",
    explanation:
      "If you drop in the wrong place or in a wrong way but have not yet played the ball, you may correct the error without penalty. Simply lift the ball and drop it correctly. The penalty only applies if you play from the wrong place.",
    tags: ["dropping"],
  },
  {
    id: "lr9",
    category: "LIFTING_RETURNING",
    tier: "official",
    text: "You drop your ball in the wrong place and play it. You then realize the error before playing your next stroke. What are the consequences in stroke play?",
    choices: [
      "Two-stroke penalty for playing from a wrong place; you should correct it if it's a serious breach, otherwise the score with the penalty stands",
      "One-stroke penalty; continue play",
      "Disqualification — playing from a wrong place is always DQ",
      "No penalty if you correct it before teeing off on the next hole",
    ],
    correct: 0,
    rule: "Rule 14.7a",
    explanation:
      "Playing from a wrong place results in a two-stroke penalty under Rule 14.7a. If it is a serious breach (meaning you gained a significant advantage), you must correct the error by playing from the right place. If not a serious breach, you continue with the ball played from the wrong place, adding the two-stroke penalty.",
    tags: ["dropping", "stroke-play"],
  },
  {
    id: "lr10",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "You are allowed to lift your ball to identify it. Must you announce your intention to your playing partner or fellow competitor before lifting?",
    choices: [
      "Yes — you must first announce your intention and give them a chance to observe the process, and you must mark the ball's position",
      "No — you can lift it anytime to check",
      "Only in match play, not stroke play",
      "Only if a rules official is present",
    ],
    correct: 0,
    rule: "Rule 7.3",
    explanation:
      "Under Rule 7.3, if you reasonably believe a ball is yours but cannot identify it as it lies, you may lift it to identify it. You must first mark the spot and tell another player. You must give them a chance to observe the lifting and replacing. You may not clean the ball more than needed to identify it.",
    tags: ["lifting", "marking"],
  },
  {
    id: "lr11",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You take relief from temporary water. After dropping, the ball embeds in soft ground within the relief area. May you take embedded ball relief from the new spot?",
    choices: [
      "Yes — you may take embedded ball relief from the new position, since the ball is now embedded in the general area",
      "No — you must play the ball as it lies after a drop",
      "Only if the ball was embedded more than halfway",
      "Yes, but with an additional one-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 16.3b",
    explanation:
      "After a proper drop, if the ball embeds in its own pitch mark in the general area, you are entitled to take free relief under Rule 16.3 (embedded ball). There is no prohibition on taking additional relief after a drop if a new condition arises.",
    tags: ["dropping", "embedded", "temporary-water", "free-relief"],
  },
  {
    id: "lr12",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "When taking relief, how do you measure the one or two club-length relief area?",
    choices: [
      "Using the longest club in your bag other than a putter",
      "Using the club you intend to play next",
      "Using a standard driver length",
      "Using any club of your choice",
    ],
    correct: 0,
    rule: "Definition of Club-Length",
    explanation:
      "A 'club-length' is defined as the length of the longest club in your bag, other than a putter. This is typically your driver. You use this same club to measure relief areas regardless of which club you plan to hit next.",
    tags: ["club-length", "dropping", "relief"],
  },
  {
    id: "lr13",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You place your ball in the relief area after two drops rolled out. The ball doesn't stay on the placed spot because of a slope. What do you do?",
    choices: [
      "Try to place it a second time on the same spot. If it still won't stay, place it on the nearest spot where it will stay, not nearer the hole",
      "Drop again from a different spot in the relief area",
      "Press the ball into the ground until it stays",
      "Move to a flatter area within the relief area and place it there",
    ],
    correct: 0,
    rule: "Rule 14.2e",
    explanation:
      "Under Rule 14.2e, if a placed ball will not stay on the spot, you must try a second time. If it still won't stay, you place the ball on the nearest spot (not nearer the hole) where it will remain at rest. You may not press the ball into the ground.",
    tags: ["placing", "dropping", "relief"],
  },
  {
    id: "lr14",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "You take a penalty drop and the ball lands in a divot hole within your relief area. Must you play it from the divot?",
    choices: [
      "Yes — a divot hole is not an abnormal course condition, so no further relief is available",
      "No — you may re-drop to avoid the divot hole",
      "You can place the ball next to the divot hole",
      "You get free relief from divot holes after a drop",
    ],
    correct: 0,
    rule: "Definition of Abnormal Course Conditions",
    explanation:
      "A divot hole is not an abnormal course condition under the Rules. Once your ball comes to rest in the relief area (even in a divot hole), it is in play. You would need to play it as it lies or declare it unplayable for an additional penalty stroke.",
    tags: ["dropping", "relief"],
  },
  {
    id: "lr15",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You are taking back-on-the-line relief from a penalty area. You drop the ball on the line, but it rolls forward (closer to the hole) and comes to rest within one club-length of where it hit the ground, still on the line. Is the drop valid?",
    choices: [
      "No — for back-on-the-line relief, the ball must come to rest within one club-length of where it first hit the ground, and no nearer the hole than the spot on the line where it was dropped",
      "Yes — the ball is within one club-length of where it was dropped",
      "Yes — as long as it stays on the line, any distance is fine",
      "No — the ball must stop exactly where it hit the ground",
    ],
    correct: 0,
    rule: "Rule 14.3c(2), Rule 17.1d(2)",
    explanation:
      "For back-on-the-line relief, the relief area is a one-club-length circle around where the ball first hits the ground, but the ball must not come to rest nearer the hole than the chosen spot on the line. If the ball rolls nearer the hole, even slightly, you must drop again.",
    tags: ["dropping", "relief"],
  },
  {
    id: "lr16",
    category: "LIFTING_RETURNING",
    tier: "official",
    text: "In stroke play, your fellow competitor lifts your ball on the fairway without your authorization and without a Rule allowing it. What is the ruling?",
    choices: [
      "Your fellow competitor gets one penalty stroke; you must replace your ball",
      "No penalty to anyone; just replace the ball",
      "Two-stroke penalty on your fellow competitor",
      "You get one penalty stroke because it's your ball",
    ],
    correct: 0,
    rule: "Rule 9.5b",
    explanation:
      "When another player lifts your ball at rest without authorization (and not under a Rule that permits it), that player gets one penalty stroke. Your ball must be replaced on its original spot.",
    tags: ["lifting", "stroke-play"],
  },
  {
    id: "lr17",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "When taking free relief from a cart path, you find that the nearest point of complete relief is in a bush. Must you drop there?",
    choices: [
      "You don't have to take relief at all — free relief is optional, and you can play from the cart path instead",
      "Yes — you must take relief and drop at the nearest point of complete relief",
      "No — you may choose any point of complete relief within two club-lengths",
      "You may take the relief on the other side of the path instead",
    ],
    correct: 0,
    rule: "Rule 16.1a",
    explanation:
      "Free relief from abnormal course conditions is always optional in the general area. If the nearest point of complete relief would put you in a worse position (like a bush), you can simply play from the cart path. You are never forced to take free relief.",
    tags: ["cart-path", "immovable-obstruction", "free-relief", "nearest-point-relief"],
  },
  {
    id: "lr18",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You substitute a ball when taking free relief from a sprinkler head, even though the original ball was not damaged. Is this allowed?",
    choices: [
      "Yes — whenever you take relief by dropping or placing under a Rule, you may substitute a ball",
      "No — you must use the original ball when taking free relief",
      "Only if the original ball cannot be recovered",
      "Yes, but only in stroke play",
    ],
    correct: 0,
    rule: "Rule 14.3a",
    explanation:
      "When a Rule allows you to take relief by dropping or placing a ball, you may use the original ball or substitute another ball — even if the original is undamaged. This applies to both free relief and penalty relief situations.",
    tags: ["substituted-ball", "dropping", "free-relief", "immovable-obstruction", "sprinkler"],
  },
  {
    id: "lr19",
    category: "LIFTING_RETURNING",
    tier: "official",
    text: "You place your ball after two failed drops. After you remove your hand, the ball rolls to a spot two inches away and stops. Is the ball in play?",
    choices: [
      "No — a placed ball must come to rest on the spot where it was placed. If it moves, you must replace it on that spot.",
      "Yes — the ball is in play wherever it comes to rest after being placed",
      "Only if it stayed within one club-length of the placed spot",
      "You must re-place it with a one-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 14.2e",
    explanation:
      "When a ball is placed and it does not stay on the required spot, you must try to place it again. If it still won't stay (after two attempts), you place it on the nearest spot where it will remain at rest, not nearer the hole. A ball that moves from the placed spot must be replaced.",
    tags: ["placing"],
  },

  // =============================================
  // RULE 15: LOOSE IMPEDIMENTS & MOVABLE OBSTRUCTIONS (fr7–fr16) — 10 scenarios
  // =============================================

  {
    id: "fr7",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "A pine cone is directly behind your ball in the fairway. You remove it and your ball moves. What happens?",
    choices: [
      "One-stroke penalty; you must replace the ball on its original spot",
      "No penalty; replace the ball",
      "No penalty; play the ball from its new position",
      "Two-stroke penalty; replace the ball",
    ],
    correct: 0,
    rule: "Rule 15.1b",
    explanation:
      "You are always allowed to remove loose impediments (like a pine cone). However, if removing a loose impediment causes your ball to move (outside the putting green), you get one penalty stroke and must replace the ball. On the putting green, there would be no penalty.",
    tags: ["loose-impediment", "fairway", "general-area"],
  },
  {
    id: "fr8",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "An acorn is sitting against your ball on the putting green. You flick it away and your ball moves slightly. What happens?",
    choices: [
      "No penalty — replace the ball on its original spot",
      "One-stroke penalty; replace the ball",
      "No penalty; play the ball from the new position",
      "Two-stroke penalty for moving your ball",
    ],
    correct: 0,
    rule: "Rule 15.1b, Exception",
    explanation:
      "On the putting green, if your ball moves while you are removing a loose impediment, there is no penalty. You simply replace the ball on its original spot. This special exception applies only on the putting green — elsewhere, moving your ball while removing a loose impediment costs one penalty stroke.",
    tags: ["putting-green", "loose-impediment"],
  },
  {
    id: "fr9",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Is a half-eaten apple left by a spectator considered a loose impediment or a movable obstruction?",
    choices: [
      "It's a movable obstruction — once a natural object has been manufactured or processed, it's artificial",
      "It's a loose impediment because it was originally natural",
      "It depends on whether it's biodegradable",
      "It's neither — it's just litter and cannot be moved",
    ],
    correct: 0,
    rule: "Definition of Obstruction, Definition of Loose Impediment",
    explanation:
      "A loose impediment must be a natural object that is not fixed or growing, not solidly embedded, and not sticking to the ball. Manufactured or processed food items (even if originally natural) are artificial objects, making them obstructions. Since a half-eaten apple can be easily moved, it's a movable obstruction — either way, you may remove it without penalty.",
    tags: ["loose-impediment", "movable-obstruction"],
  },
  {
    id: "fr10",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball comes to rest against a movable distance marker (a small stake in the ground that is easily pulled out). May you remove it?",
    choices: [
      "Yes — if the stake is easily movable, it's a movable obstruction and can be removed without penalty",
      "No — stakes in the ground are immovable obstructions",
      "Yes, but with a one-stroke penalty",
      "Only if the Committee has designated it as movable",
    ],
    correct: 0,
    rule: "Rule 15.2a",
    explanation:
      "If a distance marker or yardage stake can be easily moved (without unreasonable effort or damaging the course), it is a movable obstruction. You may remove it without penalty. If your ball moves when you do, replace it without penalty.",
    tags: ["movable-obstruction"],
  },
  {
    id: "fr11",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is near a white out-of-bounds stake. The stake interferes with your backswing. May you remove the stake?",
    choices: [
      "No — boundary objects (OB stakes, fences, walls) are not obstructions and must not be moved",
      "Yes — any stake can be removed if it interferes with your swing",
      "Only if the stake is loose in the ground",
      "Yes, but you must replace it after your shot",
    ],
    correct: 0,
    rule: "Definition of Boundary Object, Rule 8.1a",
    explanation:
      "Boundary objects (white stakes, fences, walls defining OB) are not obstructions — they are fixed parts of the course. You must not move them. If an OB stake interferes with your swing, your options are to play it as it lies or take an unplayable ball (with penalty).",
    tags: ["immovable-obstruction"],
  },
  {
    id: "fr12",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Sand is splashed onto the fairway from a bunker shot. Your ball is in the fairway and the sand is on your line of play. May you brush the sand away?",
    choices: [
      "No — sand and loose soil are only loose impediments when on the putting green, not in the general area",
      "Yes — sand is always a loose impediment",
      "Only if the sand landed after your ball was at rest",
      "Yes, but only with your club, not your hand",
    ],
    correct: 0,
    rule: "Definition of Loose Impediment",
    explanation:
      "Sand and loose soil are loose impediments only on the putting green. Elsewhere on the course (fairway, rough, etc.), sand and loose soil are NOT loose impediments and cannot be removed. Brushing sand off your line in the fairway would be improving conditions, resulting in a penalty.",
    tags: ["sand", "fairway", "general-area", "loose-impediment"],
  },
  {
    id: "fr13",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "A large rock is directly behind your ball. It is partially embedded in the ground but you could pull it out with effort. Is it a loose impediment?",
    choices: [
      "No — if the object is solidly embedded in the ground, it is not a loose impediment and cannot be removed",
      "Yes — any natural object can be removed",
      "It depends on the size of the rock",
      "Yes, as long as you don't improve your lie",
    ],
    correct: 0,
    rule: "Definition of Loose Impediment",
    explanation:
      "A loose impediment must not be solidly embedded in the ground. If a rock is solidly embedded (not just sitting on or lightly resting in the surface), it is not a loose impediment and you may not remove it. Whether something is 'solidly embedded' is a judgment call — if it requires more than minimal effort to remove, it's likely embedded.",
    tags: ["loose-impediment", "general-area"],
  },
  {
    id: "fr14",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is in the rough and resting against a movable obstruction (a plastic water bottle). You move the bottle and your ball rolls into a worse spot. What do you do?",
    choices: [
      "Replace the ball on its original spot — no penalty when a ball moves due to removing a movable obstruction",
      "Play the ball from its new position — no penalty",
      "One-stroke penalty; play from the new position",
      "One-stroke penalty; replace the ball on the original spot",
    ],
    correct: 0,
    rule: "Rule 15.2a(2)",
    explanation:
      "When you remove a movable obstruction and your ball moves as a result, the ball must be replaced on its original spot. There is no penalty. This applies anywhere on the course.",
    tags: ["movable-obstruction", "rough", "general-area"],
  },
  {
    id: "fr15",
    category: "FREE_RELIEF",
    tier: "official",
    text: "A red penalty area stake is in your way. The stake has a small base and can be easily pulled out. May you remove it?",
    choices: [
      "No — penalty area stakes are boundary-defining objects that are deemed immovable and must not be removed",
      "Yes — any easily movable stake is a movable obstruction",
      "Only in the general area, not near a penalty area",
      "Yes, but you must replace it after your stroke",
    ],
    correct: 0,
    rule: "Definition of Obstruction, Committee Procedures",
    explanation:
      "Penalty area stakes define the edge of the penalty area. They are typically treated as immovable obstructions or may be movable obstructions depending on how the Committee defines them. However, many Committees specify in the Local Rules that penalty area stakes are immovable obstructions. The answer depends on the specific course's Local Rules — but the default under the Rules is that they can be removed if easily movable, unless the Committee says otherwise. In practice, most courses define them as immovable.",
    tags: ["penalty-area", "movable-obstruction"],
  },
  {
    id: "fr16",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Dew is on the grass in front of your ball. May you towel off the dew to improve your line of play?",
    choices: [
      "No — dew is not a loose impediment and removing it would be improving conditions for your stroke",
      "Yes — dew is temporary water and you get free relief",
      "Yes — dew is a loose impediment that can be removed",
      "Only on the putting green",
    ],
    correct: 0,
    rule: "Rule 8.1a, Definition of Loose Impediment",
    explanation:
      "Dew and frost are specifically excluded from the definitions of both 'loose impediment' and 'temporary water.' They are simply natural conditions of the course. Removing dew from your line of play would be improving conditions for your stroke, resulting in a penalty under Rule 8.1a.",
    tags: ["general-area", "fairway"],
  },

  // =============================================
  // RULE 16: ABNORMAL COURSE CONDITIONS, DANGEROUS ANIMAL, EMBEDDED BALL (fr17–fr26) — 10 scenarios
  // =============================================

  {
    id: "fr17",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is in the rough and a large fire ant mound is between your ball and the hole, but it doesn't affect your stance or swing — only your line of play. Do you get free relief?",
    choices: [
      "No — free relief from abnormal course conditions requires interference with your ball, stance, or area of intended swing, not just line of play",
      "Yes — an ant mound is an animal hole and you get free relief for line of play",
      "Yes, if you are within two club-lengths of the ant mound",
      "Only if the ants are dangerous",
    ],
    correct: 0,
    rule: "Rule 16.1a",
    explanation:
      "Interference from an abnormal course condition (including animal holes) exists only when the condition affects where your ball lies, your area of intended stance, or your area of intended swing. Interference with your line of play alone does not entitle you to relief (except on the putting green).",
    tags: ["animal-hole", "free-relief", "rough", "general-area"],
  },
  {
    id: "fr18",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is on a paved cart path. You determine the nearest point of complete relief is in the rough to the right. Can you instead take relief on the left side of the path where there's a better lie?",
    choices: [
      "No — you must use the nearest point of complete relief, even if it results in a less favorable position",
      "Yes — you may choose either side of the path",
      "Yes — you may take relief on the side that is nearer the hole",
      "Only if both sides are equidistant from the ball",
    ],
    correct: 0,
    rule: "Rule 16.1b",
    explanation:
      "The nearest point of complete relief is a single, specific point — the nearest spot where the abnormal condition no longer interferes with your lie, stance, and swing. You cannot choose between sides of a path. You must use the nearest point, even if it puts you in the rough or a worse position. (Remember, taking relief is optional.)",
    tags: ["cart-path", "immovable-obstruction", "nearest-point-relief", "free-relief"],
  },
  {
    id: "fr19",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is on the putting green and there is temporary water between your ball and the hole. Your ball itself is not in the water. Do you get relief?",
    choices: [
      "Yes — on the putting green, interference exists when temporary water is on your line of putt, even if the ball itself is not in it",
      "No — the temporary water must actually touch your ball",
      "Only if the temporary water is within one club-length of your ball",
      "No — line of play interference never gives relief",
    ],
    correct: 0,
    rule: "Rule 16.1a(2)",
    explanation:
      "On the putting green only, interference from an abnormal course condition also includes when the condition is on your line of putt. So temporary water on your line of putt, even if your ball is not in it, gives you free relief. This line-of-putt interference exception only applies on the putting green.",
    tags: ["putting-green", "temporary-water", "casual-water", "free-relief"],
  },
  {
    id: "fr20",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball lands in an area marked as ground under repair (GUR), but you have a good lie and want to play it. Must you take relief?",
    choices: [
      "No — relief from GUR in the general area is optional; you may play the ball as it lies",
      "Yes — you must always take relief from GUR",
      "Only if the GUR is marked with blue stakes",
      "You may play it, but with a one-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 16.1",
    explanation:
      "Relief from abnormal course conditions (including GUR) in the general area is always optional. You may choose to play the ball as it lies. However, the Committee may make certain GUR areas 'no play zones,' in which case relief is mandatory.",
    tags: ["ground-under-repair", "free-relief", "general-area"],
  },
  {
    id: "fr21",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is in a penalty area and there is temporary water around it. Can you take free relief from the temporary water?",
    choices: [
      "No — there is no free relief from abnormal course conditions when your ball is in a penalty area",
      "Yes — temporary water always gives free relief",
      "Yes, but only if the temporary water is not part of the penalty area itself",
      "Only if the penalty area is red-staked",
    ],
    correct: 0,
    rule: "Rule 16.1a",
    explanation:
      "Free relief from abnormal course conditions (including temporary water, GUR, and animal holes) is not available when your ball is in a penalty area. Your options in a penalty area are to play it as it lies or take penalty area relief under Rule 17.",
    tags: ["penalty-area", "temporary-water", "casual-water", "free-relief"],
  },
  {
    id: "fr22",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is embedded in the face of a bunker. Are you entitled to embedded ball relief?",
    choices: [
      "No — embedded ball relief only applies in the general area, not in bunkers",
      "Yes — embedded ball relief applies in all areas of the course",
      "Yes, but only if the ball is embedded below the surface",
      "No, but you get free relief for the abnormal condition",
    ],
    correct: 0,
    rule: "Rule 16.3a",
    explanation:
      "Rule 16.3 (relief for embedded ball) only applies when the ball is in the general area. Bunkers, penalty areas, and the putting green are excluded. If your ball is embedded in a bunker, you must play it as it lies or take unplayable ball relief (with penalty).",
    tags: ["bunker", "embedded", "free-relief"],
  },
  {
    id: "fr23",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "You discover a large snake near your ball in the general area. Are you entitled to relief?",
    choices: [
      "Yes — you may take free relief from a dangerous animal situation, even if the animal doesn't interfere with your stance or swing",
      "Only if the snake is actually touching your ball",
      "No — animals are part of the natural course",
      "Yes, but with a one-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 16.2",
    explanation:
      "Under Rule 16.2, you may take free relief if there is a dangerous animal (such as a snake, alligator, or bees) near your ball. You don't need the normal 'interference with stance/swing' test — the mere presence of the dangerous animal near your ball is enough. You drop within one club-length of the nearest spot that is not nearer the hole and is away from the dangerous animal.",
    tags: ["free-relief", "general-area"],
  },
  {
    id: "fr24",
    category: "FREE_RELIEF",
    tier: "official",
    text: "Your ball is near a dangerous animal (an alligator) in a penalty area. Can you take free relief for the dangerous animal situation?",
    choices: [
      "Yes — dangerous animal relief is available anywhere on the course, including penalty areas, but the relief must be taken within the penalty area",
      "No — no free relief is available in a penalty area",
      "Yes, and you may drop outside the penalty area for free",
      "Only if the Committee has declared it a dangerous situation",
    ],
    correct: 0,
    rule: "Rule 16.2b",
    explanation:
      "Unlike other abnormal course conditions, dangerous animal relief IS available in a penalty area. However, you must take relief within the penalty area (you cannot use the dangerous animal situation to get a free drop outside the penalty area). If you want to leave the penalty area, you must use normal penalty area relief under Rule 17.",
    tags: ["penalty-area", "free-relief"],
  },
  {
    id: "fr25",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is on a sprinkler head near the green. The nearest point of complete relief is behind you, further from the hole. Your playing partner says you can take relief to the side instead. Who is correct?",
    choices: [
      "You must use the nearest point of complete relief — even if it's farther from the hole; your partner is incorrect",
      "Your partner is correct — you can choose any direction for relief",
      "You're both wrong — you should take the nearest point that is not nearer the hole",
      "Either option is fine under the Rules",
    ],
    correct: 0,
    rule: "Rule 16.1b, Definition of Nearest Point of Complete Relief",
    explanation:
      "The nearest point of complete relief is a fixed reference point — the nearest spot where the condition no longer interferes with your lie, stance, and swing, and which is not nearer the hole. You cannot choose an alternative point just because the nearest one is less favorable. Remember: relief is optional, so you can always play from the sprinkler head.",
    tags: ["sprinkler", "immovable-obstruction", "nearest-point-relief", "free-relief"],
  },
  {
    id: "fr26",
    category: "FREE_RELIEF",
    tier: "official",
    text: "Your ball is in the rough and embedded in its own pitch mark. The Committee has adopted a Local Rule restricting embedded ball relief to 'fairway-cut areas only.' Are you entitled to relief?",
    choices: [
      "No — when the Committee restricts embedded ball relief to fairway-cut areas, you do not get relief in the rough",
      "Yes — the default Rule always overrides Local Rules",
      "Yes — embedded ball relief cannot be restricted by Local Rule",
      "Only if the ball is more than halfway below the surface",
    ],
    correct: 0,
    rule: "Rule 16.3, Model Local Rule F-2",
    explanation:
      "The Committee has the authority to restrict embedded ball relief to fairway-height areas through a Local Rule (Model Local Rule F-2). When this Local Rule is in effect, a ball embedded in the rough does not qualify for free relief. You would need to play it as it lies or declare it unplayable.",
    tags: ["embedded", "rough", "general-area", "free-relief"],
  },
];

