import { Scenario } from "@/types";

export const SCENARIOS_BATCH_3: Scenario[] = [
  // =============================================
  // BUNKERS & GREENS (Rules 12-13) — 25 scenarios
  // =============================================

  // --- Rule 12: Bunkers ---

  {
    id: "gen_bg1",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is in a fairway bunker. You rest your club on the sand directly behind the ball while taking your stance. Is there a penalty?",
    choices: [
      "Yes, the general penalty — you must not touch the sand in the area right in front of or behind the ball before the stroke",
      "No penalty as long as you didn't press down",
      "No penalty — grounding your club is only prohibited in penalty areas",
      "One-stroke penalty for grounding the club",
    ],
    correct: 0,
    rule: "Rule 12.2b(1)",
    explanation:
      "Under Rule 12.2b, before making a stroke at a ball in a bunker, you must not touch the sand with your club in the area right in front of or behind the ball. Resting your club on the sand behind the ball violates this restriction and results in the general penalty (two strokes in stroke play, loss of hole in match play).",
    tags: ["bunker", "touching sand", "grounding club", "fairway bunker"],
  },
  {
    id: "gen_bg2",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is in a greenside bunker. While walking into the bunker to reach your ball, you drag your feet through the sand. Is there a penalty?",
    choices: [
      "No penalty — walking through the sand to reach your ball is not a restricted action",
      "Yes, general penalty for touching sand before your stroke",
      "No penalty only if you walk outside the area near your ball",
      "One-stroke penalty for disturbing the bunker",
    ],
    correct: 0,
    rule: "Rule 12.2b",
    explanation:
      "Walking through the bunker to reach your ball is not one of the restricted actions under Rule 12.2b. The restrictions apply to deliberately touching sand to test it, touching it in the area in front of or behind the ball with a club, during a practice swing, or on the backswing. Simply walking to your ball is allowed.",
    tags: ["bunker", "touching sand", "walking", "greenside bunker"],
  },
  {
    id: "gen_bg3",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is in a bunker. Before your stroke, you pick up a cigarette butt (artificial object) that is lying near your ball. Is there a penalty?",
    choices: [
      "No penalty — a cigarette butt is a movable obstruction and may be removed anywhere without penalty",
      "Yes, two-stroke penalty for touching anything in the bunker",
      "No penalty only if it's not touching your ball",
      "One-stroke penalty for moving an obstruction in a bunker",
    ],
    correct: 0,
    rule: "Rule 15.2a",
    explanation:
      "A cigarette butt is a movable obstruction (a small artificial object). Under Rule 15.2a, you may remove any movable obstruction anywhere on the course without penalty, including in a bunker. If the ball moves during removal, it must be replaced without penalty.",
    tags: ["bunker", "movable obstruction", "sand", "artificial object"],
  },
  {
    id: "gen_bg4",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is buried in the steep face of a bunker. You declare it unplayable. You choose back-on-the-line relief but want to drop outside the bunker on a line going back from the hole through the ball's spot. How many penalty strokes?",
    choices: [
      "Two penalty strokes — the additional back-on-the-line option outside the bunker costs two strokes total",
      "One penalty stroke, same as any unplayable option",
      "Three penalty strokes",
      "No penalty — plugged lies receive free relief in bunkers",
    ],
    correct: 0,
    rule: "Rule 19.3b",
    explanation:
      "Under Rule 19.3b, for an unplayable ball in a bunker, the three standard options (stroke and distance, back-on-the-line in the bunker, lateral in the bunker) each cost one stroke. But for an additional penalty stroke (two total), you may take back-on-the-line relief outside the bunker.",
    tags: ["bunker", "unplayable in bunker", "plugged lie", "back-on-the-line", "penalty"],
  },
  {
    id: "gen_bg5",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is in a greenside bunker. You play your shot and the ball stays in the bunker. Before your next stroke from the bunker, you rake the footprints you made walking to your first shot. Is there a penalty?",
    choices: [
      "No penalty — you may smooth sand for course care purposes as long as it doesn't improve conditions for your next stroke",
      "Yes, general penalty — you cannot touch sand while your ball is still in the bunker",
      "No penalty only if you rake an area away from your ball",
      "One-stroke penalty for altering the bunker surface",
    ],
    correct: 0,
    rule: "Rule 12.2b(2)",
    explanation:
      "Rule 12.2b(2) allows smoothing sand in a bunker at any time for the purpose of caring for the course, provided it does not improve conditions affecting your next stroke. Raking footprints in an area that doesn't affect your next shot is permitted.",
    tags: ["bunker", "raking", "touching sand", "course care"],
  },
  {
    id: "gen_bg6",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "Your ball is in a bunker. You grab a handful of sand from the bunker and toss it in the air to test the wind direction. Is there a penalty?",
    choices: [
      "Yes, general penalty — tossing sand to gauge wind direction constitutes testing the condition of the bunker",
      "No penalty — checking the wind is always allowed",
      "No penalty — the restriction only covers touching sand with a club",
      "One-stroke penalty for testing conditions",
    ],
    correct: 0,
    rule: "Rule 12.2b(1)",
    explanation:
      "Rule 12.2b(1) prohibits deliberately touching sand in a bunker to test the condition of the sand. Picking up sand and tossing it to check wind is considered testing the condition of the bunker (similar to testing bunker texture). This results in the general penalty.",
    tags: ["bunker", "touching sand", "testing conditions", "wind"],
  },
  {
    id: "gen_bg7",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball lies on the lip of a bunker. Part of the ball overhangs the sand, but the ball is sitting entirely on grass and does not touch the sand. Is the ball in the bunker?",
    choices: [
      "No — a ball is in a bunker only when any part of it touches the sand or lies within the bunker edge. If it sits on grass above the sand, it is in the general area.",
      "Yes — any ball overhanging the bunker is considered in the bunker",
      "Yes — the ball is in the bunker if any part is above the sand",
      "It depends on whether the lip is a natural or man-made edge",
    ],
    correct: 0,
    rule: "Definition of Bunker",
    explanation:
      "A ball is 'in' a bunker when any part of the ball lies on or touches the sand within the edge of the bunker. If the ball rests entirely on the grass lip without touching sand, it is not in the bunker — it is in the general area, and bunker restrictions do not apply.",
    tags: ["bunker", "lip", "general area", "ball location"],
  },
  {
    id: "gen_bg8",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is in a bunker. You accidentally touch the sand with your club while removing a loose impediment (a twig). Is there a penalty for the sand contact?",
    choices: [
      "No penalty — incidentally touching the sand while removing a loose impediment is not a breach of Rule 12.2b",
      "Yes, general penalty — any club contact with sand before a stroke is penalized",
      "No penalty only if the twig was not touching your ball",
      "One-stroke penalty for touching sand with a club",
    ],
    correct: 0,
    rule: "Rule 12.2b, Rule 15.1a",
    explanation:
      "Rule 12.2b lists specific restricted actions (touching sand behind or in front of the ball, during a practice swing, or on the backswing). Incidentally touching sand while performing a permitted action like removing a loose impediment is not one of these restricted actions and does not result in a penalty.",
    tags: ["bunker", "touching sand", "loose impediment", "twig"],
  },
  {
    id: "gen_bg9",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "In a bunker, you take a practice swing well away from the ball (several feet to the side). Your club touches the sand during this practice swing. Is there a penalty?",
    choices: [
      "Yes, general penalty — you must not touch sand with your club during a practice swing anywhere in the bunker",
      "No penalty — the practice swing was far from the ball",
      "No penalty — practice swings are only restricted near the ball",
      "One-stroke penalty only",
    ],
    correct: 0,
    rule: "Rule 12.2b(1)",
    explanation:
      "Rule 12.2b(1) states you must not touch the sand in a bunker with your club during a practice swing. This restriction applies anywhere in the bunker, not just near the ball. Even a practice swing several feet from the ball that contacts sand results in the general penalty.",
    tags: ["bunker", "practice swing in bunker", "touching sand", "penalty"],
  },
  {
    id: "gen_bg10",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "Two players' balls are in the same bunker. Player A plays first, blasting sand over Player B's ball. May Player B brush the sand off their ball before playing?",
    choices: [
      "Yes — Player B may restore their original lie by removing the displaced sand, since the lie was altered by Player A's stroke",
      "No — Player B must play the ball as it lies with the extra sand",
      "Yes, but only by blowing on it, not by touching it",
      "Only if Player A rakes the bunker first",
    ],
    correct: 0,
    rule: "Rule 12.2b(2), Rule 8.1d(2)",
    explanation:
      "Under Rule 8.1d(2), when a player's lie is altered by another player, the affected player may restore the original lie. Player B may remove the sand that was displaced onto their ball by Player A's shot. This is specifically permitted and does not violate the bunker restrictions.",
    tags: ["bunker", "sand", "altered lie", "two balls"],
  },

  // --- Rule 13: Putting Greens ---

  {
    id: "gen_bg11",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "On the putting green, you repair a pitch mark (ball mark) on your line of putt. While repairing it, you accidentally improve the surface beyond what was damaged. Is there a penalty?",
    choices: [
      "Yes, general penalty if you improve the putting green beyond what was reasonably necessary to repair the damage",
      "No penalty — any repair work on the green is allowed",
      "No penalty — you're entitled to a perfect surface on your line",
      "One-stroke penalty for excessive repair",
    ],
    correct: 0,
    rule: "Rule 13.1c(2), Rule 8.1a",
    explanation:
      "While Rule 13.1c(2) allows repairing damage on the putting green, you may not go beyond what is reasonably necessary. If the repair actually improves the surface beyond what existed before the damage (for example, tamping down extra area or creating a smoother surface than what was there), it could constitute improving conditions under Rule 8.1a.",
    tags: ["putting green", "ball mark", "repair", "line of putt", "improving lie"],
  },
  {
    id: "gen_bg12",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is on the putting green. You want to use a towel to wipe morning dew off your line of putt. Is this allowed?",
    choices: [
      "No — dew and frost are not 'damage' and you may not remove them from the putting green to improve your line of putt",
      "Yes — you can clean any surface on the putting green",
      "Yes — dew is temporary water and you may remove it",
      "Only if all players in the group agree",
    ],
    correct: 0,
    rule: "Rule 13.1c(2), Rule 8.1a",
    explanation:
      "Dew and frost are not 'damage' on the putting green, so they cannot be repaired or removed under Rule 13.1c(2). Wiping away dew on your line of putt would improve conditions affecting your stroke in breach of Rule 8.1a, resulting in the general penalty.",
    tags: ["putting green", "dew", "line of putt", "improving lie"],
  },
  {
    id: "gen_bg13",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball is on the putting green. It overhangs the lip of the hole. You walk up to the hole, wait 12 seconds, and the ball falls in. What is your score?",
    choices: [
      "Your last stroke counts plus one penalty stroke — if the ball falls in after the 10-second waiting period, it is treated as holed with the last stroke plus a one-stroke penalty",
      "Your last stroke counts — the ball is holed with no penalty",
      "You must replace the ball on the lip and putt again",
      "The ball is holed with your last stroke plus a two-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 13.3a",
    explanation:
      "Under Rule 13.3a, you get a reasonable time to reach the hole plus 10 seconds. If the ball falls in within that time, it's holed with the last stroke and no penalty. If it falls in after the 10 seconds, it is still deemed holed with the last stroke, but you add one penalty stroke to your score for the hole.",
    tags: ["putting green", "ball overhanging", "lip of hole", "penalty", "holed"],
  },
  {
    id: "gen_bg14",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is on the putting green. Your playing partner asks you to leave the flagstick in the hole. You putt and the ball hits the flagstick but bounces out. Is there a penalty?",
    choices: [
      "No penalty — hitting the flagstick is allowed; the ball is played from where it comes to rest",
      "Two-stroke penalty for hitting the flagstick while putting on the green",
      "No penalty, but you must replay the putt",
      "One-stroke penalty; play the ball as it lies",
    ],
    correct: 0,
    rule: "Rule 13.2a(2)",
    explanation:
      "Under the 2019 Rules, there is no penalty for hitting the flagstick, whether it is attended, removed, or left in the hole, regardless of where on the course the stroke is made. If the ball bounces out after hitting the flagstick, play it from where it comes to rest.",
    tags: ["putting green", "flagstick", "no penalty", "bounce out"],
  },
  {
    id: "gen_bg15",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "Your ball lands on the wrong putting green (a practice green adjacent to the 5th hole). The nearest point of complete relief is in a bunker. Must you drop in the bunker?",
    choices: [
      "Yes — the nearest point of complete relief might be in a bunker, and you must use it, as long as it is not on any putting green or in a penalty area",
      "No — you may choose any relief point that is off the wrong green",
      "No — the relief area cannot be in a bunker; find the next nearest point",
      "Yes, but you get a free drop outside the bunker too",
    ],
    correct: 0,
    rule: "Rule 13.1f",
    explanation:
      "Under Rule 13.1f, when taking mandatory free relief from a wrong green, the nearest point of complete relief must not be on any putting green or in a penalty area, but it may be in a bunker or the general area. If the nearest point is in a bunker, that is where you must drop.",
    tags: ["wrong green", "putting green", "free relief", "bunker", "nearest point of relief"],
  },
  {
    id: "gen_bg16",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "On the putting green, your ball is resting against the flagstick in the hole. The entire ball is below the surface of the green. You remove the flagstick and the ball pops out of the hole. What is the ruling?",
    choices: [
      "The ball is holed — it was entirely below the surface when resting against the flagstick. Replace it on the lip; it counts as holed with the last stroke.",
      "The ball is not holed — it must remain in the hole after the flagstick is removed",
      "You must replay the putt since the ball left the hole",
      "The ball is holed only if it falls back in within 10 seconds",
    ],
    correct: 0,
    rule: "Rule 13.2c",
    explanation:
      "Under Rule 13.2c, when a ball rests against the flagstick and any part of it is below the surface of the putting green, the ball is holed. If the ball was entirely below the surface, it was already holed. If removing the flagstick causes the ball to move out, the ball is replaced on the lip and is deemed holed with the last stroke.",
    tags: ["putting green", "flagstick", "holed", "ball against flagstick"],
  },
  {
    id: "gen_bg17",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "You are on the putting green and your caddie touches the green behind your ball to point out the line of putt. Is there a penalty?",
    choices: [
      "Yes, general penalty — your caddie must not touch the putting green to indicate the line of putt",
      "No penalty — under the current Rules, a caddie may touch the putting green to indicate the line of play",
      "No penalty as long as the caddie doesn't improve the surface",
      "Penalty only if the caddie uses an object, not a finger",
    ],
    correct: 1,
    rule: "Rule 10.2b",
    explanation:
      "Under the 2023 Rules of Golf, there is no restriction on a caddie (or player) touching the putting green to point out the line of play. The old restriction was removed in 2019. The Rules do prohibit placing an object on the green to show the line and the caddie standing behind the player during the stroke, but simply touching the surface to indicate the line is permitted.",
    tags: ["putting green", "caddie", "line of putt", "penalty"],
  },
  {
    id: "gen_bg18",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "In match play, your opponent's putt finishes right next to the hole. You want to concede the next putt. Can you concede before your opponent marks the ball?",
    choices: [
      "Yes — you may concede a stroke at any time. The ball is considered holed with the next stroke. Your opponent may pick it up.",
      "No — concessions can only be made after the player addresses the ball",
      "Yes, but your opponent must still mark and replace the ball",
      "No — the ball must be at rest for at least 10 seconds before conceding",
    ],
    correct: 0,
    rule: "Rule 3.2b",
    explanation:
      "Under Rule 3.2b, a player may concede the opponent's next stroke at any time, including before the opponent marks, lifts, or addresses the ball. The opponent's ball is then treated as holed with the next stroke. The concession is final and cannot be withdrawn.",
    tags: ["putting green", "match play", "concession", "holed"],
  },
  {
    id: "gen_bg19",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "On the putting green, you mark your ball by placing a ball marker to the side of the ball instead of behind it. Is this legal?",
    choices: [
      "Yes — a ball marker may be placed right next to the ball; it does not have to be behind the ball",
      "No — the ball marker must be placed directly behind the ball",
      "Yes, but only if you use a coin rather than a manufactured ball marker",
      "No — the marker must be placed between the ball and the hole",
    ],
    correct: 0,
    rule: "Rule 14.1a",
    explanation:
      "Rule 14.1a requires marking the spot of the ball before lifting it. The recommended method is to place a ball-marker right behind the ball, but the Rules do not require the marker to be in a specific position relative to the ball. Placing it to the side is acceptable as long as it accurately marks the ball's position.",
    tags: ["putting green", "mark ball", "ball marker", "procedure"],
  },
  {
    id: "gen_bg20",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "You putt your ball and it hits the hole liner, which is sitting slightly above the surface of the green. The ball bounces back. A rules official determines the hole liner was improperly installed. What happens?",
    choices: [
      "The stroke is cancelled and must be replayed without penalty, since the improperly installed hole liner should not have affected the stroke",
      "Play the ball as it lies — no replay",
      "The ball is considered holed since it reached the hole",
      "Two-stroke penalty for not notifying the Committee before putting",
    ],
    correct: 0,
    rule: "Rule 13.2",
    explanation:
      "If a hole liner is sitting above the surface and deflects a ball that would otherwise have been holed or affected the ball's path, the Committee should address the situation. Generally, if the improper liner affected the outcome, the stroke may be replayed without penalty. The Committee has authority to resolve these situations fairly.",
    tags: ["putting green", "hole liner", "holed", "committee"],
  },
  {
    id: "gen_bg21",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is on the putting green. You use your putter to tap down a spike mark on your line of putt. Is this repair allowed?",
    choices: [
      "Yes — spike marks are damage that may be repaired on the putting green under the current Rules",
      "No — spike marks cannot be repaired on the putting green",
      "Yes, but only with a ball mark repair tool, not a putter",
      "Only if the Committee has adopted a Local Rule allowing it",
    ],
    correct: 0,
    rule: "Rule 13.1c(2)",
    explanation:
      "Under Rule 13.1c(2) (since 2019), you may repair almost any damage on the putting green, including spike marks, ball marks, shoe damage, and equipment indentations. You may use any tool (putter, repair tool, tee, etc.) or your hand. Only natural surface imperfections and natural wear of the hole cannot be repaired.",
    tags: ["putting green", "spike mark", "repair", "line of putt"],
  },
  {
    id: "gen_bg22",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "On the putting green, your ball is replaced after being marked and lifted. A strong gust of wind then blows it into the hole. Is the ball holed?",
    choices: [
      "No — the ball must be replaced on its original spot. Since it was lifted and replaced, natural forces moving it require replacement.",
      "Yes — the ball is holed; natural forces count",
      "Yes — wind is an outside influence and the stroke counts",
      "No — replace it with a one-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 13.1d(2)",
    explanation:
      "Under Rule 13.1d(2), when a ball has been lifted and replaced on the putting green and natural forces (like wind) then move it, the ball must be replaced on its original spot. This is different from a ball that was never lifted — which would be played from the new position. No penalty applies.",
    tags: ["putting green", "wind", "ball moved", "mark and lift", "replace"],
  },
  {
    id: "gen_bg23",
    category: "BUNKERS_GREENS",
    tier: "official",
    text: "In stroke play, your ball is on the green. Before putting, you roll a practice ball across a different part of the green to test the speed. Is there a penalty?",
    choices: [
      "Yes, general penalty — you must not test the surface of the putting green by rolling a ball during the play of a hole",
      "No penalty — testing is only prohibited on your own line of putt",
      "No penalty — it's a different part of the green",
      "No penalty — testing the green is allowed before your stroke",
    ],
    correct: 0,
    rule: "Rule 13.1e",
    explanation:
      "Under Rule 13.1e, you must not test the surface of any putting green during the play of a hole by rolling a ball or roughening or scraping the surface. This applies to the entire green surface, not just your line of putt. The general penalty applies.",
    tags: ["putting green", "testing surface", "practice putt", "stroke play"],
  },
  {
    id: "gen_bg24",
    category: "BUNKERS_GREENS",
    tier: "weekend",
    text: "Your ball is just off the putting green on the fringe. There is sand on the fringe in front of your ball. Can you brush the sand away?",
    choices: [
      "No — sand and loose soil are only loose impediments on the putting green, not on the fringe (general area), so you cannot brush them away to improve your line of play",
      "Yes — sand is a loose impediment everywhere",
      "Yes — the fringe is considered part of the putting green",
      "No, but you could blow on it",
    ],
    correct: 0,
    rule: "Definition of Loose Impediment, Rule 8.1a",
    explanation:
      "Sand and loose soil are loose impediments only on the putting green. The fringe is part of the general area, not the putting green. Therefore, sand on the fringe is not a loose impediment and cannot be removed. Doing so would improve conditions affecting your stroke, resulting in the general penalty.",
    tags: ["fringe", "sand", "loose impediment", "putting green", "line of putt"],
  },
  {
    id: "gen_bg25",
    category: "BUNKERS_GREENS",
    tier: "competitor",
    text: "On the putting green, you accidentally knock your ball off its spot with your putter while taking a practice stroke. What is the ruling?",
    choices: [
      "No penalty — replace the ball on its original spot. Accidentally moving your ball on the putting green is penalty-free.",
      "One-stroke penalty; replace the ball",
      "No penalty; play it from the new spot",
      "General penalty for hitting a ball at rest",
    ],
    correct: 0,
    rule: "Rule 13.1d(1)",
    explanation:
      "Under Rule 13.1d(1), there is no penalty if you (or your opponent in match play, or another player in stroke play) accidentally cause your ball to move on the putting green. Simply replace the ball on its original spot (or estimated spot). This exception applies only on the putting green.",
    tags: ["putting green", "accidentally moved", "no penalty", "replace"],
  },

  // =============================================
  // LIFTING & RETURNING (Rule 14) — 20 scenarios
  // =============================================

  {
    id: "gen_lr1",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "You are taking free relief from a cart path. You drop the ball from knee height. It lands in the relief area, bounces once, and rolls to rest inside the relief area. Is the drop valid?",
    choices: [
      "Yes — the drop is valid because the ball came to rest within the relief area",
      "No — the ball must not bounce during a drop",
      "Yes, but only if the ball did not roll more than two club-lengths",
      "No — you must re-drop if the ball bounced",
    ],
    correct: 0,
    rule: "Rule 14.3c",
    explanation:
      "Under Rule 14.3c, a dropped ball is in play when it comes to rest within the relief area. Bouncing is a normal part of a drop — there is no restriction on bouncing. The only requirement is that the ball ends up in the relief area.",
    tags: ["drop", "knee height", "relief area", "cart path"],
  },
  {
    id: "gen_lr2",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "When measuring your one-club-length relief area, which club do you use?",
    choices: [
      "The longest club in your bag except the putter",
      "The club you intend to use for your next shot",
      "Any club you choose",
      "A standard 48-inch driver",
    ],
    correct: 0,
    rule: "Definition of Club-Length",
    explanation:
      "The definition of 'club-length' specifies the longest club in the player's bag other than the putter. This is used for all relief area measurements. You always use this same club regardless of which club you plan to hit next.",
    tags: ["drop", "relief area", "club-length", "measurement"],
  },
  {
    id: "gen_lr3",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You drop your ball in the correct relief area. It comes to rest in a divot hole within the relief area. You don't like the lie. Can you re-drop?",
    choices: [
      "No — once a properly dropped ball comes to rest in the relief area, it is in play. You cannot re-drop because of a bad lie.",
      "Yes — you may re-drop once if the ball lands in a divot",
      "Yes — a divot hole entitles you to embedded ball relief",
      "No, but you can declare it unplayable without a penalty",
    ],
    correct: 0,
    rule: "Rule 14.3c",
    explanation:
      "When a dropped ball comes to rest within the relief area, it is the ball in play regardless of the lie. A divot hole is not grounds for re-dropping. If you pick it up without a Rule authorizing you to do so, you get a one-stroke penalty. You may declare it unplayable with a one-stroke penalty if desired.",
    tags: ["drop", "relief area", "divot", "ball in play"],
  },
  {
    id: "gen_lr4",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "Can your caddie drop the ball for you when you are taking relief?",
    choices: [
      "No — only the player may drop the ball; no one else may do it for you",
      "Yes — your caddie may drop on your behalf",
      "Yes — any member of your group may drop for you",
      "Only if you are physically unable to bend down",
    ],
    correct: 0,
    rule: "Rule 14.3b",
    explanation:
      "Under Rule 14.3b, the player must personally drop the ball. No one else — caddie, partner, or any other person — may drop the ball for the player. If someone else drops it, the ball must be re-dropped by the player.",
    tags: ["drop", "caddie", "procedure", "knee height"],
  },
  {
    id: "gen_lr5",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You are taking free relief from GUR. You determine the nearest point of complete relief and drop within one club-length. The ball rolls and comes to rest two club-lengths from the nearest point, but you think it's still in the relief area. Is the drop valid?",
    choices: [
      "No — for free relief under Rule 16.1b, the relief area is one club-length from the nearest point of relief. If the ball rolled beyond one club-length from that point, it is outside the relief area.",
      "Yes — the ball may roll up to two club-lengths after a drop",
      "Yes — as long as the ball stays on the course",
      "No — the ball must come to rest within 6 inches of where it hit the ground",
    ],
    correct: 0,
    rule: "Rule 14.3c(2), Rule 16.1b",
    explanation:
      "For free relief from abnormal course conditions, the relief area is one club-length from the nearest point of complete relief, not nearer the hole, in the same area of the course. If the ball rolls beyond this one-club-length zone, it has left the relief area and must be re-dropped.",
    tags: ["drop", "relief area", "GUR", "ground under repair", "re-drop"],
  },
  {
    id: "gen_lr6",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "You accidentally drop the ball from waist height instead of knee height. It lands and stays in the relief area. What should you do?",
    choices: [
      "Re-drop from knee height — a drop from the wrong height does not count, regardless of where the ball lands",
      "Play it — the ball is in the relief area so it's fine",
      "Take a one-stroke penalty and play it where it lies",
      "Place it where it landed instead of re-dropping",
    ],
    correct: 0,
    rule: "Rule 14.3b(2)",
    explanation:
      "Rule 14.3b requires dropping from knee height. If the ball is dropped from the wrong height, the drop does not count. You must re-drop from the correct height. There is no penalty for the incorrect drop itself, but playing the incorrectly dropped ball would incur a penalty.",
    tags: ["drop", "knee height", "re-drop", "procedure"],
  },
  {
    id: "gen_lr7",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You lift your ball to take relief from an immovable obstruction. Before dropping, you clean mud off the ball. Is this allowed?",
    choices: [
      "Yes — when a ball is lifted for relief (dropping or placing), you may always clean it",
      "No — you may only clean the ball on the putting green",
      "Yes, but only if the mud affects your ability to identify the ball",
      "No — cleaning is not allowed during a hole except on the green",
    ],
    correct: 0,
    rule: "Rule 14.1c",
    explanation:
      "Under Rule 14.1c, a ball that has been lifted may be cleaned whenever it is to be dropped or placed, with only a few narrow exceptions (identification under Rule 7.3, damage check under Rule 4.2c, or interference under Rule 15.3b). Taking relief from an obstruction allows full cleaning.",
    tags: ["clean ball", "drop", "immovable obstruction", "lifting"],
  },
  {
    id: "gen_lr8",
    category: "LIFTING_RETURNING",
    tier: "official",
    text: "You take back-on-the-line relief from a penalty area. You drop the ball on the line. It rolls forward (toward the hole) but stays within one club-length of where it first hit the ground. Is this a valid drop?",
    choices: [
      "No — for back-on-the-line relief, the ball must not come to rest nearer the hole than the spot where it first struck the ground, even if it stays within one club-length",
      "Yes — the ball is within one club-length of where it hit the ground",
      "Yes — the ball just needs to stay on the line",
      "No — the ball must land and stay at the exact point on the line",
    ],
    correct: 0,
    rule: "Rule 14.3c(2)",
    explanation:
      "For back-on-the-line relief, the relief area is a circle with a one-club-length radius around where the dropped ball first hits the ground, but the ball must not come to rest nearer the hole than that point. Rolling forward (closer to the hole) means the ball is outside the relief area and must be re-dropped.",
    tags: ["drop", "back-on-the-line", "relief area", "penalty relief", "re-drop"],
  },
  {
    id: "gen_lr9",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "You want to substitute a different ball when taking free relief from temporary water. Your original ball is not damaged. Is this allowed?",
    choices: [
      "Yes — when taking relief by dropping, you may always use either the original ball or a substituted ball",
      "No — you must use the original ball unless it is cut or cracked",
      "Yes, but only with a one-stroke penalty",
      "Only if you cannot retrieve the original ball",
    ],
    correct: 0,
    rule: "Rule 14.3a",
    explanation:
      "Under Rule 14.3a, when taking relief that requires dropping or placing, the player may use the original ball or substitute another ball. There is no requirement that the original ball be damaged or unplayable.",
    tags: ["substitution", "drop", "temporary water", "free relief"],
  },
  {
    id: "gen_lr10",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "In stroke play, you drop in the wrong relief area (you miscalculated the nearest point of relief) and play the ball. You realize the mistake before teeing off on the next hole. What is the penalty?",
    choices: [
      "General penalty (two strokes) for playing from a wrong place. Your score with that ball counts unless it was a serious breach.",
      "Disqualification",
      "One-stroke penalty; the score counts",
      "No penalty since you corrected it before the next hole",
    ],
    correct: 0,
    rule: "Rule 14.7a",
    explanation:
      "Under Rule 14.7a, playing from a wrong place in stroke play results in the general penalty (two strokes added). The score with the ball played from the wrong place counts. If the Committee determines it was a serious breach (significant advantage gained), you must correct it by playing from the right place or face disqualification.",
    tags: ["drop", "wrong place", "stroke play", "general penalty", "nearest point of relief"],
  },
  {
    id: "gen_lr11",
    category: "LIFTING_RETURNING",
    tier: "official",
    text: "You are required to place a ball after two drops rolled out of the relief area. You place it on the required spot, but the ball rolls about 3 inches downhill and comes to rest. What do you do?",
    choices: [
      "Try to place it on the same spot a second time. If it still won't stay, place it on the nearest spot where it will remain at rest, not nearer the hole.",
      "The ball is in play where it came to rest",
      "Drop again instead of placing",
      "Move to a different relief area entirely",
    ],
    correct: 0,
    rule: "Rule 14.2e",
    explanation:
      "Under Rule 14.2e, if a placed ball does not remain on the required spot, you must try placing it a second time. If it still doesn't stay, you find the nearest spot (not nearer the hole, not in a penalty area or bunker unless relief was taken there) where the ball will remain at rest and place it there.",
    tags: ["place", "relief area", "procedure", "slope", "re-drop"],
  },
  {
    id: "gen_lr12",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "You want to lift your ball to identify it in the rough. Must you tell anyone before lifting?",
    choices: [
      "Yes — you must first announce your intention to lift, mark the spot, and give your opponent (match play) or marker (stroke play) a chance to observe the process",
      "No — you can lift to identify at any time without telling anyone",
      "Only in match play, not in stroke play",
      "Only if a rules official is present",
    ],
    correct: 0,
    rule: "Rule 7.3",
    explanation:
      "Under Rule 7.3, before lifting a ball to identify it, you must announce your intention to another player or your marker and give them a chance to observe. You must mark the spot before lifting. Failure to follow this procedure results in a one-stroke penalty.",
    tags: ["mark ball", "identification", "lifting", "procedure"],
  },
  {
    id: "gen_lr13",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You drop your ball and it comes to rest in the relief area. You then realize you used the wrong reference point for your nearest point of relief, but haven't made a stroke yet. What should you do?",
    choices: [
      "Pick up the ball without penalty and re-drop at the correct spot — you may correct a relief error before making a stroke",
      "Play the ball — you're committed once you drop",
      "Take a one-stroke penalty and re-drop at the correct point",
      "Continue play — minor errors in determining the nearest point don't matter",
    ],
    correct: 0,
    rule: "Rule 14.5b",
    explanation:
      "Under Rule 14.5b, before making a stroke, a player may lift a ball that was dropped or placed to take relief and correct the error without penalty. Since no stroke has been made, you can pick up the ball and redo the relief procedure at the correct nearest point with no penalty.",
    tags: ["drop", "nearest point of relief", "correction", "re-drop"],
  },
  {
    id: "gen_lr14",
    category: "LIFTING_RETURNING",
    tier: "official",
    text: "After taking relief, you drop the ball. It hits the ground inside the relief area, bounces up and hits your golf bag lying on the ground outside the relief area, then ricochets back into the relief area and comes to rest. Is this a valid drop?",
    choices: [
      "Yes — the ball first hit the ground without touching you or your equipment, and it came to rest in the relief area, so the drop is valid",
      "No — the ball touched your equipment, so you must re-drop",
      "No — the ball left the relief area during its travel",
      "Yes, but only if the bag was not deliberately placed there",
    ],
    correct: 0,
    rule: "Rule 14.3b(2), Rule 14.3c",
    explanation:
      "Rule 14.3b(2) requires the ball not to touch the player or equipment before hitting the ground. Since the ball hit the ground first (inside the relief area) and then bounced to hit the bag, this requirement is met. Under Rule 14.3c, the ball is in play if it comes to rest in the relief area, which it did.",
    tags: ["drop", "knee height", "relief area", "equipment", "procedure"],
  },
  {
    id: "gen_lr15",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "In match play, your opponent lifts your ball from the fairway without your authorization and without any Rule allowing it. What is the ruling?",
    choices: [
      "Your opponent gets a one-stroke penalty. Your ball must be replaced on its original spot.",
      "No penalty — any player can lift any ball",
      "You get a one-stroke penalty because it's your ball",
      "Your opponent is disqualified from the hole",
    ],
    correct: 0,
    rule: "Rule 9.5b",
    explanation:
      "Under Rule 9.5b, if your opponent lifts or moves your ball at rest without authorization and without a Rule allowing it, the opponent gets one penalty stroke and the ball must be replaced on its original spot. In stroke play, another player is an outside influence, and there would be no penalty to anyone under Rule 9.6.",
    tags: ["lifting", "match play", "penalty", "unauthorized"],
  },
  {
    id: "gen_lr16",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You take free relief from an immovable obstruction. After completing the proper relief procedure, a different immovable obstruction now interferes with your stance at the new spot. Can you take relief again?",
    choices: [
      "Yes — you may take free relief from the new obstruction by going through the full relief procedure again",
      "No — you already used your free relief for this shot",
      "Yes, but only with a one-stroke penalty",
      "No — you must play from where your drop landed",
    ],
    correct: 0,
    rule: "Rule 16.1b",
    explanation:
      "There is no limit on the number of times you may take free relief from abnormal course conditions. If after properly completing relief from one obstruction, a different one interferes, you are entitled to a separate free relief from the new interference.",
    tags: ["immovable obstruction", "free relief", "relief area", "drop"],
  },
  {
    id: "gen_lr17",
    category: "LIFTING_RETURNING",
    tier: "official",
    text: "You mark your ball on the putting green. Another player's ball in motion strikes your ball marker and moves it several inches. What do you do?",
    choices: [
      "Replace the ball marker on its original spot (estimated if needed) — no penalty to anyone",
      "Place your ball where the marker now sits",
      "The other player gets a one-stroke penalty for moving your marker",
      "Ask the Committee to determine the correct spot",
    ],
    correct: 0,
    rule: "Rule 9.6",
    explanation:
      "Under Rule 9.6, if a ball-marker is moved by another ball in motion, the ball-marker must be replaced on its original spot (estimated if not known). There is no penalty to any player.",
    tags: ["mark ball", "ball marker", "putting green", "moved by another ball"],
  },
  {
    id: "gen_lr18",
    category: "LIFTING_RETURNING",
    tier: "official",
    text: "You are taking lateral relief from a red penalty area. You drop within two club-lengths of the reference point. The ball rolls and comes to rest 2.5 club-lengths from the reference point but not nearer the hole. Is this valid?",
    choices: [
      "No — the ball rolled outside the relief area (two club-lengths from the reference point). You must re-drop.",
      "Yes — the ball is not nearer the hole, which is the only requirement",
      "Yes — the ball can roll up to three club-lengths after a drop",
      "No — place the ball at the edge of the two-club-length zone",
    ],
    correct: 0,
    rule: "Rule 14.3c(2), Rule 17.1d(3)",
    explanation:
      "For lateral relief from a red penalty area, the relief area extends two club-lengths from the reference point (where the ball last crossed the edge), not nearer the hole. If the ball comes to rest beyond two club-lengths from that point, it is outside the relief area. You must re-drop, and if the second drop also rolls out, place where the second drop hit.",
    tags: ["drop", "lateral relief", "relief area", "re-drop", "penalty area"],
  },
  {
    id: "gen_lr19",
    category: "LIFTING_RETURNING",
    tier: "competitor",
    text: "You need to place a ball after two drops rolled out. You place it and remove your hand. The ball stays put for a moment, then topples over and rolls two feet away due to the slope. Is the ball in play at the new spot?",
    choices: [
      "No — the ball did not stay on the required spot. You must try placing it a second time. If it still won't stay, place it on the nearest spot where it will remain at rest (not nearer the hole).",
      "Yes — once you released the ball it is in play wherever it stops",
      "Yes — it stayed on the spot initially so it's in play",
      "No — drop again instead of placing",
    ],
    correct: 0,
    rule: "Rule 14.2e",
    explanation:
      "Under Rule 14.2e, a placed ball must come to rest on the spot where it is placed. If it does not stay on that spot, you try a second time. If it still won't remain, you place it on the nearest spot where it will stay at rest, not nearer the hole.",
    tags: ["place", "procedure", "slope", "relief area"],
  },
  {
    id: "gen_lr20",
    category: "LIFTING_RETURNING",
    tier: "weekend",
    text: "You lift your ball on the putting green to clean it and accidentally drop it on the concrete cart path beside the green, cracking it. Can you substitute a new ball?",
    choices: [
      "Yes — if a ball breaks or cracks during the play of a hole, you may substitute another ball, placing it on the spot where the original ball was lifted from",
      "No — you must continue with the damaged ball",
      "Yes, but with a one-stroke penalty for damaging the ball",
      "Only if a rules official confirms the damage",
    ],
    correct: 0,
    rule: "Rule 4.2c",
    explanation:
      "Under Rule 4.2c, if a ball in play becomes cut or cracked during the play of a hole, you may substitute another ball. Place the substituted ball on the spot where the original ball was at rest (in this case, where it was marked on the putting green). There is no penalty.",
    tags: ["substitution", "putting green", "damaged ball", "clean ball"],
  },

  // =============================================
  // FREE RELIEF (Rules 15-16) — 30 scenarios
  // =============================================

  // --- Rule 15: Loose Impediments and Movable Obstructions ---

  {
    id: "gen_fr1",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is in the rough and there is a small pebble directly behind it. You carefully remove the pebble, but your ball moves slightly. What happens?",
    choices: [
      "One-stroke penalty and you must replace the ball on its original spot",
      "No penalty — simply replace the ball",
      "No penalty — play the ball from its new position",
      "Two-stroke penalty for moving your ball",
    ],
    correct: 0,
    rule: "Rule 15.1b",
    explanation:
      "Under Rule 15.1b, if removing a loose impediment causes your ball to move in the general area (anywhere except the putting green), you get a one-stroke penalty and must replace the ball. On the putting green, there would be no penalty.",
    tags: ["loose impediment", "ball moved", "penalty", "rough"],
  },
  {
    id: "gen_fr2",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "A fallen leaf is touching your ball on the putting green. You brush it away and your ball rolls slightly. Is there a penalty?",
    choices: [
      "No penalty — on the putting green, there is no penalty if your ball moves while removing a loose impediment. Simply replace the ball.",
      "One-stroke penalty; replace the ball",
      "No penalty; play the ball from its new spot",
      "General penalty for moving your ball",
    ],
    correct: 0,
    rule: "Rule 15.1b, Exception",
    explanation:
      "Rule 15.1b provides an exception for the putting green: if your ball moves while you are removing a loose impediment on the putting green, there is no penalty. Replace the ball on its original spot.",
    tags: ["loose impediment", "putting green", "ball moved", "no penalty", "leaf"],
  },
  {
    id: "gen_fr3",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is in the fairway. A large dead branch from a nearby tree is lying across the ground and touching your ball. You want to remove it, but the ball will almost certainly move. What are your options?",
    choices: [
      "You may remove the branch (it's a loose impediment), but if the ball moves you get a one-stroke penalty and must replace it. Alternatively, play it as it lies.",
      "You may not remove any loose impediment if you know the ball will move",
      "Mark and lift the ball first, then remove the branch, then replace the ball with no penalty",
      "Declare an unplayable lie — that is your only option",
    ],
    correct: 0,
    rule: "Rule 15.1a, Rule 15.1b",
    explanation:
      "You are always allowed to remove loose impediments anywhere on the course (Rule 15.1a). However, in the general area, if the ball moves as a result, you get a one-stroke penalty and must replace the ball (Rule 15.1b). You cannot mark and lift your ball just to remove loose impediments in the general area.",
    tags: ["loose impediment", "ball moved", "branch", "fairway", "penalty"],
  },
  {
    id: "gen_fr4",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "An empty soda can is lying in the rough near your ball. You want to remove it. Is it a loose impediment or a movable obstruction?",
    choices: [
      "A movable obstruction — it is an artificial object, not a natural one. You may remove it without penalty.",
      "A loose impediment — all trash is considered natural debris",
      "Neither — you must play around it",
      "A loose impediment only if it's biodegradable",
    ],
    correct: 0,
    rule: "Definition of Movable Obstruction",
    explanation:
      "An obstruction is any artificial object. A soda can is artificial (man-made), not natural. Since it can be moved with reasonable effort, it is a movable obstruction. Under Rule 15.2a, you may remove it without penalty anywhere on the course. If the ball moves during removal, it must be replaced without penalty.",
    tags: ["movable obstruction", "no penalty", "rough", "artificial object"],
  },
  {
    id: "gen_fr5",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball comes to rest inside a movable obstruction — a large cardboard box that blew onto the course. How do you take relief?",
    choices: [
      "Lift the ball, remove the box, and drop within one club-length of the spot directly below where the ball was resting inside the box, not nearer the hole",
      "Remove the box and play the ball from wherever it rolls to",
      "Free drop anywhere within two club-lengths of the box",
      "Declare an unplayable lie with one-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 15.2a(2)",
    explanation:
      "Under Rule 15.2a(2), when a ball is in or on a movable obstruction, you may lift the ball, remove the obstruction, and drop (or place on the putting green) within one club-length of the spot directly below where the ball was resting on or in the obstruction, not nearer the hole. No penalty.",
    tags: ["movable obstruction", "drop", "relief area", "free relief"],
  },
  {
    id: "gen_fr6",
    category: "FREE_RELIEF",
    tier: "official",
    text: "Is a living worm on the putting green considered a loose impediment that you may remove before putting?",
    choices: [
      "Yes — worms, insects, and similar animals are loose impediments and may be removed without penalty",
      "No — living creatures are never loose impediments",
      "Yes, but only dead worms are loose impediments",
      "Only if it is on your line of putt",
    ],
    correct: 0,
    rule: "Definition of Loose Impediment",
    explanation:
      "The definition of loose impediment includes 'worms, insects, and similar animals that can be removed easily.' Living worms qualify as loose impediments. You may remove them without penalty anywhere on the course.",
    tags: ["loose impediment", "worm", "putting green", "natural object"],
  },
  {
    id: "gen_fr7",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is near a white out-of-bounds stake. The stake interferes with your backswing. Can you pull out the stake?",
    choices: [
      "No — boundary objects (OB stakes) are not obstructions and may not be moved, even if they interfere with your swing",
      "Yes — any stake on the course can be removed",
      "Yes — OB stakes are movable obstructions",
      "Only if the stake is loose in the ground",
    ],
    correct: 0,
    rule: "Definition of Obstruction, Rule 8.1a",
    explanation:
      "Boundary objects (OB stakes, fences, walls defining the course boundary) are not obstructions — they are specifically excluded from the definition. They may not be moved. Moving a boundary object to improve conditions for your stroke results in the general penalty.",
    tags: ["out of bounds", "boundary object", "no relief", "backswing"],
  },
  {
    id: "gen_fr8",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is in the general area near a red penalty area stake. The stake interferes with your swing. The stake can be pulled out easily. May you remove it?",
    choices: [
      "Yes — penalty area stakes are movable obstructions when they can be easily removed, and you may remove them without penalty",
      "No — penalty area stakes may never be moved",
      "Yes, but with a one-stroke penalty",
      "Only if the Committee has authorized removal of stakes",
    ],
    correct: 0,
    rule: "Rule 15.2a",
    explanation:
      "Penalty area stakes are obstructions. If a penalty area stake can be moved with reasonable effort without unreasonable delay and without damaging the course, it is a movable obstruction and may be removed under Rule 15.2a without penalty. However, the Committee may adopt a Local Rule making them immovable.",
    tags: ["movable obstruction", "penalty area", "red stakes", "free relief"],
  },
  {
    id: "gen_fr9",
    category: "FREE_RELIEF",
    tier: "official",
    text: "Your ball is in the rough. A large rock is partially embedded in the ground next to your ball. You could pull it out with significant effort. Is it a loose impediment?",
    choices: [
      "No — if the rock is solidly embedded (not loose), it is not a loose impediment. A loose impediment must not be fixed, growing, or solidly embedded.",
      "Yes — all rocks are loose impediments",
      "Yes — any rock that can be moved with effort is a loose impediment",
      "It depends on whether the rock is natural or placed",
    ],
    correct: 0,
    rule: "Definition of Loose Impediment",
    explanation:
      "A loose impediment must be a natural object that is not fixed or growing, not solidly embedded, and not adhering to the ball. If a rock is solidly embedded in the ground, it does not qualify as a loose impediment. Whether it is 'solidly embedded' is a judgment call based on the specific situation.",
    tags: ["loose impediment", "rock", "embedded", "rough", "natural object"],
  },
  {
    id: "gen_fr10",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is in the fairway resting against a movable distance marker (a small post that can be easily pulled out). The marker interferes with your swing. Can you remove it?",
    choices: [
      "Yes — if the distance marker can be moved with reasonable effort, it is a movable obstruction and may be removed without penalty",
      "No — distance markers are part of the course and cannot be moved",
      "Yes, but only with a one-stroke penalty",
      "Only if another player confirms it's movable",
    ],
    correct: 0,
    rule: "Rule 15.2a",
    explanation:
      "If a distance marker can be moved with reasonable effort without unreasonable delay and without damaging the course, it is a movable obstruction. Under Rule 15.2a, you may remove any movable obstruction without penalty. If your ball moves during removal, replace it without penalty.",
    tags: ["movable obstruction", "distance marker", "free relief", "fairway"],
  },

  // --- Rule 16: Abnormal Course Conditions ---

  {
    id: "gen_fr11",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is on a paved cart path. You want to take free relief. How do you determine the nearest point of complete relief?",
    choices: [
      "Find the nearest spot off the path where the path no longer interferes with your ball, stance, or swing — using the club you would normally play, not nearer the hole",
      "Pick the most advantageous point on either side of the path",
      "Measure one club-length from the edge of the path",
      "Drop anywhere within two club-lengths of where the ball sits on the path",
    ],
    correct: 0,
    rule: "Rule 16.1b, Definition of Nearest Point of Complete Relief",
    explanation:
      "The nearest point of complete relief is the estimated point where the condition (cart path) no longer interferes with your ball lie, stance, and swing for the stroke you would make from that spot. You simulate your stance and swing with the club you would use. This point may be in the rough even if the other side of the path has a better lie.",
    tags: ["cart path", "nearest point of relief", "immovable obstruction", "free relief"],
  },
  {
    id: "gen_fr12",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is in the general area. A sprinkler head interferes with your stance for a normal shot, but you could avoid the sprinkler by playing an unusual shot (e.g., playing left-handed when you're right-handed). Must you play the unusual shot to avoid the obstruction?",
    choices: [
      "No — you determine interference based on the stroke you would reasonably make if the obstruction were not there. If a normal shot would be interfered with, you get relief.",
      "Yes — you must try to avoid the obstruction before claiming relief",
      "No — you always get relief regardless of what shot you would play",
      "Yes — the Rules require you to minimize obstruction impact",
    ],
    correct: 0,
    rule: "Rule 16.1a",
    explanation:
      "Interference is judged based on the stroke the player would reasonably make if the abnormal course condition were not there. You don't have to manufacture an unusual stroke to avoid the condition. If your normal, reasonable stroke is interfered with, you are entitled to free relief.",
    tags: ["sprinkler head", "immovable obstruction", "stance", "reasonable stroke", "free relief"],
  },
  {
    id: "gen_fr13",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is sitting in temporary water on the fairway. You take free relief. The nearest point of complete relief is in the rough. Must you drop in the rough?",
    choices: [
      "Yes — you must use the nearest point of complete relief even if it puts you in a worse area like the rough",
      "No — you may choose any dry spot on the fairway",
      "No — the relief area must be in the same cut of grass",
      "Yes, but you may request a second opinion from a rules official",
    ],
    correct: 0,
    rule: "Rule 16.1b",
    explanation:
      "The nearest point of complete relief is determined by the specific location of the ball and the condition. If the nearest point where the temporary water no longer interferes is in the rough, that is where you must take relief. You don't get to choose a more favorable spot. You always have the option to play from the temporary water instead.",
    tags: ["temporary water", "nearest point of relief", "rough", "fairway"],
  },
  {
    id: "gen_fr14",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is in a bunker sitting in temporary water. There is no place in the bunker that provides complete relief from the water. What are your options?",
    choices: [
      "Free: take maximum available relief in the bunker (the driest spot). Or for one penalty stroke: drop outside the bunker on the back-on-the-line.",
      "Free drop outside the bunker at the nearest point of complete relief",
      "Must play it as it lies in the water",
      "Two-stroke penalty to drop outside the bunker",
    ],
    correct: 0,
    rule: "Rule 16.1c",
    explanation:
      "Under Rule 16.1c, when complete relief is not available in a bunker, you may take free relief at the point of maximum available relief in the bunker (the spot that gives the most relief). Alternatively, for one penalty stroke, you may take back-on-the-line relief outside the bunker, keeping the point where the ball lay between you and the hole.",
    tags: ["bunker", "temporary water", "free relief", "back-on-the-line"],
  },
  {
    id: "gen_fr15",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "A gopher hole is next to your ball in the fairway and your foot would be in the hole during your swing. Do you get free relief?",
    choices: [
      "Yes — a hole made by a burrowing animal is an abnormal course condition, and you get free relief when it interferes with your stance, swing, or ball lie",
      "No — animal holes are natural features of the course",
      "Yes, but only if the animal that made it is still present",
      "Only if the Committee has marked it with blue stakes",
    ],
    correct: 0,
    rule: "Rule 16.1a, Definition of Animal Hole",
    explanation:
      "An 'animal hole' under the Rules includes any hole dug by an animal (except by insects or worms), along with the loose material and any raised trail leading to it. When it interferes with your stance, swing, or ball lie, you are entitled to free relief under Rule 16.1b.",
    tags: ["animal hole", "free relief", "stance", "fairway", "abnormal course condition"],
  },
  {
    id: "gen_fr16",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is embedded in the face of a bunker — but in the grass lip above the sand, not in the sand itself. Are you entitled to embedded ball relief?",
    choices: [
      "Yes — the grass lip of a bunker is part of the general area, not the bunker, so embedded ball relief under Rule 16.3 applies",
      "No — the ball is in a bunker so no embedded ball relief",
      "Yes, but only with a one-stroke penalty",
      "No — embedded ball relief only applies in fairway-cut areas",
    ],
    correct: 0,
    rule: "Rule 16.3, Definition of Bunker",
    explanation:
      "The bunker is defined as the prepared area of sand plus any grass, soil, or other material within the bunker edge that is at the same level as the sand or below. The grass lip or face rising above the bunker is part of the general area. Since embedded ball relief applies in the general area, you get free relief.",
    tags: ["embedded ball", "bunker", "general area", "grass lip", "free relief"],
  },
  {
    id: "gen_fr17",
    category: "FREE_RELIEF",
    tier: "official",
    text: "The Committee has adopted a Local Rule restricting embedded ball relief to 'closely mown areas' (fairway height or less). Your ball is embedded in the rough. What are your options?",
    choices: [
      "No free relief — you must play it as it lies or declare the ball unplayable with a one-stroke penalty",
      "You still get free relief regardless of the Local Rule",
      "Free relief, but you must drop in the rough",
      "You may lift and clean the ball but must replace it in the same lie",
    ],
    correct: 0,
    rule: "Rule 16.3, Model Local Rule F-2",
    explanation:
      "When the Committee has adopted Model Local Rule F-2, free embedded ball relief is restricted to areas cut to fairway height or less. A ball embedded in the rough would not qualify for free relief. Your options are to play it as it lies or take unplayable ball relief with a one-stroke penalty under Rule 19.",
    tags: ["embedded ball", "rough", "local rule", "unplayable"],
  },
  {
    id: "gen_fr18",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball embeds in its own pitch mark in the rough (general area). Are you entitled to embedded ball relief?",
    choices: [
      "Yes — under the default Rules, embedded ball relief applies anywhere in the general area, including the rough",
      "No — embedded ball relief is only for the fairway",
      "Yes, but with a one-stroke penalty",
      "Only if the course has a Local Rule allowing it",
    ],
    correct: 0,
    rule: "Rule 16.3a",
    explanation:
      "Under the default Rule 16.3, you get free relief for a ball embedded in the general area — which includes both the fairway and the rough. The ball must be in its own pitch mark. Note that the Committee may adopt a Local Rule restricting this relief to fairway-height areas only.",
    tags: ["embedded ball", "rough", "general area", "free relief", "pitch mark"],
  },
  {
    id: "gen_fr19",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is on a drainage grate (immovable obstruction) in the rough. The grate only interferes with your ball's lie — your stance and swing are not affected. Do you get free relief?",
    choices: [
      "Yes — interference exists when the obstruction affects the lie of your ball, even if your stance and swing are unaffected",
      "No — relief requires interference with your stance or swing, not just the ball's lie",
      "Yes, but only if the ball is touching the grate",
      "No — drainage grates are part of the course",
    ],
    correct: 0,
    rule: "Rule 16.1a",
    explanation:
      "Under Rule 16.1a, interference from an abnormal course condition exists when it interferes with any one of three things: the lie of the ball, the area of intended stance, or the area of intended swing. The ball sitting on a grate constitutes interference with its lie, and you are entitled to free relief.",
    tags: ["immovable obstruction", "free relief", "ball lie", "drainage"],
  },
  {
    id: "gen_fr20",
    category: "FREE_RELIEF",
    tier: "official",
    text: "Your ball is in the general area. The nearest point of complete relief from an immovable obstruction would be on a putting green (not the green you're playing to). Can you drop there?",
    choices: [
      "No — when your ball is in the general area, the nearest point of complete relief must also be in the general area, not on any putting green or in a penalty area",
      "Yes — any putting green is a valid relief point",
      "Yes — only the green of the hole you're playing is excluded",
      "No — you lose the right to free relief entirely",
    ],
    correct: 0,
    rule: "Rule 16.1b",
    explanation:
      "Under Rule 16.1b, when the ball is in the general area, the nearest point of complete relief must be in the general area. It cannot be on any putting green or in a penalty area. You must find the nearest point that satisfies these requirements, even if it means going past the obstruction.",
    tags: ["immovable obstruction", "nearest point of relief", "putting green", "general area"],
  },
  {
    id: "gen_fr21",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "After heavy rain, there is temporary water on the putting green directly on your line of putt. Your ball is on the green but not in the water. Do you get relief?",
    choices: [
      "Yes — on the putting green, you get free relief if temporary water intervenes on your line of putt, even if the ball itself is not in the water",
      "No — relief is only available if the ball is sitting in the water",
      "Yes, but only by moving to a different part of the green",
      "No — you must putt through the water",
    ],
    correct: 0,
    rule: "Rule 16.1d",
    explanation:
      "On the putting green, the definition of interference from abnormal course conditions is broader. Under Rule 16.1d, interference exists when temporary water on the green intervenes on your line of putt between your ball and the hole, even if the ball itself is not in the water. You get free relief by placing the ball at the nearest point of complete relief (on the green or in the general area).",
    tags: ["putting green", "temporary water", "line of putt", "free relief"],
  },
  {
    id: "gen_fr22",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is in a red penalty area and sitting in temporary water. Can you take free relief from the temporary water?",
    choices: [
      "No — there is no free relief from abnormal course conditions when your ball is in a penalty area. Your options are to play it as it lies or take penalty area relief.",
      "Yes — temporary water always gives free relief",
      "Yes — free relief from temporary water applies everywhere",
      "No free relief, but you get a one-stroke penalty drop within the penalty area",
    ],
    correct: 0,
    rule: "Rule 16.1a",
    explanation:
      "Under Rule 16.1a, free relief from abnormal course conditions (including temporary water) is NOT available when your ball is in a penalty area. Your options are to play the ball as it lies in the penalty area or take penalty area relief under Rule 17 with a one-stroke penalty.",
    tags: ["penalty area", "temporary water", "no relief"],
  },
  {
    id: "gen_fr23",
    category: "FREE_RELIEF",
    tier: "official",
    text: "Your ball is in the general area. An ant mound interferes with your stance. An ant mound is made by insects. Do you get free relief?",
    choices: [
      "No — the definition of 'animal hole' specifically excludes holes made by insects (such as ants). An ant mound is not an abnormal course condition.",
      "Yes — any animal-made structure is an animal hole",
      "Yes — ant mounds are considered ground under repair",
      "No, but you may flatten the mound as a loose impediment",
    ],
    correct: 0,
    rule: "Definition of Animal Hole",
    explanation:
      "The definition of 'animal hole' excludes holes dug by insects or worms. Since ants are insects, an ant mound does not qualify as an animal hole and is not an abnormal course condition. You are not entitled to free relief. You may remove loose material from the mound as a loose impediment if it is not solidly embedded.",
    tags: ["animal hole", "insect", "no relief", "stance", "loose impediment"],
  },
  {
    id: "gen_fr24",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is behind a tree. A sprinkler head (immovable obstruction) is also between your ball and the green, but it doesn't affect your lie, stance, or swing — the tree prevents you from hitting toward the green anyway. Can you still claim free relief from the sprinkler head?",
    choices: [
      "No — you cannot take relief from an immovable obstruction if your only interference is on the line of play, and the obstruction doesn't affect your lie, stance, or swing for the shot you would reasonably play",
      "Yes — the sprinkler head is an obstruction so you always get relief",
      "Yes — relief is based on any possible interference",
      "No — you must hit over or around the tree first",
    ],
    correct: 0,
    rule: "Rule 16.1a",
    explanation:
      "Relief from immovable obstructions requires interference with your lie, stance, or swing for the stroke you would reasonably make. If the tree means your reasonable stroke would be sideways or backwards (not toward the green), and the sprinkler doesn't interfere with that reasonable stroke's lie, stance, or swing, there is no interference and no relief.",
    tags: ["sprinkler head", "immovable obstruction", "tree", "reasonable stroke", "no relief"],
  },
  {
    id: "gen_fr25",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "You take free relief from a cart path. The nearest point of complete relief is in deep rough. Your playing partner says you should take relief on the other side of the path where the fairway is. Can you?",
    choices: [
      "No — you must use the actual nearest point of complete relief, even if the other side of the path offers a better lie",
      "Yes — you may choose either side of the path",
      "Yes — you can take the most favorable relief available",
      "No, but you can play from the path instead and avoid the rough",
    ],
    correct: 0,
    rule: "Rule 16.1b, Definition of Nearest Point of Complete Relief",
    explanation:
      "The 'nearest point of complete relief' is a fixed reference point — the closest spot where the obstruction no longer interferes with your lie, stance, and swing, not nearer the hole. You cannot choose between multiple points. However, you always have the option to play the ball as it lies on the path.",
    tags: ["cart path", "nearest point of relief", "rough", "free relief"],
  },
  {
    id: "gen_fr26",
    category: "FREE_RELIEF",
    tier: "official",
    text: "Your ball is in the general area and an immovable obstruction interferes with your stance. The nearest point of complete relief would put you in a penalty area. What do you do?",
    choices: [
      "Find the nearest point of complete relief that is in the general area — you cannot drop in a penalty area when taking relief from the general area",
      "Drop in the penalty area since it's the nearest point",
      "You cannot take relief — play it as it lies",
      "Take a one-stroke penalty and drop outside both the obstruction and penalty area",
    ],
    correct: 0,
    rule: "Rule 16.1b",
    explanation:
      "Under Rule 16.1b, when the ball is in the general area, the relief area must also be in the general area — it cannot be in a penalty area, a bunker (unless the ball was in one), or on a putting green. Find the nearest point of complete relief that meets these restrictions.",
    tags: ["immovable obstruction", "penalty area", "nearest point of relief", "general area"],
  },
  {
    id: "gen_fr27",
    category: "FREE_RELIEF",
    tier: "weekend",
    text: "Your ball is on a cart path. You don't want to take relief because the path gives you a clear shot to the green and the rough on both sides is thick. Can you play from the path?",
    choices: [
      "Yes — relief from immovable obstructions is always optional in the general area. You may play the ball as it lies on the path.",
      "No — you must take relief from all paved surfaces",
      "Yes, but only if all other players agree",
      "No — playing from a cart path results in a two-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 16.1",
    explanation:
      "Free relief from abnormal course conditions (including immovable obstructions like cart paths) is always optional in the general area. You may choose to play the ball as it lies, even from a cart path, if you prefer that to the relief available.",
    tags: ["cart path", "immovable obstruction", "optional relief", "free relief"],
  },
  {
    id: "gen_fr28",
    category: "FREE_RELIEF",
    tier: "competitor",
    text: "Your ball is in an area marked with white lines as 'Ground Under Repair.' You have a good lie and want to play it from there. Must you take relief?",
    choices: [
      "No — relief from GUR is optional unless the Committee has designated it as a no-play zone",
      "Yes — you must always take relief from GUR",
      "No, but only in match play — you must take relief in stroke play",
      "Yes — white lines indicate mandatory relief",
    ],
    correct: 0,
    rule: "Rule 16.1",
    explanation:
      "Relief from ground under repair (GUR) is optional under Rule 16.1 — you may play the ball as it lies if you choose. The only exception is when the Committee designates the GUR as a 'no-play zone,' which requires mandatory relief. Check for signs or information from the Committee about no-play zones.",
    tags: ["GUR", "ground under repair", "optional relief", "no play zone"],
  },
  {
    id: "gen_fr29",
    category: "FREE_RELIEF",
    tier: "official",
    text: "Temporary water is not visible at your ball in the fairway. However, when you take your normal stance, water seeps up around the soles of your shoes. Does this count as temporary water?",
    choices: [
      "Yes — temporary water exists if it is visible before, during, or after you take your normal stance. Water seeping up under normal stance pressure qualifies.",
      "No — temporary water must be visible without taking your stance",
      "Yes, but only if the water is at least half an inch deep",
      "No — subsurface water is not temporary water",
    ],
    correct: 0,
    rule: "Definition of Temporary Water",
    explanation:
      "The definition of temporary water states it is a temporary accumulation of water that is visible on the surface of the ground before, during, or after the player takes a stance. Water that becomes visible when you take your normal stance (without excessive pressing) qualifies as temporary water, entitling you to free relief.",
    tags: ["temporary water", "stance", "fairway", "free relief"],
  },
  {
    id: "gen_fr30",
    category: "FREE_RELIEF",
    tier: "official",
    text: "Your ball is on the putting green and temporary water sits between your ball and the hole. The nearest point of complete relief on the green would put you farther from the hole, but there is a closer point of complete relief on the fringe. Where do you take relief?",
    choices: [
      "At the nearest point of complete relief, which may be on the putting green or in the general area (fringe) — whichever is closer",
      "Only on the putting green — you must stay on the green",
      "Only on the fringe — you must leave the green",
      "At the point that gives you the shortest remaining putt",
    ],
    correct: 0,
    rule: "Rule 16.1d",
    explanation:
      "Under Rule 16.1d, when your ball is on the putting green and you take free relief from an abnormal course condition, the nearest point of complete relief may be either on the putting green or in the general area (such as the fringe). You use whichever is the actual nearest point, and you place (not drop) the ball there.",
    tags: ["putting green", "temporary water", "fringe", "nearest point of relief", "free relief"],
  },
];
