import { Scenario } from "@/types";

export const SCENARIOS_BATCH_2: Scenario[] = [
  // =============================================
  // RULE 7: SEARCHING FOR AND FINDING BALL
  // =============================================

  {
    id: "gen_b1",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "While searching for your ball in tall grass, you accidentally step on it and push it into the ground. What is the ruling?",
    choices: [
      "No penalty; replace the ball on its original spot (estimated if necessary)",
      "One-stroke penalty; replace the ball",
      "No penalty; play the ball as it lies in the ground",
      "One-stroke penalty; play the ball as it lies",
    ],
    correct: 0,
    rule: "Rule 7.4",
    explanation:
      "Under Rule 7.4, if you accidentally move your ball while searching for it, there is no penalty. You must replace the ball on its original estimated spot, including recreating the original lie if the ball was pushed into the ground.",
    tags: ["searching", "accidentally moved", "ball at rest", "replace ball"],
  },
  {
    id: "gen_b2",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You are searching for your ball in a bush. You push aside some branches to see better and your ball moves. What happens?",
    choices: [
      "No penalty; replace the ball",
      "One-stroke penalty because you moved vegetation that caused the ball to move",
      "No penalty; play from the new spot",
      "Two-stroke penalty for improving your lie",
    ],
    correct: 0,
    rule: "Rule 7.4",
    explanation:
      "Rule 7.4 protects you during a search: if your ball is accidentally moved while searching, there is no penalty regardless of how it happened (stepping on it, moving vegetation, etc.). You must replace the ball on its original spot.",
    tags: ["searching", "accidentally moved", "ball at rest", "rough"],
  },
  {
    id: "gen_b3",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You find a ball in the rough and want to check if it's yours. What is the proper procedure?",
    choices: [
      "Announce your intent, mark the spot, lift the ball to identify it, then replace it",
      "Pick it up and look at the number — no need to mark",
      "Rotate the ball in place to see the marking without lifting",
      "You cannot lift a ball for identification unless it is on the putting green",
    ],
    correct: 0,
    rule: "Rule 7.3",
    explanation:
      "Under Rule 7.3, if your ball might be yours but you cannot identify it as it lies, you may lift it to identify it. You must first mark the spot, then lift and identify. You must not clean the ball more than needed for identification.",
    tags: ["searching", "identification", "ball at rest", "rough"],
  },
  {
    id: "gen_b4",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "You lift a ball in the rough to identify it but clean it thoroughly before checking. The ball turns out to be yours. Is there a penalty?",
    choices: [
      "One-stroke penalty for cleaning the ball more than needed for identification",
      "No penalty since it turned out to be your ball",
      "Two-stroke penalty for improperly lifting",
      "No penalty; you can clean a lifted ball any time",
    ],
    correct: 0,
    rule: "Rule 7.3",
    explanation:
      "Under Rule 7.3, when lifting to identify, you must not clean the ball more than needed to identify it. Over-cleaning results in a one-stroke penalty. A quick wipe of a small area to see a marking is fine, but a thorough cleaning is not.",
    tags: ["searching", "identification", "ball at rest", "penalty"],
  },
  {
    id: "gen_b5",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You find your ball buried under leaves in the rough. You moved several leaves during your search, improving your lie. What should you do?",
    choices: [
      "No penalty for moving leaves during the search, but you must recreate the original lie before playing",
      "One-stroke penalty for improving your lie",
      "Play it as it lies; you cannot put leaves back",
      "Free relief since the ball was buried under loose impediments",
    ],
    correct: 0,
    rule: "Rule 7.4",
    explanation:
      "Under Rule 7.4, there is no penalty for accidentally moving loose impediments during a search. However, if the original lie was altered, you must recreate it (e.g., re-cover the ball with leaves) before playing your next stroke.",
    tags: ["searching", "improving lie", "loose impediment", "rough"],
  },
  {
    id: "gen_b6",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Your caddie kicks over a sand mound while searching for your ball in a waste area, and the ball is found beneath the sand. Must the lie be restored?",
    choices: [
      "Yes; the original lie must be recreated, including re-covering the ball with sand if necessary",
      "No; the ball was found so play it as it now lies",
      "One-stroke penalty on the caddie; play as it lies",
      "Free drop within one club-length since the lie was altered",
    ],
    correct: 0,
    rule: "Rule 7.4",
    explanation:
      "Rule 7.4 allows searching without penalty, but requires restoring the original lie if it was altered. If the ball was buried under sand, it must be re-covered, leaving only a small part visible so you can find it again.",
    tags: ["searching", "caddie", "ball at rest", "general area"],
  },
  {
    id: "gen_b7",
    category: "PLAYING_BALL",
    tier: "official",
    text: "While searching for your ball, a spectator finds it and picks it up, then puts it back in approximately the same spot. What is the ruling?",
    choices: [
      "No penalty; replace the ball on its estimated original spot",
      "One-stroke penalty on you; play from where the spectator placed it",
      "The ball is considered lost because an outside influence moved it",
      "Two-stroke penalty; you must replay from the previous spot",
    ],
    correct: 0,
    rule: "Rule 9.6",
    explanation:
      "Under Rule 9.6, when an outside influence (such as a spectator) lifts or moves your ball at rest, there is no penalty. The ball must be replaced on its original spot (estimated if not known exactly).",
    tags: ["searching", "outside influence", "ball at rest", "spectator"],
  },
  {
    id: "gen_b8",
    category: "PLAYING_BALL",
    tier: "official",
    text: "You are searching for your ball and use your club to probe thick grass, moving your ball. You did not see the ball move and cannot determine its original spot. What happens?",
    choices: [
      "No penalty; estimate the original spot and replace the ball there",
      "One-stroke penalty; play from where you find it",
      "The ball is lost since you cannot determine its original position",
      "Drop within one club-length of where you find it, no penalty",
    ],
    correct: 0,
    rule: "Rule 7.4, Rule 14.2c",
    explanation:
      "Rule 7.4 provides no penalty for accidentally moving your ball during a search. Under Rule 14.2c, if the exact original spot is not known, you must estimate it. Place the ball on that estimated spot.",
    tags: ["searching", "accidentally moved", "ball at rest", "estimate"],
  },
  {
    id: "gen_b9",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You hit your tee shot into the trees. Your caddie reaches the area and starts looking. You arrive 90 seconds later. How much search time remains?",
    choices: [
      "90 seconds — the clock started when your caddie began searching",
      "3 minutes — the clock starts when you personally arrive",
      "2 minutes — the clock starts when the previous group clears",
      "No time limit as long as you don't delay play unreasonably",
    ],
    correct: 0,
    rule: "Rule 18.2a(1)",
    explanation:
      "The 3-minute search time begins when you or your caddie (whichever arrives first) begin to search in the area where the ball is likely to be. Since your caddie started searching 90 seconds ago, you have 90 seconds remaining.",
    tags: ["searching", "caddie", "lost ball"],
  },
  {
    id: "gen_b10",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Your 3-minute search time expires and you head back to play under stroke and distance. While walking back, your original ball is found. What is the status of the original ball?",
    choices: [
      "The original ball is lost — the 3-minute search time has expired and it cannot be put back into play",
      "You may still play the original since you haven't hit another ball yet",
      "You must play whichever ball is in the better position",
      "The original is only lost if you have already dropped another ball",
    ],
    correct: 0,
    rule: "Rule 18.2a(1)",
    explanation:
      "Under Rule 18.2a(1), a ball is lost if it is not found within 3 minutes after you or your caddie begin searching. Once the 3 minutes expire, the ball is lost — finding it afterward does not change its status, even if you haven't played another ball yet.",
    tags: ["searching", "lost ball", "provisional ball"],
  },

  // =============================================
  // RULE 8: COURSE PLAYED AS FOUND
  // =============================================

  {
    id: "gen_b11",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is behind a young sapling. You bend the sapling out of your backswing path before making your stroke. Is this allowed?",
    choices: [
      "No — bending a growing plant to improve your area of intended swing is a penalty",
      "Yes — you may move any natural object that interferes with your swing",
      "Yes — as long as you don't break the sapling",
      "No penalty if the sapling returns to its original position",
    ],
    correct: 0,
    rule: "Rule 8.1a(1)",
    explanation:
      "Under Rule 8.1a, you must not improve the conditions affecting your stroke by moving, bending, or breaking anything growing or attached. Bending a sapling to clear your backswing is improving your area of intended swing and results in the general penalty.",
    tags: ["improving conditions", "backstroke", "play it as it lies", "general area"],
  },
  {
    id: "gen_b12",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is in the rough. Before your stroke, you press down the grass behind the ball with your foot, creating a better lie. What is the ruling?",
    choices: [
      "General penalty (two strokes / loss of hole) for improving your lie",
      "No penalty — you are allowed to take a fair stance",
      "One-stroke penalty only",
      "No penalty as long as you don't touch the ball",
    ],
    correct: 0,
    rule: "Rule 8.1a",
    explanation:
      "Under Rule 8.1a, you must not improve the conditions affecting your stroke. Deliberately pressing down grass behind your ball improves your lie, resulting in the general penalty (two strokes in stroke play, loss of hole in match play).",
    tags: ["improving lie", "rough", "play it as it lies", "general area"],
  },
  {
    id: "gen_b13",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is at the base of a tree. You break off a dead branch that is attached to the tree to make room for your backswing. What is the penalty?",
    choices: [
      "General penalty — you cannot break anything attached to the tree to improve your swing area",
      "No penalty — dead branches are loose impediments",
      "One-stroke penalty only",
      "No penalty since the branch was dead, not living",
    ],
    correct: 0,
    rule: "Rule 8.1a(1)",
    explanation:
      "Under Rule 8.1a, you must not improve conditions by moving, bending, or breaking anything growing or attached — even dead branches still attached to a tree are 'attached' and cannot be broken off. Only a detached branch (already on the ground) is a loose impediment that may be moved.",
    tags: ["improving conditions", "backstroke", "play it as it lies", "general area"],
  },
  {
    id: "gen_b14",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Your ball is on a slope in the rough. You take your stance and your feet slip, creating footprints that flatten the grass around your ball. Is there a penalty?",
    choices: [
      "No penalty — you are entitled to fairly take your stance, even if it alters conditions",
      "General penalty for improving your lie",
      "No penalty only if the footprints are unavoidable",
      "One-stroke penalty for altering the ground",
    ],
    correct: 0,
    rule: "Rule 8.1b(5)",
    explanation:
      "Under Rule 8.1b, you may fairly take a stance for your stroke, including firmly planting your feet. If doing so alters the conditions (like flattening some grass), there is no penalty because fairly taking a stance is a permitted action.",
    tags: ["improving lie", "play it as it lies", "fair stance", "rough"],
  },
  {
    id: "gen_b15",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is in a divot in the fairway. You press down the turf around the divot to create a more level surface for your shot. What happens?",
    choices: [
      "General penalty for improving the conditions affecting your stroke",
      "No penalty — divots are abnormal course conditions",
      "No penalty if you are just replacing the divot turf",
      "One-stroke penalty but you may proceed",
    ],
    correct: 0,
    rule: "Rule 8.1a",
    explanation:
      "Pressing down turf around your ball to create a better surface is improving the conditions affecting your stroke under Rule 8.1a. This results in the general penalty. A divot hole is not an abnormal course condition — you must play it as it lies.",
    tags: ["improving lie", "divot", "fairway", "play it as it lies"],
  },
  {
    id: "gen_b16",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "You lay your golf bag down behind your ball to block the wind while you prepare to hit your shot. Is this allowed?",
    choices: [
      "No — placing an object to protect against wind is not allowed and results in the general penalty",
      "Yes — you can use your equipment however you like",
      "Yes — protecting against the elements is always permitted",
      "No penalty if you remove the bag before making the stroke",
    ],
    correct: 0,
    rule: "Rule 10.2b(5)",
    explanation:
      "Under Rule 10.2b(5), a player must not deliberately position an object to protect against the elements (wind, sun, rain). Using your golf bag as a windbreak results in the general penalty.",
    tags: ["improving conditions", "equipment", "wind"],
  },
  {
    id: "gen_b17",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Before your stroke, you take several practice swings in the rough near your ball, which flatten some grass in your intended line of play. What is the ruling?",
    choices: [
      "General penalty — your practice swings improved your line of play by flattening the grass",
      "No penalty — practice swings are always allowed anywhere",
      "No penalty as long as you didn't touch your ball",
      "One-stroke penalty for each practice swing",
    ],
    correct: 0,
    rule: "Rule 8.1a(2)",
    explanation:
      "Under Rule 8.1a, you must not improve your line of play by any action, including flattening grass with practice swings. While practice swings are generally allowed, they must not improve conditions affecting your stroke, including your intended line of play.",
    tags: ["improving line of play", "practice swing", "rough", "play it as it lies"],
  },
  {
    id: "gen_b18",
    category: "PLAYING_BALL",
    tier: "official",
    text: "Your ball lies in a bush. On your backswing, you break a small twig in the bush. This happens as part of your actual stroke (not a practice swing). Is there a penalty?",
    choices: [
      "No penalty — breaking something during your backswing for a stroke is not a breach of Rule 8.1a",
      "General penalty for moving something attached during the stroke",
      "One-stroke penalty for improving conditions",
      "No penalty only if the twig was dead",
    ],
    correct: 0,
    rule: "Rule 8.1b(7)",
    explanation:
      "Under Rule 8.1b(7), there is no penalty if you improve conditions by actions taken in the area of your backswing for your stroke, as long as you then make that stroke. The protection applies to the actual stroke, not a practice swing.",
    tags: ["backstroke", "improving conditions", "play it as it lies", "general area"],
  },
  {
    id: "gen_b19",
    category: "PLAYING_BALL",
    tier: "official",
    text: "You take your backswing, breaking a twig in a bush behind you. You then stop and decide not to hit the shot. Is there a penalty?",
    choices: [
      "Yes — the general penalty applies because you did not complete the stroke",
      "No penalty since it happened on a backswing",
      "No penalty — you can stop at any time without consequence",
      "One-stroke penalty for breaking vegetation",
    ],
    correct: 0,
    rule: "Rule 8.1b(7)",
    explanation:
      "The exception in Rule 8.1b(7) only protects actions taken in the backswing if you then go on to make the stroke. If you stop your swing and do not complete the stroke, the improvement to conditions is not protected, and the general penalty applies.",
    tags: ["backstroke", "improving conditions", "play it as it lies"],
  },
  {
    id: "gen_b20",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is on a muddy lie in the fairway. Can you place a towel on the ground next to the ball to get a clean stance?",
    choices: [
      "No — placing objects to build a stance is not allowed and results in the general penalty",
      "Yes — you can use any equipment to help your stance",
      "Yes, but only a towel, not a club",
      "Only if the Committee has authorized it due to wet conditions",
    ],
    correct: 0,
    rule: "Rule 8.1a(3)",
    explanation:
      "Under Rule 8.1a, you must not improve the conditions affecting your stroke by creating or eliminating areas of the ground. Building a stance by placing objects on the ground is specifically prohibited. You must take your stance on the existing ground conditions.",
    tags: ["improving conditions", "fairway", "play it as it lies", "equipment"],
  },
  {
    id: "gen_b21",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "After hitting your shot, you replace the divot and tamp it down. Your ball ends up in a position where you must chip back over the same area. Have you breached a rule?",
    choices: [
      "Yes — replacing the divot improved the conditions affecting your next stroke, resulting in the general penalty",
      "No — replacing divots is good etiquette and always allowed",
      "No penalty as long as you didn't know your ball would end up there",
      "Yes, but only a one-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 8.1a",
    explanation:
      "Under Rule 8.1a, you must not improve conditions affecting your stroke. If replacing a divot happens to improve your line of play for your next stroke, it is a breach — even if done with good intentions. The general penalty applies.",
    tags: ["improving line of play", "divot", "fairway", "play it as it lies"],
  },
  {
    id: "gen_b22",
    category: "PLAYING_BALL",
    tier: "official",
    text: "A greenkeeper drives a course maintenance vehicle across the fairway, leaving tracks that are now directly on your line of play. Are you entitled to any relief?",
    choices: [
      "No specific relief under Rule 8, but the tracks may qualify as ground under repair if so defined by the Committee",
      "Yes — free relief from any damage caused by maintenance equipment",
      "Yes — the tracks are automatically abnormal course conditions",
      "No relief at all; play it as it lies regardless",
    ],
    correct: 0,
    rule: "Rule 8.1d, Definition of Ground Under Repair",
    explanation:
      "Under Rule 8.1d, if conditions affecting your stroke are worsened by someone else, there is generally no relief unless the damage creates a condition that qualifies as an abnormal course condition (like ground under repair). The Committee may mark the tracks as GUR, but without such marking, you play it as it lies.",
    tags: ["improving conditions", "general area", "play it as it lies", "ground under repair"],
  },
  {
    id: "gen_b23",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is behind a boundary fence (white stakes). The fence interferes with your backswing. Can you get free relief from the boundary fence?",
    choices: [
      "No — boundary objects (fences, stakes, walls) are not obstructions and no free relief is available",
      "Yes — you get free relief from any man-made object on the course",
      "Yes, but only if the ball is in the general area",
      "Only if a Local Rule grants relief from boundary fences",
    ],
    correct: 0,
    rule: "Rule 8.1a, Definition of Obstruction",
    explanation:
      "Boundary objects (white stakes, fences, walls) are not obstructions under the Rules — they are boundary objects. You are not entitled to free relief from them. You must play the ball as it lies, take an unplayable, or use other available relief options.",
    tags: ["improving conditions", "play it as it lies", "general area"],
  },
  {
    id: "gen_b24",
    category: "PLAYING_BALL",
    tier: "official",
    text: "You mark and lift your ball on the putting green, then repair a pitch mark that is on your line of putt. You then realize the pitch mark was actually in the fringe, not on the green. Is there a penalty?",
    choices: [
      "Yes — repairing damage off the putting green to improve your line of play results in the general penalty",
      "No — you can repair any pitch mark near the green",
      "No penalty since you were on the putting green when you did it",
      "No — pitch marks can be repaired anywhere on the course",
    ],
    correct: 0,
    rule: "Rule 8.1a, Rule 13.1c",
    explanation:
      "The right to repair damage under Rule 13.1c applies only on the putting green itself. If you repair damage off the green (in the fringe/general area) and it improves your line of play, it is a breach of Rule 8.1a, resulting in the general penalty.",
    tags: ["improving line of play", "putting green", "play it as it lies"],
  },
  {
    id: "gen_b25",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Your ball is on the cart path and you are taking free relief. While determining the nearest point of complete relief, you flatten some grass in the rough with your feet. Is this a penalty?",
    choices: [
      "No penalty — actions taken while determining a relief area are part of the relief procedure",
      "General penalty for improving conditions in the relief area",
      "One-stroke penalty for altering the area",
      "No penalty, but you must use a different reference point",
    ],
    correct: 0,
    rule: "Rule 8.1b",
    explanation:
      "Actions reasonably taken to determine a reference point or relief area (like walking through the area) are not a breach of Rule 8.1a. You are entitled to take reasonable steps in the relief process without penalty.",
    tags: ["improving conditions", "free relief", "general area"],
  },
  {
    id: "gen_b26",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is sitting in a sandy area of the rough. You brush away some sand from around the ball to see it better before your stroke (you are not searching). What is the ruling?",
    choices: [
      "General penalty — removing sand to improve your lie is not allowed outside the putting green",
      "No penalty — sand is a loose impediment",
      "No penalty as long as you didn't move the ball",
      "One-stroke penalty for touching the ground near your ball",
    ],
    correct: 0,
    rule: "Rule 8.1a",
    explanation:
      "Under Rule 8.1a, you must not improve conditions affecting your stroke. While sand and loose soil on the putting green may be removed, in the general area sand and loose soil are not loose impediments and removing them to improve your lie is a breach resulting in the general penalty.",
    tags: ["improving lie", "play it as it lies", "general area", "rough"],
  },

  // =============================================
  // RULE 9: BALL PLAYED AS IT LIES
  // =============================================

  {
    id: "gen_b27",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You set your club behind the ball at address, and the ball rolls backward. Did you cause the ball to move?",
    choices: [
      "You are deemed to have caused the ball to move unless you can prove natural forces caused it",
      "No — setting a club behind the ball never causes movement",
      "One-stroke penalty automatically, no questions asked",
      "No penalty — the ball moved on its own",
    ],
    correct: 0,
    rule: "Rule 9.4b(1)",
    explanation:
      "Under Rule 9.4b(1), if your ball at rest moves after you have addressed it or begun your backswing, you are deemed to have caused the ball to move unless it is known or virtually certain that natural forces caused the movement. You get a one-stroke penalty and must replace it.",
    tags: ["ball moved", "ball at rest", "play it as it lies", "fairway"],
  },
  {
    id: "gen_b28",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "A gust of wind blows your ball off the tee before you make a stroke. What do you do?",
    choices: [
      "Re-tee the ball without penalty — a ball on a tee is not yet in play",
      "Play it from the ground where it rolled to, no penalty",
      "One-stroke penalty; re-tee",
      "One-stroke penalty; play from where it stopped",
    ],
    correct: 0,
    rule: "Rule 6.2b(5)",
    explanation:
      "A ball on the tee is not yet in play (it becomes in play when you make a stroke at it). If it falls off the tee or is blown off by wind before a stroke is made, you simply re-tee it without penalty.",
    tags: ["ball moved", "wind", "natural forces", "teeing area"],
  },
  {
    id: "gen_b29",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is sitting on the edge of the fairway. While you are walking up to it (before addressing it), the ball rolls into the rough due to wind. What is the ruling?",
    choices: [
      "No penalty; play the ball from its new position in the rough",
      "No penalty; replace the ball on the fairway",
      "One-stroke penalty; play from the rough",
      "Free relief back to the fairway",
    ],
    correct: 0,
    rule: "Rule 9.3",
    explanation:
      "Under Rule 9.3, when natural forces (wind, gravity, water) cause your ball at rest to move to a new position, you play it from the new position with no penalty. Since you had not yet addressed the ball or lifted and replaced it, it must be played from where it now lies.",
    tags: ["ball moved", "wind", "natural forces", "ball at rest", "fairway"],
  },
  {
    id: "gen_b30",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Your ball is at rest in the fairway. A dog runs across the course, picks up your ball, and carries it away. You cannot retrieve it. What do you do?",
    choices: [
      "No penalty; substitute a ball and place it on the estimated original spot",
      "One-stroke penalty; drop a new ball where the dog picked it up",
      "The ball is lost — take stroke-and-distance relief",
      "Free drop anywhere in the fairway within two club-lengths",
    ],
    correct: 0,
    rule: "Rule 9.6",
    explanation:
      "Under Rule 9.6, when an outside influence (including an animal) moves your ball at rest, there is no penalty. You must replace the ball on its original spot (estimated if not known). If the ball cannot be recovered, you may substitute another ball.",
    tags: ["outside influence", "ball at rest", "substituted ball", "fairway"],
  },
  {
    id: "gen_b31",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You accidentally kick your ball while walking to your next shot. What happens?",
    choices: [
      "One-stroke penalty; replace the ball on its original spot",
      "No penalty; replace the ball",
      "No penalty; play it from the new spot",
      "Two-stroke penalty; replace the ball",
    ],
    correct: 0,
    rule: "Rule 9.4b",
    explanation:
      "Under Rule 9.4, if you (the player) cause your ball at rest to move, you get a one-stroke penalty and must replace the ball on its original spot. This applies whether you move it with your foot, club, or any other way.",
    tags: ["accidentally moved", "ball at rest", "penalty", "general area"],
  },
  {
    id: "gen_b32",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Your fellow competitor in stroke play accidentally moves your ball while searching for their own ball. What happens?",
    choices: [
      "No penalty to anyone; replace your ball on its original spot",
      "Your fellow competitor gets a one-stroke penalty; replace your ball",
      "You get a one-stroke penalty; replace your ball",
      "No penalty; play your ball from the new spot",
    ],
    correct: 0,
    rule: "Rule 9.6",
    explanation:
      "In stroke play, a fellow competitor is an outside influence. Under Rule 9.6, when an outside influence moves your ball at rest, there is no penalty to anyone. You must replace your ball on its original spot (estimated if necessary).",
    tags: ["outside influence", "ball at rest", "accidentally moved", "stroke play"],
  },
  {
    id: "gen_b33",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "In match play, your opponent accidentally moves your ball while searching for it. What is the ruling?",
    choices: [
      "No penalty to anyone; replace the ball — Rule 7.4 protects all players during a search",
      "Your opponent gets a one-stroke penalty; replace the ball",
      "Your opponent loses the hole",
      "No penalty; play from the new position",
    ],
    correct: 0,
    rule: "Rule 7.4",
    explanation:
      "Under Rule 7.4, if a ball is accidentally moved during a search by anyone (the player, opponent, fellow competitor, or anyone else), there is no penalty. The ball must be replaced on its original spot. The search protection overrides the normal Rule 9.5b opponent penalty.",
    tags: ["match play", "accidentally moved", "ball at rest", "searching"],
  },
  {
    id: "gen_b34",
    category: "PLAYING_BALL",
    tier: "official",
    text: "Your ball is at rest on a steep slope. You address the ball. Before you swing, the ball begins rolling down the slope due to gravity. What must you do?",
    choices: [
      "You are deemed to have caused it to move — one-stroke penalty, replace the ball",
      "No penalty; play from the new spot since natural forces caused the movement",
      "No penalty; replace the ball on the original spot",
      "Two-stroke penalty; replace the ball",
    ],
    correct: 0,
    rule: "Rule 9.4b(2)",
    explanation:
      "Under Rule 9.4b(2), once you have addressed the ball, you are presumed to have caused it to move unless it is known or virtually certain that natural forces caused the movement. The burden is on you to prove natural forces were responsible; otherwise, it is a one-stroke penalty and you must replace the ball.",
    tags: ["ball moved", "ball at rest", "natural forces", "play it as it lies"],
  },
  {
    id: "gen_b35",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is at rest in the fairway. Another player's ball in motion strikes your ball and moves it. What happens to your ball?",
    choices: [
      "No penalty; replace your ball on its original spot",
      "No penalty; play from the new spot",
      "The other player gets a penalty; replace your ball",
      "You must drop your ball within one club-length of where it was hit",
    ],
    correct: 0,
    rule: "Rule 9.6, Rule 11.1",
    explanation:
      "When a ball in motion moves your ball at rest, your ball must be replaced on its original spot under Rule 9.6. There is no penalty to you. The player whose ball struck yours plays their ball from where it came to rest (no penalty to them either, in most cases).",
    tags: ["ball at rest", "ball in motion", "stacked balls", "fairway"],
  },
  {
    id: "gen_b36",
    category: "PLAYING_BALL",
    tier: "official",
    text: "Your ball is on a slope. You mark it, lift it, clean it, and replace it. A few seconds later, gravity causes the ball to roll to a new position. What do you do?",
    choices: [
      "Replace the ball on the original spot — after being lifted and replaced, it must be replaced again if natural forces move it",
      "Play from the new position since natural forces caused the movement",
      "One-stroke penalty; replace the ball",
      "Drop the ball on the original spot since it won't stay",
    ],
    correct: 0,
    rule: "Rule 9.3, Exception",
    explanation:
      "Under the exception to Rule 9.3, if a ball that has been lifted and replaced is moved by natural forces (wind, gravity), it must be replaced on its original spot, with no penalty. This is different from a ball that was never lifted — in that case, you'd play from the new position.",
    tags: ["ball moved", "natural forces", "ball at rest", "replace ball"],
  },
  {
    id: "gen_b37",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "You place your club on the ground behind the ball to align your shot. The clubhead moves your ball slightly. What is the ruling?",
    choices: [
      "One-stroke penalty; replace the ball on its original spot",
      "No penalty; replace the ball",
      "General penalty (two strokes) for grounding the club improperly",
      "No penalty; play from the new position",
    ],
    correct: 0,
    rule: "Rule 9.4b",
    explanation:
      "Under Rule 9.4, if you cause your ball at rest to move, you get a one-stroke penalty and must replace the ball. Touching or moving the ball with your club while grounding it counts as causing the ball to move.",
    tags: ["ball moved", "ball at rest", "club", "accidentally moved"],
  },
  {
    id: "gen_b38",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your ball is at rest in the fairway. A sprinkler head suddenly pops up and moves your ball. What is the ruling?",
    choices: [
      "No penalty; replace the ball on its original spot — the sprinkler is an outside influence",
      "No penalty; play from the new position",
      "Free relief from the sprinkler head",
      "One-stroke penalty; replace the ball",
    ],
    correct: 0,
    rule: "Rule 9.6",
    explanation:
      "A sprinkler head that activates and moves your ball is treated as an outside influence under Rule 9.6. There is no penalty, and you must replace the ball on its original spot (estimated if necessary).",
    tags: ["outside influence", "ball at rest", "fairway", "replace ball"],
  },
  {
    id: "gen_b39",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "You drop your spare ball from your pocket while walking, and it accidentally hits your ball in play, causing it to move. What is the ruling?",
    choices: [
      "One-stroke penalty; replace the ball — your equipment caused the movement",
      "No penalty; replace the ball since it was accidental",
      "No penalty; play from the new position",
      "General penalty; replace the ball",
    ],
    correct: 0,
    rule: "Rule 9.4b",
    explanation:
      "Under Rule 9.4, if you cause your ball at rest to move, you get a one-stroke penalty. A spare ball you drop is your equipment, and your equipment causing your ball to move is treated as you causing the movement. Replace the ball on its original spot.",
    tags: ["accidentally moved", "ball at rest", "equipment", "penalty"],
  },
  {
    id: "gen_b40",
    category: "PLAYING_BALL",
    tier: "official",
    text: "Your ball is at rest on the putting green. An earthquake tremor causes it to move to a new position. You had NOT lifted and replaced the ball before the tremor. What do you do?",
    choices: [
      "Play the ball from the new position — natural forces moved a ball that had not been lifted and replaced",
      "Replace it on the original spot",
      "Drop at the original spot",
      "Choose whichever position you prefer",
    ],
    correct: 0,
    rule: "Rule 9.3",
    explanation:
      "Under Rule 9.3, when natural forces move a ball at rest, you generally play from the new position with no penalty. The exception (requiring replacement) only applies on the putting green when the ball had been lifted and replaced before being moved by natural forces. Since this ball had not been lifted and replaced, play from the new spot.",
    tags: ["natural forces", "ball at rest", "ball moved", "putting green"],
  },
  {
    id: "gen_b41",
    category: "PLAYING_BALL",
    tier: "official",
    text: "After your ball comes to rest against a tree, another player's cart accidentally drives over and breaks a branch that was in your intended line of play, improving your conditions. What happens?",
    choices: [
      "No penalty to you — you must accept the changed conditions caused by an outside influence",
      "You must restore the branch to its original position",
      "Free relief because an outside influence changed conditions",
      "You get a penalty for allowing your conditions to be improved",
    ],
    correct: 0,
    rule: "Rule 8.1d",
    explanation:
      "Under Rule 8.1d, if an outside influence or another player worsens or improves conditions affecting your stroke, you generally cannot restore them. You must accept the new conditions unless a specific Rule provides otherwise. The improvement was not your action, so no penalty to you.",
    tags: ["improving conditions", "outside influence", "play it as it lies"],
  },

  // =============================================
  // RULE 10: PREPARING FOR AND MAKING A STROKE
  // =============================================

  {
    id: "gen_b42",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "During your round on a par 3, before either of you has played, you ask your playing partner what club they plan to use. In stroke play, what is the penalty?",
    choices: [
      "Two-stroke penalty on you for asking for advice",
      "Two-stroke penalty on your playing partner for giving advice (if they answer)",
      "No penalty — club selection is public information",
      "Both of you receive a two-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 10.2a",
    explanation:
      "Under Rule 10.2a, 'advice' includes any verbal comment or action intended to influence a player's decision on how to play, including club selection. Asking what club another player plans to use before they play is asking for advice and results in the general penalty (two strokes). Note: looking into another player's bag to see what club they selected is NOT advice because it is publicly available information. But directly asking is.",
    tags: ["advice", "stroke play", "penalty", "club selection"],
  },
  {
    id: "gen_b43",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You look into another player's bag to see what club they used on the previous hole. Is this allowed?",
    choices: [
      "Yes — looking at a club someone left out or observing their bag is not asking for advice",
      "No — any attempt to learn what club another player used is a penalty",
      "Only if the other player doesn't notice",
      "Only in match play, not stroke play",
    ],
    correct: 0,
    rule: "Rule 10.2a, Interpretation",
    explanation:
      "Looking at another player's clubs in their bag or observing what club they hold is not a breach of Rule 10.2a. 'Advice' requires a verbal communication or action specifically intended to influence. Passive observation of publicly visible information is not asking for advice.",
    tags: ["advice", "club", "stroke play"],
  },
  {
    id: "gen_b44",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You share yardage information with another player during your round. Is this considered advice?",
    choices: [
      "No — distance and publicly available information is not advice",
      "Yes — sharing any playing information is advice",
      "Only if the player asked for it",
      "Only in stroke play, not match play",
    ],
    correct: 0,
    rule: "Rule 10.2a, Definition of Advice",
    explanation:
      "Under the definition of Advice, publicly available information such as distances, the position of hazards, or the location of the flagstick on the green is not advice. You can freely share this kind of information without penalty.",
    tags: ["advice", "stroke play", "match play"],
  },
  {
    id: "gen_b45",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Your caddie holds an umbrella over you to shield you from rain while you play your shot. Is this allowed?",
    choices: [
      "No — no one may deliberately protect you from the elements while you are making a stroke",
      "Yes — your caddie may assist you in any way",
      "Yes — protection from rain is always allowed",
      "Only if you are not on the putting green",
    ],
    correct: 0,
    rule: "Rule 10.2b(5)",
    explanation:
      "Under Rule 10.2b(5), no one may deliberately position an object or stand in a position to protect you from sun, rain, wind, or other elements while you are making a stroke. Your caddie must lower the umbrella before you swing.",
    tags: ["caddie", "equipment", "improving conditions"],
  },
  {
    id: "gen_b46",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "You anchor the butt end of your putter against your stomach while making a putting stroke. Is this a legal stroke?",
    choices: [
      "No — anchoring the club against your body is not allowed, resulting in the general penalty",
      "Yes — you may hold the club however you like",
      "Yes, but only for putts inside 10 feet",
      "No — it's a disqualification offense",
    ],
    correct: 0,
    rule: "Rule 10.1b",
    explanation:
      "Under Rule 10.1b, you must not make a stroke by anchoring the club against your body (either directly or by using an 'anchor point' with your forearm). This applies to all strokes, including putts. The penalty is the general penalty (two strokes / loss of hole).",
    tags: ["anchoring", "putting", "club", "stroke play"],
  },
  {
    id: "gen_b47",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You use a swing alignment stick placed on the ground during a practice swing on the tee, then remove it before hitting your actual shot. Is this allowed?",
    choices: [
      "No — you must not use any alignment device during a round, even for a practice swing",
      "Yes — alignment devices are always allowed during practice swings",
      "Yes — as long as you remove it before the actual stroke",
      "Only on the practice range, not the course",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, you must not use equipment in an abnormal way to assist your play. Setting an alignment aid on the ground — even for a practice swing during a round — is a breach, as it helps you align or aim. The penalty is the general penalty.",
    tags: ["equipment", "alignment", "practice swing"],
  },
  {
    id: "gen_b48",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "In a four-ball match, your partner (who is not your caddie) gives you advice on how to read a putt. Is this allowed?",
    choices: [
      "Yes — in a team format like four-ball, partners may give each other advice freely",
      "No — advice between any players is prohibited",
      "Yes, but only in match play, not stroke play",
      "No — only caddies may give advice",
    ],
    correct: 0,
    rule: "Rule 10.2a, Rule 23.5a",
    explanation:
      "Under Rule 10.2a, advice may only be given to and received from your caddie, your partner, and your partner's caddie. In four-ball (or any partnership format), partners are specifically permitted to give each other advice without penalty.",
    tags: ["advice", "match play", "partner"],
  },
  {
    id: "gen_b49",
    category: "PLAYING_BALL",
    tier: "official",
    text: "During your stroke, you accidentally hit the ball twice — your clubhead catches the ball on the follow-through. What is the ruling?",
    choices: [
      "No penalty; it counts as one stroke — play the ball as it lies",
      "One additional penalty stroke; play the ball as it lies",
      "The stroke does not count; replay it",
      "Two-stroke penalty; play from where the ball ends up",
    ],
    correct: 0,
    rule: "Rule 10.1a",
    explanation:
      "Under Rule 10.1a, if your club accidentally hits the ball more than once during a single stroke, there is no penalty. It counts as just one stroke, and you play the ball as it lies.",
    tags: ["double hit", "club", "ball in motion"],
  },
  {
    id: "gen_b50",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "On the putting green, your caddie touches the green to point out the line of putt before you make your stroke. Is this a penalty?",
    choices: [
      "No penalty — a caddie may touch the putting green to indicate the line of putt as long as they don't improve conditions",
      "General penalty — no one may touch the green on your line of putt",
      "One-stroke penalty on the caddie",
      "No penalty, but only in match play",
    ],
    correct: 0,
    rule: "Rule 10.2b(2)",
    explanation:
      "Under Rule 10.2b(2), before you make a stroke, your caddie may touch the putting green to indicate your line of putt (the target and line), but must not improve the conditions for the stroke (e.g., pressing down a mark).",
    tags: ["caddie", "putting green", "line of play", "advice"],
  },
  {
    id: "gen_b51",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "You place a tee on the ground behind your ball to help you aim, then remove it before making your stroke. Is there a penalty?",
    choices: [
      "Yes — the general penalty applies. You may not set an alignment aid, even if removed before the stroke",
      "No — as long as you remove it before swinging, there is no penalty",
      "One-stroke penalty only",
      "No penalty if the object was a tee already in your hand",
    ],
    correct: 0,
    rule: "Rule 10.2b(3)",
    explanation:
      "Under Rule 10.2b(3), you must not set an object down (or draw a line) to help aim for your stroke, regardless of whether you remove it before making the stroke. The general penalty applies as soon as the object is placed for alignment purposes.",
    tags: ["alignment", "equipment", "penalty", "play it as it lies"],
  },
  {
    id: "gen_b52",
    category: "PLAYING_BALL",
    tier: "official",
    text: "Your caddie, without your knowledge, stands behind you on an extension of your line of play while you begin taking your stance. You don't notice until after you've hit the shot. Is there a penalty?",
    choices: [
      "Yes — the general penalty applies regardless of whether you were aware of the caddie's position",
      "No — you must be aware of the caddie's position for a penalty to apply",
      "One-stroke penalty only since it was unintentional",
      "No penalty if the caddie moved before you completed the stroke",
    ],
    correct: 0,
    rule: "Rule 10.2b(4)",
    explanation:
      "Under Rule 10.2b(4), if your caddie deliberately stands on or close to your line of play extended behind you when you begin taking a stance for the stroke and you make the stroke without the caddie moving away, the general penalty applies — even if you were unaware.",
    tags: ["caddie", "alignment", "line of play", "penalty"],
  },
  {
    id: "gen_b53",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "While standing over your putt, you rest your putter against your forearm to create a stable anchor point. Is this a legal stroke?",
    choices: [
      "No — using a forearm as an anchor point is prohibited, resulting in the general penalty",
      "Yes — you may rest the club against your forearm",
      "No — but only if the club touches your body above the waist",
      "Yes, as long as the grip doesn't touch your body",
    ],
    correct: 0,
    rule: "Rule 10.1b",
    explanation:
      "Under Rule 10.1b, the club must not be anchored, either directly against your body or by using a 'forearm anchor' where a forearm is held against the body to create a stable anchor point. This is the general penalty (two strokes / loss of hole).",
    tags: ["anchoring", "putting", "club", "penalty"],
  },
  {
    id: "gen_b54",
    category: "PLAYING_BALL",
    tier: "official",
    text: "You use a distance-measuring device (rangefinder) during your round to measure the distance to the flagstick. Is this allowed?",
    choices: [
      "Yes — distance-measuring devices are allowed unless the Committee has prohibited them by Local Rule",
      "No — electronic devices are never allowed during a round",
      "Yes, but only in casual rounds, not tournaments",
      "Only if the device measures distance only and not slope",
    ],
    correct: 0,
    rule: "Rule 4.3a(1)",
    explanation:
      "Under Rule 4.3a(1), you may use a device to measure distance only. By default, DMDs are allowed. However, the Committee may prohibit them by Local Rule. If the device has slope capability, the slope feature must be disabled or turned off.",
    tags: ["equipment", "stroke play", "match play"],
  },
  {
    id: "gen_b55",
    category: "PLAYING_BALL",
    tier: "official",
    text: "You use a rangefinder with the slope feature turned ON during a competition that allows distance-measuring devices. What is the penalty?",
    choices: [
      "General penalty for the first breach; disqualification for the second breach",
      "No penalty — slope is fine as long as the device measures distance",
      "Disqualification immediately",
      "One-stroke penalty per use",
    ],
    correct: 0,
    rule: "Rule 4.3a(1)",
    explanation:
      "Under Rule 4.3, using a device's slope feature (or any feature that gauges conditions or recommends club selection) gives the general penalty for the first breach and disqualification for a subsequent breach, even if the Committee has allowed distance-measuring devices.",
    tags: ["equipment", "penalty", "stroke play"],
  },
  {
    id: "gen_b56",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Between holes, you listen to music on headphones. Is this allowed under the Rules?",
    choices: [
      "No — listening to music during a round is not allowed as it may eliminate outside distractions",
      "Yes — you may listen to music between holes but not during a stroke",
      "Yes — there are no restrictions on music during a round",
      "Only with Committee approval",
    ],
    correct: 0,
    rule: "Rule 4.3a(4)",
    explanation:
      "Under Rule 4.3a(4), you must not listen to music or other audio content during a round to eliminate distractions or help with your swing tempo. This applies at all times during the round, not just during strokes. The general penalty applies.",
    tags: ["equipment", "penalty"],
  },
  {
    id: "gen_b57",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "Your caddie stands behind you on an extension of your line of play while you take your stance, then moves away before you make the stroke. Is there a penalty?",
    choices: [
      "Yes — the general penalty applies because the caddie was behind you when you began taking your stance, even though they moved before the stroke",
      "No penalty — the restriction only applies if the caddie is still behind you when you make the stroke",
      "One-stroke penalty on the caddie",
      "No penalty; caddies may stand anywhere at any time",
    ],
    correct: 0,
    rule: "Rule 10.2b(4)",
    explanation:
      "Under Rule 10.2b(4), from the time you begin taking a stance for the stroke and until the stroke is made, your caddie must not deliberately stand on or close to an extension of your line of play behind you. The breach occurs when you begin taking your stance with the caddie in that position. The caddie moving away afterward does not cure the breach — the general penalty applies. To avoid the penalty, you must back away from your stance, have the caddie move, and then retake your stance.",
    tags: ["caddie", "line of play", "alignment", "stance"],
  },

  // =============================================
  // RULE 11: BALL IN MOTION ACCIDENTALLY DEFLECTED
  // =============================================

  {
    id: "gen_b58",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You hit a chip shot and the ball strikes the flagstick and bounces away from the hole. What is the ruling?",
    choices: [
      "No penalty; play the ball as it lies",
      "One-stroke penalty; play as it lies",
      "No penalty; replay the shot",
      "You must replace the ball at the point it hit the flagstick",
    ],
    correct: 0,
    rule: "Rule 11.1a, Rule 13.2a(2)",
    explanation:
      "There is no penalty when your ball hits the flagstick, whether left in, attended, or removed. Under Rule 11.1a, if your ball in motion accidentally hits any person or outside influence, there is no penalty — play the ball as it lies.",
    tags: ["ball in motion", "flagstick", "general area"],
  },
  {
    id: "gen_b59",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You play a shot from the fairway and the ball accidentally hits a fellow competitor walking ahead. What happens in stroke play?",
    choices: [
      "No penalty to either player; play the ball as it lies",
      "One-stroke penalty on you; play as it lies",
      "Two-stroke penalty on you; replay the shot",
      "No penalty; the fellow competitor may place the ball where they want",
    ],
    correct: 0,
    rule: "Rule 11.1a",
    explanation:
      "Under Rule 11.1a, if your ball in motion accidentally hits any person (including a fellow competitor), there is no penalty to anyone. You must play the ball as it lies.",
    tags: ["ball in motion", "outside influence", "stroke play"],
  },
  {
    id: "gen_b60",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You hit a shot that bounces off a tree and comes back and hits you in the leg. What is the ruling?",
    choices: [
      "No penalty; play the ball as it lies",
      "One-stroke penalty; play the ball as it lies",
      "No penalty; replay the shot",
      "Two-stroke penalty; play as it lies",
    ],
    correct: 0,
    rule: "Rule 11.1a",
    explanation:
      "Under Rule 11.1a, if your ball in motion accidentally hits you, your caddie, or your equipment, there is no penalty. You simply play the ball as it lies. The old rule that penalized this was changed in 2019.",
    tags: ["ball in motion", "play it as it lies"],
  },
  {
    id: "gen_b61",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "Your ball is rolling toward a penalty area. Your caddie runs over and stops the ball with their foot to prevent it from going in. What happens?",
    choices: [
      "General penalty (two strokes); the ball must be placed on the estimated spot where it would have come to rest",
      "No penalty — your caddie was trying to help",
      "One-stroke penalty; play from where the caddie stopped it",
      "General penalty; replace the ball where it was when stopped and replay",
    ],
    correct: 0,
    rule: "Rule 11.2c",
    explanation:
      "Under Rule 11.2, if you, your caddie, or your equipment deliberately deflects or stops your ball in motion, you get the general penalty. Under Rule 11.2c, the ball must be placed on the estimated spot where it would have come to rest (or, if it would have gone into a penalty area, take penalty area relief).",
    tags: ["ball in motion", "deliberate deflection", "caddie", "penalty"],
  },
  {
    id: "gen_b62",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You hit a shot from the bunker and the ball hits a rake lying at the edge of the bunker and deflects sideways. What is the ruling?",
    choices: [
      "No penalty; play the ball as it lies",
      "Free drop within one club-length of where the ball hit the rake",
      "Replay the shot from the bunker, no penalty",
      "One-stroke penalty; play as it lies",
    ],
    correct: 0,
    rule: "Rule 11.1a",
    explanation:
      "Under Rule 11.1a, if your ball in motion is accidentally deflected by equipment or any outside influence, there is no penalty. Play the ball as it lies, even if the deflection sent it to an unfavorable location.",
    tags: ["ball in motion", "equipment", "bunker"],
  },
  {
    id: "gen_b63",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "You play a shot from the rough and your ball strikes another player's ball at rest in the fairway. Both balls move. What happens in stroke play?",
    choices: [
      "No penalty to either player; you play your ball as it lies, the other ball is replaced",
      "Two-stroke penalty on you; both balls played as they lie",
      "No penalty; both balls played from their new positions",
      "One-stroke penalty on you; the other ball is replaced",
    ],
    correct: 0,
    rule: "Rule 11.1a, Rule 9.6",
    explanation:
      "Under Rule 11.1a, when your ball in motion accidentally hits another ball at rest, there is no penalty (exception: when both balls are on the putting green in stroke play). You play your ball from its new position. The other player's ball must be replaced on its original spot under Rule 9.6.",
    tags: ["ball in motion", "ball at rest", "stacked balls", "stroke play"],
  },
  {
    id: "gen_b64",
    category: "PLAYING_BALL",
    tier: "official",
    text: "In match play, your ball in motion is about to roll off the green. Your opponent deliberately stops it with their foot. What is the ruling?",
    choices: [
      "Your opponent gets the general penalty (loss of hole)",
      "You may choose to either estimate where the ball would have come to rest and place it there, or cancel the stroke and replay it",
      "Your opponent gets a one-stroke penalty; play the ball as it lies",
      "No penalty and no remedy — play the ball as it lies where it was stopped",
    ],
    correct: 1,
    rule: "Rule 11.2c",
    explanation:
      "Under Rule 11.2c, when an opponent deliberately deflects or stops your ball in motion in match play, there is no penalty to the opponent. Instead, you (the player whose ball was stopped) get to choose the outcome: either estimate where the ball would have come to rest and place it at that spot, or cancel the stroke and replay it. This gives you the advantage, not a penalty to the opponent.",
    tags: ["ball in motion", "deliberate deflection", "match play", "opponent"],
  },
  {
    id: "gen_b65",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You play a shot and your ball hits a bird in mid-flight and drops into a bunker. What is the ruling?",
    choices: [
      "No penalty; play the ball as it lies in the bunker",
      "Free drop outside the bunker since a bird interfered",
      "Replay the shot without penalty",
      "One-stroke penalty; play from the bunker",
    ],
    correct: 0,
    rule: "Rule 11.1a",
    explanation:
      "Under Rule 11.1a, if your ball in motion is accidentally deflected by an animal (an outside influence), there is no penalty. You must play the ball as it lies, even if the deflection sent it into an unfavorable location.",
    tags: ["ball in motion", "outside influence", "bunker"],
  },
  {
    id: "gen_b66",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "You putt your ball on the green. While it is still rolling, you realize it's going to miss badly, so you reach out and swat the ball to stop it. What is the penalty?",
    choices: [
      "General penalty; the ball must be placed on the estimated spot where it would have come to rest",
      "One-stroke penalty; replay the putt",
      "Disqualification for unsportsmanlike conduct",
      "No penalty if it was clearly going to miss the hole",
    ],
    correct: 0,
    rule: "Rule 11.2c",
    explanation:
      "Under Rule 11.2, deliberately stopping your own ball in motion results in the general penalty (two strokes in stroke play, loss of hole in match play). The ball is placed on the spot where it is estimated it would have come to rest if not stopped.",
    tags: ["ball in motion", "deliberate deflection", "putting green", "penalty"],
  },
  {
    id: "gen_b67",
    category: "PLAYING_BALL",
    tier: "weekend",
    text: "You hit a pitch shot and the ball hits the flagstick (which you left in the hole) and bounces into a bunker. What are your options?",
    choices: [
      "No penalty; play the ball as it lies in the bunker — you accepted the risk of leaving the flagstick in",
      "Replay the shot without penalty since the flagstick interfered",
      "Drop within one club-length of the hole, no penalty",
      "Replace the ball at the spot where it hit the flagstick",
    ],
    correct: 0,
    rule: "Rule 11.1a, Rule 13.2a(2)",
    explanation:
      "There is no penalty when your ball hits the flagstick. Regardless of where the ball ends up — even if it deflects into a bunker — you must play the ball as it lies. You accepted the risk by leaving the flagstick in.",
    tags: ["ball in motion", "flagstick", "bunker"],
  },
  {
    id: "gen_b68",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "In match play, you play a chip shot from just off the green. While your ball is still rolling on the green, your opponent putts their ball, and the two balls collide. What happens?",
    choices: [
      "No penalty to either player; you play your ball from where it comes to rest, but your opponent must replay their putt",
      "No penalty to either player; both balls are played from where they come to rest",
      "Both balls must be replayed",
      "Your opponent gets a penalty for playing out of turn",
    ],
    correct: 0,
    rule: "Rule 11.1a, Clarification 11.1b(2)/1",
    explanation:
      "Under the 2026 Clarification 11.1b(2)/1, a ball in motion on the putting green is treated as a movable obstruction. Your opponent putted from the putting green and their ball hit your ball (a 'movable obstruction' in motion on the green), so your opponent must replay their stroke without penalty. Your ball was played from off the green, so Rule 11.1b(2) does not apply to you — you play your ball from where it comes to rest under Rule 11.1a. No penalty to either player.",
    tags: ["ball in motion", "collision", "match play", "putting green", "2026 clarification"],
  },
  {
    id: "gen_b69",
    category: "PLAYING_BALL",
    tier: "official",
    text: "You deliberately position your golf bag near the green so that if your chip rolls past the hole, the bag will stop it. Your ball does hit the bag. What is the ruling?",
    choices: [
      "General penalty; the ball must be placed on the estimated spot where it would have come to rest without the bag",
      "No penalty since the bag was your equipment",
      "One-stroke penalty; replay the shot",
      "General penalty; replay from the original spot",
    ],
    correct: 0,
    rule: "Rule 11.2a, Rule 11.2c",
    explanation:
      "Under Rule 11.2a, deliberately positioning equipment to potentially deflect a ball in motion is a breach. The general penalty applies, and the ball must be placed on the estimated spot where it would have come to rest if the equipment had not been there.",
    tags: ["ball in motion", "deliberate deflection", "equipment", "penalty"],
  },
  {
    id: "gen_b70",
    category: "PLAYING_BALL",
    tier: "official",
    text: "In stroke play, you putt from the putting green. Your ball hits your playing partner's ball, which was also at rest on the putting green. What is the penalty?",
    choices: [
      "Two-stroke penalty on you (the player who putted); your ball is played as it lies, the other ball is replaced",
      "No penalty to either player; both balls played as they lie",
      "Two-stroke penalty on both players",
      "No penalty; the other ball is replaced, you replay your putt",
    ],
    correct: 0,
    rule: "Rule 11.1a, Exception in Stroke Play",
    explanation:
      "In stroke play only, when both balls were on the putting green before the stroke and your ball hits the other ball, you receive a two-stroke penalty. Your ball is played as it lies, and the other ball must be replaced on its original spot. This exception does not apply in match play.",
    tags: ["ball in motion", "ball at rest", "putting green", "stacked balls", "stroke play"],
  },
  {
    id: "gen_b71",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "You play a shot and your ball in motion is about to go out of bounds. A spectator deliberately kicks the ball back onto the course. What is the ruling?",
    choices: [
      "The ball must be placed on the estimated spot where it would have come to rest or gone out of bounds — if out of bounds, take stroke-and-distance",
      "Play the ball as it lies since it was a spectator who moved it",
      "No penalty; replay the shot",
      "The spectator is penalized and you play from where the ball stopped",
    ],
    correct: 0,
    rule: "Rule 11.2c",
    explanation:
      "Under Rule 11.2c, when any person deliberately deflects or stops a ball in motion, the ball is not played as it lies. Instead, the ball is placed on the estimated spot where it would have come to rest. If it would have gone out of bounds, you must take stroke-and-distance relief. No penalty to you.",
    tags: ["ball in motion", "deliberate deflection", "outside influence", "spectator"],
  },
  {
    id: "gen_b72",
    category: "PLAYING_BALL",
    tier: "official",
    text: "You play a shot from the fairway and your ball in motion hits another ball at rest that belongs to your playing partner, also in the fairway. In stroke play, what is the full ruling?",
    choices: [
      "No penalty to either player; your ball is played as it lies, the other ball must be replaced on its original spot",
      "Two-stroke penalty on you; both balls played as they lie",
      "No penalty to you, but the other player is penalized for not moving their ball",
      "Two-stroke penalty on the other player for interference; both balls played as they lie",
    ],
    correct: 0,
    rule: "Rule 11.1a, Rule 9.6",
    explanation:
      "Under Rule 11.1a, when your ball played from off the putting green hits another ball at rest, there is no penalty to anyone (the stroke-play exception only applies when both balls are on the putting green). Your ball is played from where it comes to rest. The other ball is replaced on its original spot under Rule 9.6.",
    tags: ["ball in motion", "ball at rest", "stacked balls", "stroke play", "fairway"],
  },
  {
    id: "gen_b73",
    category: "PLAYING_BALL",
    tier: "official",
    text: "On the putting green in stroke play, you putt and your ball is rolling toward the hole. Your playing partner, thinking you've already holed out, picks up the flagstick and your rolling ball hits them. What happens?",
    choices: [
      "No penalty to anyone; play the ball as it lies",
      "Two-stroke penalty on the playing partner; replay the putt",
      "No penalty; you may choose to replay the stroke or accept the result",
      "One-stroke penalty on you; play as it lies",
    ],
    correct: 0,
    rule: "Rule 11.1a",
    explanation:
      "Under Rule 11.1a, if your ball in motion accidentally hits any person, there is no penalty to anyone. The ball is played as it lies. The key word is 'accidentally' — the playing partner did not deliberately try to deflect the ball.",
    tags: ["ball in motion", "putting green", "outside influence", "stroke play"],
  },
  {
    id: "gen_b74",
    category: "PLAYING_BALL",
    tier: "official",
    text: "Two balls are rolling on the putting green at the same time after being putted and they collide. Neither player deliberately caused the collision. What is the ruling under the 2026 clarification?",
    choices: [
      "No penalty to either player; each ball is played from where it comes to rest",
      "No penalty; both players must replay their strokes from the original spots",
      "Both players get a one-stroke penalty and replay",
      "No penalty; only the player who putted second must replay",
    ],
    correct: 1,
    rule: "Clarification 11.1b(2)/1",
    explanation:
      "Under the January 2026 Clarification 11.1b(2)/1, a ball in motion on the putting green is treated as a movable obstruction. When a ball played from the putting green accidentally hits another ball in motion on the putting green, the player must replay the stroke. Since both balls were played from the putting green and both hit each other while in motion, both players must replay their strokes from the original spots. There is no penalty.",
    tags: ["ball in motion", "putting green", "replay stroke", "2026 clarification"],
  },
  {
    id: "gen_b75",
    category: "PLAYING_BALL",
    tier: "competitor",
    text: "In match play, your opponent putts and the ball is rolling toward the hole. You deliberately step on it to stop it because you think it will go in. What happens?",
    choices: [
      "You lose the hole for deliberately deflecting your opponent's ball in motion",
      "Two-stroke penalty on you; the putt counts",
      "Your opponent's putt is considered holed automatically",
      "Both of you receive a one-stroke penalty",
    ],
    correct: 0,
    rule: "Rule 11.2c, Rule 1.2a",
    explanation:
      "When you deliberately deflect or stop your opponent's ball in motion in match play, the general penalty applies to you — which in match play means loss of hole. Additionally, Rule 1.2a may apply for serious misconduct, potentially resulting in disqualification.",
    tags: ["match play", "opponent", "deliberate deflection", "ball in motion", "penalty"],
  },
];
