import { Scenario } from "@/types";

export const SCENARIOS_BATCH_6: Scenario[] = [
  // =====================================================================
  // FUNDAMENTALS (Rules 3–4) — 93 deep edge-case scenarios
  // Tier distribution: 31 weekend, 33 competitor, 29 official
  // Rule 3 (The Competition): 40 scenarios
  // Rule 4 (The Player's Equipment): 53 scenarios
  // =====================================================================

  // =====================================================================
  // RULE 3 — THE COMPETITION (40 scenarios)
  // =====================================================================

  // --- Rule 3.1: Components of a Round ---

  {
    id: "b6_001",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In stroke play, what must a player do on every hole to have a valid score?",
    choices: [
      "Hole out — the ball must come to rest in the hole after a stroke",
      "Record a score within double par",
      "Complete the hole within the pace-of-play time limit",
      "Get their marker's approval on the score before leaving the green",
    ],
    correct: 0,
    rule: "Rule 3.3c",
    explanation:
      "Under Rule 3.3c, in stroke play a player must hole out on each hole. If the player does not hole out and does not correct the mistake before making a stroke to begin another hole (or, on the final hole, before returning the scorecard), the player is disqualified.",
    tags: ["stroke play", "hole out", "valid score", "disqualification"],
  },
  {
    id: "b6_002",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In stroke play, you complete the 9th hole but realize you need to go back and replay the 7th hole because you think you played from a wrong place. What should you do?",
    choices: [
      "Continue your round in the correct order — you cannot go back and replay a hole already completed",
      "Go back and replay the 7th hole, adding two penalty strokes",
      "Ask the Committee for permission to replay the 7th hole",
      "Disqualify yourself for the wrong-place error",
    ],
    correct: 0,
    rule: "Rule 3.1",
    explanation:
      "Under Rule 3.1, a round consists of 18 (or fewer) holes played in the order set by the Committee. Once you have completed a hole and started the next, you cannot go back and replay it. If you played from a wrong place, the penalty was applied at the time of the breach; you must continue in order.",
    tags: ["round", "order of play", "stroke play", "wrong place"],
  },
  {
    id: "b6_003",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In stroke play, you fail to hole out on the 14th hole (you pick up your ball in frustration). You then realize your mistake on the 15th tee. Can you go back and hole out on the 14th?",
    choices: [
      "Yes — you must correct the error before making a stroke on the 15th hole or you will be disqualified; go back and hole out with a penalty",
      "No — once you have left the green you cannot go back",
      "Yes — but only with Committee permission",
      "No — you are already disqualified for picking up",
    ],
    correct: 0,
    rule: "Rule 3.3c",
    explanation:
      "Under Rule 3.3c, if a player fails to hole out and the error is discovered before the player makes a stroke to begin another hole, the player must go back and hole out, with the general penalty added. If the player does not correct the error before playing from the next tee, or on the final hole before returning the scorecard, the player is disqualified.",
    tags: ["stroke play", "hole out", "correction", "disqualification"],
  },
  {
    id: "b6_004",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "You are playing a casual 18-hole round. After the 16th hole, you and your playing partners agree to skip the 17th and go straight to the 18th because it is getting dark. Have you completed a valid round?",
    choices: [
      "No — you must play all holes in the order set by the Committee to complete a valid round",
      "Yes — as long as you play 17 of 18 holes, it counts",
      "Yes — all players agreed so it is valid",
      "Only if you record a par for the 17th hole",
    ],
    correct: 0,
    rule: "Rule 3.1",
    explanation:
      "Under Rule 3.1, a round consists of 18 holes played in the order set by the Committee. Skipping a hole means you have not completed a valid round. In a competition, this would result in disqualification.",
    tags: ["round", "order of play", "18 holes", "completing round"],
  },

  // --- Rule 3.2: Match Play ---

  {
    id: "b6_005",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In match play, you and your opponent both make a 5 on a par-4 hole. What is the result of that hole?",
    choices: [
      "The hole is halved — both players scored the same",
      "You both lose the hole because you were over par",
      "The hole is carried over to the next hole",
      "The player who was away first wins the hole",
    ],
    correct: 0,
    rule: "Rule 3.2a(1)",
    explanation:
      "Under Rule 3.2a, a hole is halved when both players complete the hole in the same number of strokes (including any penalty strokes). The actual score relative to par is irrelevant — only the comparison between the two players matters.",
    tags: ["match play", "halved", "scoring", "result of hole"],
  },
  {
    id: "b6_006",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In match play, you are 3 up with 3 holes to play. You halve the 16th hole. What is the status of the match?",
    choices: [
      "You win the match 3 and 2 — you lead by more holes than remain to be played",
      "You are still 3 up with 2 to play and must continue",
      "The match is tied and goes to extra holes",
      "You win 3 up after 16 holes",
    ],
    correct: 0,
    rule: "Rule 3.2a(2)",
    explanation:
      "Under Rule 3.2a(2), a match is won when one player leads by more holes than remain to be played. After halving the 16th, you are still 3 up with 2 holes remaining. Since 3 is more than 2, the match is over. You win 3 and 2.",
    tags: ["match play", "winning match", "3 and 2", "dormie"],
  },
  {
    id: "b6_007",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In match play, the match is all square (tied) after 18 holes. What happens next?",
    choices: [
      "The match continues hole by hole until one player wins a hole",
      "The match is declared a draw",
      "Both players share the point",
      "The player with the lower total stroke count wins",
    ],
    correct: 0,
    rule: "Rule 3.2a(4)",
    explanation:
      "Under Rule 3.2a(4), if a match is all square after the last hole, the match is extended one hole at a time until there is a winner. This is commonly called a 'sudden death' playoff. The Committee determines which hole(s) to play.",
    tags: ["match play", "tied", "extra holes", "all square"],
  },
  {
    id: "b6_008",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In match play, your opponent's ball is sitting 2 feet from the hole. Before your opponent can address the ball, you say 'That's good.' Your opponent wants to putt it anyway. Can they decline the concession?",
    choices: [
      "No — a concession cannot be declined or withdrawn once made; the ball is considered holed",
      "Yes — the player can always choose to putt out",
      "Yes — a concession only applies if the opponent agrees",
      "The opponent can decline, but only with the Committee's approval",
    ],
    correct: 0,
    rule: "Rule 3.2b(1)",
    explanation:
      "Under Rule 3.2b(1), once a concession is made, it is final. It cannot be declined by the opponent or withdrawn by the player who made it. The opponent's next stroke, the hole, or the match (whichever was conceded) is immediately settled.",
    tags: ["match play", "concession", "cannot decline", "final"],
  },
  {
    id: "b6_009",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In match play, you concede your opponent's next stroke while they are in the middle of their backswing. Your opponent completes the stroke and the ball goes into a bunker. What is the ruling?",
    choices: [
      "The concession stands — the ball was already considered holed before the stroke was completed",
      "The concession is void because the opponent had already started the stroke",
      "The opponent can choose between the concession and the result of the stroke",
      "The stroke counts and the concession is cancelled",
    ],
    correct: 0,
    rule: "Rule 3.2b(1)",
    explanation:
      "Under Rule 3.2b(1), a concession is final once made, regardless of timing. Even though the opponent was mid-swing, the concession took effect immediately when it was communicated. The subsequent stroke is irrelevant — the ball was already considered holed with the next stroke at the moment the concession was given.",
    tags: ["match play", "concession", "timing", "mid-swing"],
  },
  {
    id: "b6_010",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In match play, you concede the match to your opponent on the 15th hole because you feel you cannot win. After the round, you realize you miscounted and were actually only 1 down, not 4 down. Can you withdraw the concession?",
    choices: [
      "No — a concession of a match is final and cannot be withdrawn, even if based on a mistake",
      "Yes — the concession was based on a factual error",
      "Yes — both players must agree for a match concession to stand",
      "The Committee can reverse it if the error is proven",
    ],
    correct: 0,
    rule: "Rule 3.2b(3)",
    explanation:
      "Under Rule 3.2b, a concession of a match is final once made. It cannot be withdrawn even if the player made it based on a misunderstanding of the match status. The conceding player bears the responsibility for knowing the state of the match.",
    tags: ["match play", "concession", "match concession", "final", "mistake"],
  },
  {
    id: "b6_011",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In match play, you concede your opponent's next putt. Your opponent, not hearing the concession, putts and misses. They then pick up and say they'll take the concession. What score does your opponent get?",
    choices: [
      "The score at the time of concession — the putt was already conceded before the stroke was made",
      "The score including the missed putt, since they chose to putt",
      "The score including the missed putt plus a penalty stroke",
      "The hole must be replayed",
    ],
    correct: 0,
    rule: "Rule 3.2b(1)",
    explanation:
      "Under Rule 3.2b(1), a concession is final once made. Even though the opponent did not hear it and putted (and missed), the concession was already in effect. The ball was considered holed at the time of the concession, and the subsequent stroke and miss are irrelevant.",
    tags: ["match play", "concession", "not heard", "final"],
  },
  {
    id: "b6_012",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In match play, can you concede a hole to your opponent before anyone has teed off on that hole?",
    choices: [
      "Yes — you can concede a hole at any time before the result of the hole is decided",
      "No — you must at least tee off before conceding",
      "Only if you are already behind in the match",
      "Only with the opponent's agreement",
    ],
    correct: 0,
    rule: "Rule 3.2b(2)",
    explanation:
      "Under Rule 3.2b(2), a player may concede a hole at any time before the result of the hole is decided, including before either player has teed off. This might be done for strategic reasons or to speed up play.",
    tags: ["match play", "concession", "concede hole", "before tee off"],
  },
  {
    id: "b6_013",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In a handicap match, Player A receives 2 strokes on the 5th hole (stroke index 1) per the handicap allocation. Player A makes a gross 5 on the par 4. Player B makes a 4. Who wins the hole?",
    choices: [
      "Player A wins — their net score is 3 (5 minus 2 strokes), which is better than Player B's 4",
      "Player B wins — 4 beats 5 regardless of handicap",
      "The hole is halved — net 3 vs. 4 is not how handicaps work",
      "Player A wins with net 4, halving the hole (not winning it)",
    ],
    correct: 0,
    rule: "Rule 3.2c",
    explanation:
      "Under Rule 3.2c, when handicap strokes are given, the net score determines the result of each hole. Player A's gross 5 minus 2 handicap strokes equals a net 3, which beats Player B's 4. Player A wins the hole.",
    tags: ["match play", "handicap", "net score", "stroke allocation"],
  },
  {
    id: "b6_014",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In match play, Player A gives Player B the wrong handicap before the match starts. They discover the error on the 10th tee. Player B had received 1 fewer stroke than entitled on holes already played. What happens?",
    choices: [
      "If no hole result was affected, the correct handicap applies going forward; if a hole result was affected, the match stands if the error was not discovered in time",
      "The match is restarted with the correct handicap",
      "Player A is disqualified for providing the wrong handicap",
      "All holes played with the wrong handicap are halved",
    ],
    correct: 0,
    rule: "Rule 3.2c(1)",
    explanation:
      "Under Rule 3.2c(1), if a player gives the wrong handicap before or during a match and this affects the number of strokes given or received, the correction depends on when the error is discovered. If a hole result was affected and the claim is made in time (before either player makes a stroke on the next tee), the hole result is corrected. Otherwise, the result stands and the correct handicap is applied to remaining holes.",
    tags: ["match play", "handicap", "wrong handicap", "correction"],
  },
  {
    id: "b6_015",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In match play, you notice your opponent has grounded their club in a bunker before making a stroke. When must you raise this issue?",
    choices: [
      "You should make the claim before either player makes a stroke on the next tee (or before results are final on the last hole)",
      "You can raise it at any time during the round",
      "You can raise it after the round is over",
      "Only the Committee can raise rule breaches in match play",
    ],
    correct: 0,
    rule: "Rule 3.2d(2)",
    explanation:
      "Under Rule 3.2d(2), in match play, to protect your rights, you should promptly make your opponent or the Committee aware of any breach. If you do not do so in a timely manner — generally before either player makes a stroke on the next tee (or for the last hole, before results are final) — you may lose the right to the claim.",
    tags: ["match play", "claim", "timely request", "opponent breach"],
  },
  {
    id: "b6_016",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In match play, your opponent makes a 4 on a hole. You have a putt for 4 and your opponent concedes it. Later, you both realize your opponent actually scored a 5, not a 4. You would have won the hole. What is the ruling?",
    choices: [
      "The concession stands — you halved the hole; the wrong information about the score does not change the concession",
      "You win the hole because your opponent's actual score was 5",
      "The hole is replayed",
      "The Committee adjusts the match score retroactively",
    ],
    correct: 1,
    rule: "Rule 3.2d(1)",
    explanation:
      "Under Rule 3.2d(1), a player is expected to tell the opponent the correct number of strokes taken. If the opponent gives wrong information about their score (saying 4 when it was 5), and this is discovered before the result of the match is final, the hole result is corrected. Since you actually made 4 and your opponent made 5, you win the hole. The concession of your stroke means you scored 4, but the opponent's score is corrected to 5.",
    tags: ["match play", "wrong information", "score correction", "concession"],
  },
  {
    id: "b6_017",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In match play, you make a stroke from the teeing area. Your opponent says 'nice shot' but does not concede anything. You pick up your ball thinking the hole was conceded. What is the ruling?",
    choices: [
      "You lose the hole — 'nice shot' is not a concession; you lifted your ball in play without authority",
      "The hole is conceded because 'nice shot' implies concession",
      "No penalty — replace the ball and continue",
      "The hole is halved",
    ],
    correct: 0,
    rule: "Rule 3.2b(1)",
    explanation:
      "Under Rule 3.2b(1), a concession must be clearly communicated — by words or by an action that clearly shows the intent to concede. A casual comment like 'nice shot' does not constitute a concession. By lifting the ball without a concession, the player has breached the Rules and loses the hole.",
    tags: ["match play", "concession", "ambiguous", "not a concession"],
  },
  {
    id: "b6_018",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In match play, your opponent is about to putt for par. You say 'Pick it up, that's good.' Your opponent says 'I'd rather putt it' and holes the putt. What is the result of the hole?",
    choices: [
      "The concession already gave your opponent a par — the putt was irrelevant because a concession cannot be declined",
      "The opponent holed the putt so the score is the putted score",
      "The opponent can choose between the concession score and the putted score",
      "The concession is cancelled because the opponent chose to putt",
    ],
    correct: 0,
    rule: "Rule 3.2b(1)",
    explanation:
      "Under Rule 3.2b(1), a concession is final and cannot be declined or withdrawn. Once you said 'pick it up, that's good,' the next stroke was conceded and the ball was considered holed. The opponent's subsequent putt is irrelevant — the concession already settled the score for the hole.",
    tags: ["match play", "concession", "cannot decline", "putt anyway"],
  },
  {
    id: "b6_019",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In match play, you ask your opponent what club they used on the previous shot. Your opponent tells you a 7-iron, but actually used a 6-iron. You discover this on the next hole. What happens?",
    choices: [
      "Your opponent loses the previous hole for giving deliberately misleading information",
      "No penalty — players are not required to share club information",
      "Two-stroke penalty applied to your opponent",
      "The hole is replayed",
    ],
    correct: 0,
    rule: "Rule 3.2d(1)",
    explanation:
      "Under Rule 3.2d(1), a player must not give deliberately misleading information to the opponent. If asked what club was used, a player may decline to answer, but must not give a deliberately wrong answer. Giving false club information constitutes giving wrong information, and the penalty is loss of hole if the claim is made in time.",
    tags: ["match play", "wrong information", "club selection", "deliberately misleading"],
  },

  // --- Rule 3.3: Stroke Play ---

  {
    id: "b6_020",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In stroke play, who is responsible for adding up the total score on your scorecard?",
    choices: [
      "The Committee — the player is only responsible for the accuracy of each individual hole score",
      "The player — you must verify your total before submitting",
      "The marker — they are responsible for all scoring",
      "It is a shared responsibility between the player and marker",
    ],
    correct: 0,
    rule: "Rule 3.3b(2)",
    explanation:
      "Under Rule 3.3b(2), the Committee is responsible for adding up the hole scores and applying handicap strokes in a handicap competition. The player is only responsible for ensuring that each individual hole score is correct and that the scorecard is certified and returned promptly.",
    tags: ["stroke play", "scorecard", "total score", "committee responsibility"],
  },
  {
    id: "b6_021",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In stroke play, you return your scorecard showing a 5 on the 7th hole. You actually made a 4. What is the ruling?",
    choices: [
      "The higher score of 5 stands — a score higher than actually taken is not corrected",
      "The score is corrected to 4 by the Committee",
      "You are disqualified for a wrong score",
      "Two-stroke penalty and the score is corrected to 4",
    ],
    correct: 0,
    rule: "Rule 3.3b(3)",
    explanation:
      "Under Rule 3.3b(3), if a player returns a score for a hole that is higher than actually taken, the higher score stands. Only a score that is lower than actually taken results in disqualification. The Committee does not correct an erroneously high score.",
    tags: ["stroke play", "scorecard", "higher score", "wrong score"],
  },
  {
    id: "b6_022",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In stroke play, you return your scorecard showing a 4 on the 12th hole. You actually made a 5. What is the ruling?",
    choices: [
      "You are disqualified — a score lower than actually taken results in DQ",
      "The lower score of 4 stands",
      "Two-stroke penalty and the score is corrected to 5",
      "The Committee corrects the score to 5 with no penalty",
    ],
    correct: 0,
    rule: "Rule 3.3b(3)",
    explanation:
      "Under Rule 3.3b(3), if a player returns a score for any hole that is lower than actually taken (including when penalty strokes that the player did not know about are left out), the player is disqualified. The integrity of stroke play depends on accurate scorecards.",
    tags: ["stroke play", "scorecard", "lower score", "disqualification"],
  },
  {
    id: "b6_023",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In stroke play, you incur a two-stroke penalty on the 8th hole but are unaware of it. You record a 5 for that hole (which would be 7 with the penalty). After the round, the Committee discovers the breach. What happens?",
    choices: [
      "You are disqualified — the returned score for that hole was lower than actually taken",
      "The Committee adds the two penalty strokes to your score; you are not disqualified",
      "No penalty — you did not know about the breach",
      "Two additional penalty strokes for the scorecard error, on top of the original two",
    ],
    correct: 1,
    rule: "Rule 3.3b(3), Exception",
    explanation:
      "Under the Exception to Rule 3.3b(3), if penalty strokes were not included in a player's score because the player did not know about them before returning the scorecard, the player is not disqualified. Instead, the Committee revises the score by adding the missing penalty strokes. This Exception was added in the 2023 Rules to prevent the harsh outcome of disqualification for unknowing breaches. If the player HAD known about the penalty and still returned a lower score, disqualification would apply.",
    tags: ["stroke play", "scorecard", "unknown penalty", "disqualification"],
  },
  {
    id: "b6_024",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In stroke play, you return your scorecard without your marker's signature. You realize this 10 minutes later, before the results are finalized. What happens?",
    choices: [
      "You may still have the marker certify the scorecard if results have not been finalized",
      "You are disqualified — the scorecard must be signed before leaving the scoring area",
      "The Committee can waive the signature requirement",
      "One-stroke penalty and the scorecard is accepted",
    ],
    correct: 0,
    rule: "Rule 3.3b(2)",
    explanation:
      "Under Rule 3.3b(2), the player must ensure the marker certifies the hole scores on the scorecard. If the scorecard is returned without the marker's certification, the player is disqualified — but only when the competition results are final. If results have not been finalized, the player may still have the marker certify it.",
    tags: ["stroke play", "scorecard", "marker signature", "certification"],
  },
  {
    id: "b6_025",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In stroke play, what does your marker do?",
    choices: [
      "Records your scores on the scorecard, certifies the hole scores, and is typically another player in your group",
      "Makes rulings on any disputes during the round",
      "Enforces the pace of play policy",
      "Watches every stroke you make and verifies club conformance",
    ],
    correct: 0,
    rule: "Rule 3.3b(1)",
    explanation:
      "Under Rule 3.3b(1), the marker is responsible for certifying the player's hole scores on the scorecard. The marker is typically another player in the group. The marker does not make rulings (that is the Committee's role) and does not need to watch every stroke — they record what they observe and what the player reports.",
    tags: ["stroke play", "marker", "scorecard"],
  },
  {
    id: "b6_026",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In stroke play, can you have more than one marker during a round?",
    choices: [
      "Yes — the Committee may assign a new marker or allow the player to change markers during the round",
      "No — the same marker must sign for every hole",
      "Only if the original marker becomes ill or cannot continue",
      "Only with the approval of all other players in the group",
    ],
    correct: 0,
    rule: "Rule 3.3b(1)",
    explanation:
      "Under Rule 3.3b(1), the Committee assigns (or approves) who acts as a marker. A different marker can be assigned during the round by the Committee. The scorecard must show which holes each marker has certified.",
    tags: ["stroke play", "marker", "multiple markers", "committee"],
  },
  {
    id: "b6_027",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In stroke play, you return your scorecard with the correct hole-by-hole scores but the wrong total. The actual total should be 78, but you wrote 76. What is the ruling?",
    choices: [
      "No penalty — the Committee is responsible for adding up the total and will correct it to 78",
      "You are disqualified for returning an incorrect scorecard",
      "Two-stroke penalty for a scorecard error",
      "The lower total of 76 stands since you signed it",
    ],
    correct: 0,
    rule: "Rule 3.3b(2)",
    explanation:
      "Under Rule 3.3b(2), the Committee is responsible for adding up the hole scores on the scorecard. If the individual hole scores are correct, an error in the total is simply corrected by the Committee with no penalty to the player.",
    tags: ["stroke play", "scorecard", "wrong total", "committee adds scores"],
  },
  {
    id: "b6_028",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In stroke play, you sign your scorecard in the scoring area but your marker is not present to sign. You leave the scoring area to find them. Is this acceptable?",
    choices: [
      "Yes — you may leave the scoring area to get the marker's certification, as long as you do not unreasonably delay returning the scorecard",
      "No — if the marker is not present to sign, you are disqualified",
      "Only with Committee permission",
      "Only if the marker signs within 5 minutes",
    ],
    correct: 0,
    rule: "Rule 3.3b(2)",
    explanation:
      "Under Rule 3.3b(2), the player must have the marker certify the hole scores. While it is preferable to do this in the scoring area, the player is not automatically disqualified if the marker is absent — the player should make reasonable efforts to obtain the certification before formally returning the scorecard.",
    tags: ["stroke play", "scorecard", "marker certification", "scoring area"],
  },
  {
    id: "b6_029",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In stroke play, you finish your round and sign your scorecard. On the way to the car, you realize you forgot to include a penalty stroke on the 14th hole. Can you go back and correct it?",
    choices: [
      "No — once you have returned your scorecard, it cannot be changed; you are disqualified for a score lower than taken",
      "Yes — you can always correct your scorecard within 30 minutes",
      "Yes — the Committee will add the penalty stroke for you",
      "Only if you notify the Committee before leaving the property",
    ],
    correct: 0,
    rule: "Rule 3.3b(2)",
    explanation:
      "Under Rule 3.3b(2), once the player has returned the scorecard to the Committee, it cannot be changed. If a hole score is lower than actually taken (because the penalty was not included), the player is disqualified under Rule 3.3b(3).",
    tags: ["stroke play", "scorecard", "returned scorecard", "cannot change"],
  },
  {
    id: "b6_030",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In stroke play, your marker refuses to sign your scorecard because of a disagreement about your score on one hole. What should you do?",
    choices: [
      "Ask the Committee to validate your score and assign or act as an alternative marker",
      "Sign the scorecard yourself as both player and marker",
      "Have another player in the group sign as marker",
      "You are disqualified if the marker will not sign",
    ],
    correct: 0,
    rule: "Rule 3.3b(2)",
    explanation:
      "Under Rule 3.3b(2), if the marker refuses to certify the scorecard, the player should refer the matter to the Committee. The Committee can get the facts from anyone present and can accept the scorecard with appropriate evidence, or assign another person to act as marker for those holes.",
    tags: ["stroke play", "scorecard", "marker refuses", "committee"],
  },
  {
    id: "b6_031",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In stroke play, how is the winner determined?",
    choices: [
      "The player who completes all rounds in the fewest total strokes (including penalty strokes) wins",
      "The player with the most birdies wins",
      "The player with the best scoring average per round wins",
      "The player with the fewest bogeys wins",
    ],
    correct: 0,
    rule: "Rule 3.3a",
    explanation:
      "Under Rule 3.3a, the winner in stroke play is the player who completes all rounds in the fewest total strokes, including any penalty strokes. In a handicap competition, the winner is determined by the fewest net strokes.",
    tags: ["stroke play", "winner", "total strokes", "scoring"],
  },
  {
    id: "b6_032",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In stroke play, after returning your scorecard, you discover that you failed to include a penalty that you did not know about at the time. A new Rule interpretation, published after the round, confirms the penalty. What is the ruling?",
    choices: [
      "No disqualification — the player is not disqualified when a wrong score results from not knowing a penalty that was later discovered through new information the player could not reasonably have known",
      "You are disqualified — the scorecard had a lower score than taken",
      "Two-stroke penalty is added, but no disqualification",
      "The result stands as submitted with no changes",
    ],
    correct: 0,
    rule: "Rule 3.3b(3), Exception",
    explanation:
      "Under the Exception to Rule 3.3b(3), a player is not disqualified if they return a wrong score for a hole because of failure to include penalty strokes that the player did not know about before returning the scorecard, provided the player could not reasonably have known about the penalty. In this case, the Committee adds the penalty strokes to the score rather than disqualifying the player.",
    tags: ["stroke play", "scorecard", "unknown penalty", "exception to DQ"],
  },
  {
    id: "b6_033",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In stroke play, Player A's scorecard is signed by a marker, but the marker wrote the wrong name on the card (wrote 'Player B' instead of 'Player A'). The hole scores are correct and the player certifies the card. What is the ruling?",
    choices: [
      "No penalty — the scorecard is valid as long as the hole scores are correct, the marker has certified it, and the player has certified it",
      "Player A is disqualified for an invalid scorecard",
      "Two-stroke penalty for a procedural error",
      "The marker must redo the entire scorecard",
    ],
    correct: 0,
    rule: "Rule 3.3b(2)",
    explanation:
      "Under Rule 3.3b(2), the essential requirements are that the hole scores are correct, the marker certifies them, and the player certifies them. An incorrect name written on the scorecard by the marker is an administrative error that the Committee can correct. It does not invalidate the scorecard.",
    tags: ["stroke play", "scorecard", "wrong name", "administrative error"],
  },

  // --- More Rule 3 edge cases ---

  {
    id: "b6_034",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In match play, you win the first three holes. Your opponent then wins the next three holes. What is the match status after 6 holes?",
    choices: [
      "The match is all square (tied)",
      "You are still 3 up because you won first",
      "Your opponent is 3 up because they won the most recent holes",
      "The match restarts from even",
    ],
    correct: 0,
    rule: "Rule 3.2a(1)",
    explanation:
      "Under Rule 3.2a, each hole won or lost changes the match status by one. You went to 3 up after 3 holes, then your opponent won three consecutive holes (3 up, 2 up, 1 up, all square), bringing the match back to all square after 6 holes.",
    tags: ["match play", "match status", "all square", "counting holes"],
  },
  {
    id: "b6_035",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In match play, your opponent tells you their score on a hole was 5. You halve the hole. On the next tee, you learn your opponent actually made a 6. Can you claim the hole?",
    choices: [
      "Yes — but only if you make the claim before either player makes a stroke on the next hole; since you just arrived at the next tee, you can still claim",
      "No — the hole result is final once both players leave the green",
      "Yes — you can make a claim at any time during the round",
      "No — only the Committee can correct a wrong score in match play",
    ],
    correct: 0,
    rule: "Rule 3.2d(1)",
    explanation:
      "Under Rule 3.2d(1), players are expected to tell the opponent the correct number of strokes taken. If an opponent gives wrong information and the player later learns the truth, they may make a timely request to the Committee. A request is timely if made before either player makes a stroke to begin the next hole (or for the last hole, before results are final).",
    tags: ["match play", "wrong information", "timely claim", "score dispute"],
  },
  {
    id: "b6_036",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In match play, you and your opponent both agree that a particular free relief situation allows a drop. After the hole is completed and you won it, a referee tells you the drop was actually not permitted. What happens?",
    choices: [
      "The result stands — if both players agreed on how to apply the Rules, even if wrong, the result of the hole is not changed unless the Committee decides otherwise before the result of the match is final",
      "The hole is replayed",
      "You lose the hole because you benefited from the wrong ruling",
      "Both players are penalized for incorrect application of the Rules",
    ],
    correct: 0,
    rule: "Rule 3.2d(3)",
    explanation:
      "Under Rule 3.2d(3), in match play, if the players agree to settle a Rules issue in a way that turns out to be wrong, the agreed outcome stands — unless the Committee decides otherwise before the result of the match is final. Players cannot knowingly agree to ignore a Rule or penalty.",
    tags: ["match play", "agreed ruling", "wrong ruling", "result stands"],
  },
  {
    id: "b6_037",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In match play, you and your opponent knowingly agree to ignore a penalty so that one of you can win a hole. What is the ruling?",
    choices: [
      "Both players are disqualified for deliberately agreeing to ignore a known Rule",
      "Only the player who benefited is disqualified",
      "No penalty — players can settle disputes between themselves in match play",
      "The hole is replayed with the correct ruling",
    ],
    correct: 0,
    rule: "Rule 3.2d(3)",
    explanation:
      "Under Rule 3.2d(3), if the players knowingly agree to ignore any Rule or penalty, both are disqualified. This is different from unknowingly agreeing on a wrong application of the Rules (which is allowed to stand). The distinction is whether the players knew they were ignoring a Rule.",
    tags: ["match play", "ignore rule", "disqualification", "agreement"],
  },
  {
    id: "b6_038",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In stroke play, you hole out in 5 strokes. Your marker records a 4. You check the scorecard, do not notice the error, certify it, and turn it in. The error is discovered after results are final. What is the ruling?",
    choices: [
      "You are disqualified — you returned a score lower than actually taken",
      "The Committee corrects the score to 5 with no penalty",
      "Two-stroke penalty and the score is corrected to 5",
      "The result stands as 4 since the scorecard was certified",
    ],
    correct: 0,
    rule: "Rule 3.3b(3)",
    explanation:
      "Under Rule 3.3b(3), the player is responsible for the correctness of each hole score. If the returned score for any hole is lower than actually taken, the player is disqualified — regardless of whether the error was the marker's or the player's. The player bears ultimate responsibility for checking the scorecard before certifying and returning it.",
    tags: ["stroke play", "scorecard", "marker error", "lower score", "disqualification"],
  },
  {
    id: "b6_039",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "In stroke play, can you act as the marker for more than one player in your group?",
    choices: [
      "Yes — a marker may keep score for more than one player if authorized by the Committee",
      "No — each player must have a different marker",
      "Only if the group has fewer than four players",
      "Only in casual rounds, not in official competitions",
    ],
    correct: 0,
    rule: "Rule 3.3b(1)",
    explanation:
      "Under Rule 3.3b(1), the Committee designates who acts as each player's marker. There is no prohibition against one person marking for multiple players. In practice, this often happens in two-ball groups or when the Committee assigns a marker.",
    tags: ["stroke play", "marker", "multiple players", "committee"],
  },
  {
    id: "b6_040",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In match play, after completing the 18th hole, you believe the match is all square and agree with your opponent to play extra holes. You then win the 19th hole. Later, it is discovered you had actually won the match on the 18th, 1 up. What is the result?",
    choices: [
      "You won the match on the 18th hole, 1 up — the result of the 19th hole is irrelevant since the match was already over",
      "You won on the 19th hole since that is what was played",
      "The match must be replayed from the 18th",
      "The Committee decides whether the 18th or 19th hole result counts",
    ],
    correct: 0,
    rule: "Rule 3.2a(5)",
    explanation:
      "Under Rule 3.2a, the match ends when one player wins. If it was later discovered that a player had already won the match at an earlier point, the match result is corrected to reflect the actual outcome. Playing additional holes when the match was already decided has no effect on the result.",
    tags: ["match play", "match already won", "extra holes", "correction"],
  },

  // =====================================================================
  // RULE 4 — THE PLAYER'S EQUIPMENT (53 scenarios)
  // =====================================================================

  // --- Rule 4.1: Clubs ---

  {
    id: "b6_041",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "You start your round with 14 clubs but break your 7-iron on the 5th hole during a normal swing. Can you replace it?",
    choices: [
      "Yes — you may replace a club damaged during the round by normal use, as long as it does not unreasonably delay play",
      "No — you must finish the round with 13 clubs",
      "Only if you can get a replacement within 5 minutes",
      "Only with Committee permission",
    ],
    correct: 0,
    rule: "Rule 4.1b(3)",
    explanation:
      "Under Rule 4.1b(3), if a club is damaged during the round by the player or caddie (including normal use), the player may replace it with any other club, provided doing so does not unreasonably delay play and the player did not damage it through abuse.",
    tags: ["clubs", "damaged club", "replacement", "normal use"],
  },
  {
    id: "b6_042",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "You slam your putter into the ground in frustration and bend the shaft. Can you replace the putter?",
    choices: [
      "No — a club damaged through abuse cannot be replaced; you may continue using it in its damaged state or have it repaired",
      "Yes — any damaged club can be replaced regardless of how it was damaged",
      "Only if you receive a two-stroke penalty",
      "Only if the Committee grants permission",
    ],
    correct: 0,
    rule: "Rule 4.1b(3)",
    explanation:
      "Under Rule 4.1b(3), a player may replace a club damaged during the round ONLY if it was damaged during the normal course of play, not through abuse. When damage is caused by abuse (slamming, throwing, etc.), the player cannot replace it. They may continue using it in its damaged state or have it repaired.",
    tags: ["clubs", "damaged club", "abuse", "no replacement"],
  },
  {
    id: "b6_043",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "You discover on the 3rd tee that you have 15 clubs in your bag. What is the penalty in stroke play?",
    choices: [
      "Two-stroke penalty per hole where the breach occurred, maximum of four penalty strokes; declare the excess club out of play immediately",
      "You are disqualified",
      "One-stroke penalty per hole, no maximum",
      "No penalty — just remove the extra club",
    ],
    correct: 0,
    rule: "Rule 4.1b(1)",
    explanation:
      "Under Rule 4.1b(1), in stroke play, the penalty for carrying more than 14 clubs is two strokes for each hole at which a breach occurred, with a maximum penalty of four strokes (two holes). The player must immediately take the excess club out of play by declaring it.",
    tags: ["clubs", "15 clubs", "excess clubs", "stroke play", "penalty"],
  },
  {
    id: "b6_044",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "You start with 13 clubs and want to add a club during the round. Your friend, who is playing in the same competition, offers to lend you one of their clubs. Can you accept it?",
    choices: [
      "No — you cannot add a club that is being used by (selected for play by) another person playing on the course",
      "Yes — you can borrow any club from anyone as long as you stay at 14",
      "Yes — but only for one hole, then you must return it",
      "Only if the Committee approves the loan",
    ],
    correct: 0,
    rule: "Rule 4.1b(1)",
    explanation:
      "Under Rule 4.1b(1), a player may add clubs during a round up to the 14-club limit, but must not add a club that has been selected for play by any other person who is playing on the course. You can add a club from someone not playing, your car, the pro shop, etc., but not from another player's bag.",
    tags: ["clubs", "adding clubs", "sharing clubs", "14 club limit"],
  },
  {
    id: "b6_045",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In a foursomes (alternate shot) event, Partner A has 10 clubs and Partner B has 4 clubs. Can they share the clubs between them?",
    choices: [
      "Yes — partners may share clubs provided the total number between them does not exceed 14; 10 + 4 = 14, so this is allowed",
      "No — each player must carry their own separate set of clubs",
      "Yes — but only if each partner carries at least 7 clubs",
      "Only with Committee approval",
    ],
    correct: 0,
    rule: "Rule 4.1b(2)",
    explanation:
      "Under Rule 4.1b(2), in a partnership form of play (like four-ball or foursomes), partners may share clubs, provided that the total number of clubs between them is not more than 14. With 10 and 4, the total is exactly 14, so sharing is permitted. Either partner may use any of the 14 clubs.",
    tags: ["clubs", "sharing clubs", "foursomes", "partnership", "14 club limit"],
  },
  {
    id: "b6_046",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "In a four-ball stroke play event, Partner A has 10 clubs and Partner B has 8 clubs. They want to share clubs. Is this allowed?",
    choices: [
      "No — partners may share clubs only if the total does not exceed 14; with 18 clubs total, they have too many and receive the excess club penalty",
      "Yes — each partner can have up to 14, so 18 total is fine",
      "Yes — sharing is always allowed in four-ball",
      "Only if they declare 4 clubs out of play before starting",
    ],
    correct: 0,
    rule: "Rule 4.1b(2)",
    explanation:
      "Under Rule 4.1b(2), when partners share clubs, the total number must not exceed 14. With 10 + 8 = 18, they exceed the limit by 4 clubs. The excess clubs penalty applies (two strokes per hole with the breach, maximum four strokes in stroke play). They must immediately declare the excess clubs out of play.",
    tags: ["clubs", "sharing clubs", "four-ball", "excess clubs", "penalty"],
  },
  {
    id: "b6_047",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "Before the round, you notice that the grip on your driver is loose. Can you repair it before the round starts?",
    choices: [
      "Yes — you may repair or replace any club before the round begins without restriction",
      "No — you must play with clubs in their current condition",
      "Only if the Committee grants permission",
      "Only if you do not delay the start of the round",
    ],
    correct: 0,
    rule: "Rule 4.1a(1)",
    explanation:
      "Under Rule 4.1a(1), there are no restrictions on repairing, replacing, or modifying clubs before the round begins. The restrictions on club replacement and modification only apply during the round. You can fix, swap, or adjust any clubs before your round starts.",
    tags: ["clubs", "repair", "before round", "equipment"],
  },
  {
    id: "b6_048",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "During the round, the shaft on your 5-iron bends slightly when you lean on it while waiting on the tee. Can you straighten it?",
    choices: [
      "Yes — you may repair a club damaged during the round to restore it as nearly as possible to its condition before the damage, but you must not unreasonably delay play",
      "No — once a club is bent during the round, it must stay that way",
      "Only if the damage was caused during a stroke",
      "Only a certified club repair technician can make repairs during a round",
    ],
    correct: 0,
    rule: "Rule 4.1a(2)",
    explanation:
      "Under Rule 4.1a(2), if a club is damaged during the round (by any cause, including leaning on it), the player may have it repaired or restored to its condition before the damage, as long as doing so does not unreasonably delay play and the player does not change the playing characteristics of the club.",
    tags: ["clubs", "repair during round", "damaged club", "restore"],
  },
  {
    id: "b6_049",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "You start the round with 14 clubs. On the 6th hole, the head of your driver falls off during a practice swing. You cannot repair it. If you replace it, how many clubs will you have?",
    choices: [
      "14 — you may replace the broken driver with another club, keeping the total at 14",
      "15 — the broken driver still counts as a club",
      "13 — you cannot replace a club that broke during a practice swing",
      "14, but only if you discard the broken driver head and shaft",
    ],
    correct: 0,
    rule: "Rule 4.1b(3)",
    explanation:
      "Under Rule 4.1b(3), when replacing a damaged club, the player must take the damaged club out of play. The replacement club takes its place, keeping the total at the 14-club maximum. A practice swing counts as normal use, so the replacement is allowed.",
    tags: ["clubs", "broken club", "replacement", "practice swing", "14 clubs"],
  },
  {
    id: "b6_050",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "During your round, you realize that one of your 14 clubs does not conform to the Equipment Rules (the grooves on your wedge exceed the allowed specifications). What happens?",
    choices: [
      "If the club was non-conforming before the round, you are disqualified; if it became non-conforming through normal wear during the round, you may continue using it",
      "No penalty — the Equipment Rules are only enforced at equipment checks",
      "Two-stroke penalty and you must immediately remove the club",
      "One-stroke penalty for each hole played with the club",
    ],
    correct: 0,
    rule: "Rule 4.1a(1)",
    explanation:
      "Under Rule 4.1a(1), a player must not make a stroke with a club that does not conform to the Equipment Rules. If a club was non-conforming at the start of the round, strokes made with it count but the player is disqualified. However, if a conforming club's characteristics change through normal wear during the round, it remains conforming.",
    tags: ["clubs", "non-conforming", "equipment rules", "disqualification"],
  },
  {
    id: "b6_051",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "During a round, your caddie accidentally drops your bag and one club falls into a pond and cannot be retrieved. Can you replace it?",
    choices: [
      "Yes — you may replace a club that is lost during the round, as long as you do not unreasonably delay play and the club was not lost through abuse",
      "No — you must continue the round with fewer clubs",
      "Only if you can find the exact same model",
      "Only with Committee approval",
    ],
    correct: 0,
    rule: "Rule 4.1b(3)",
    explanation:
      "Under Rule 4.1b(3), if a club is damaged or lost during the round by the player or caddie in the normal course of play (not through abuse), the player may replace it with any club, provided doing so does not unreasonably delay play.",
    tags: ["clubs", "lost club", "replacement", "caddie"],
  },
  {
    id: "b6_052",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "You start with 12 clubs. On the 7th hole, you find a wedge abandoned on the course and add it to your bag. On the 10th hole, you add another club from the pro shop, bringing your total to 14. Is this allowed?",
    choices: [
      "Yes — you may add clubs at any time during the round up to the 14-club limit, as long as you do not select a club from another player on the course and do not unreasonably delay play",
      "No — you can only add one club per round",
      "Only clubs from the pro shop can be added, not abandoned clubs",
      "You may add clubs only between rounds, not during a round",
    ],
    correct: 0,
    rule: "Rule 4.1b(1)",
    explanation:
      "Under Rule 4.1b(1), a player who starts with fewer than 14 clubs may add clubs during the round up to the 14-club limit. The only restrictions are that the club must not be selected for play by another player on the course and the process must not unreasonably delay play. An abandoned club found on the course is not selected for play by anyone.",
    tags: ["clubs", "adding clubs", "14 club limit", "during round"],
  },
  {
    id: "b6_053",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "You declare a club 'out of play' on the 5th hole because you realize you have 15 clubs. Can you later change your mind and declare a different club out of play instead?",
    choices: [
      "No — once a club is declared out of play, the declaration cannot be changed; the club remains out of play for the rest of the round",
      "Yes — you can switch which club is out of play at any time",
      "Yes — but only between holes",
      "Only with Committee approval",
    ],
    correct: 0,
    rule: "Rule 4.1b(1)",
    explanation:
      "Under Rule 4.1b(1), when a player declares a club out of play, that declaration is final for the rest of the round. The player cannot reverse the declaration or substitute a different club as the one taken out of play.",
    tags: ["clubs", "out of play", "declaration", "excess clubs"],
  },
  {
    id: "b6_054",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "Between rounds of a 36-hole competition, can you change the clubs in your bag?",
    choices: [
      "Yes — you may add, remove, or replace any club between rounds without restriction",
      "No — you must use the same clubs for all rounds of a competition",
      "Only if a club was damaged during the previous round",
      "Only with Committee permission",
    ],
    correct: 0,
    rule: "Rule 4.1b(1)",
    explanation:
      "Under Rule 4.1b(1), the 14-club limit and restrictions on adding/replacing clubs apply only during a round. Between rounds, a player may change their club selection freely — adding, removing, or swapping any clubs — as long as they start the next round with no more than 14.",
    tags: ["clubs", "between rounds", "changing clubs", "multi-round"],
  },

  // --- Rule 4.1c: Anchoring ---

  {
    id: "b6_055",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "You have a long (belly) putter. Can you anchor it against your body while putting?",
    choices: [
      "No — you must not anchor the club against your body or use a hand to create an anchoring point",
      "Yes — belly putters are designed to be anchored and this is legal",
      "Only if the putter was manufactured before 2016",
      "Only in casual rounds, not in competitions",
    ],
    correct: 0,
    rule: "Rule 4.1c",
    explanation:
      "Under Rule 4.1c, a player must not make a stroke by anchoring the club, either directly (pressing the club or a gripping hand against the body) or by using an 'anchor point' (holding a forearm against the body to create a stable point). This applies to all clubs, including long and belly putters.",
    tags: ["anchoring", "putter", "stroke method", "belly putter"],
  },
  {
    id: "b6_056",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "While putting, you hold the grip end of your standard-length putter against your forearm (not your body) to stabilize the stroke. Is this a breach?",
    choices: [
      "No — resting the club against a forearm is not anchoring, as long as the forearm is not pressed against the body to create an anchor point",
      "Yes — any contact between the club and your arm is anchoring",
      "Only if the forearm touches the body",
      "It depends on the length of the putter",
    ],
    correct: 0,
    rule: "Rule 4.1c",
    explanation:
      "Under Rule 4.1c, anchoring means pressing the club or a gripping hand directly against the body, or holding a forearm against the body to use it as an anchor point. Simply resting the shaft against a forearm that is free from the body is not anchoring, because no anchor point against the body is being created.",
    tags: ["anchoring", "forearm", "putter", "grip"],
  },
  {
    id: "b6_057",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "You make a stroke with a standard iron from the fairway while unintentionally brushing the grip end of the club against your stomach during the swing. Is this a breach of the anchoring Rule?",
    choices: [
      "No — incidental contact between the club and the body during a stroke is not a breach; the club must be deliberately anchored",
      "Yes — any contact between the club and body is a breach",
      "No for irons, but yes for putters",
      "Only if it happens more than once",
    ],
    correct: 0,
    rule: "Rule 4.1c",
    explanation:
      "Under Rule 4.1c, incidental contact between the club and the body during the normal motion of a stroke is not anchoring. The prohibition is against deliberately pressing the club or a gripping hand against the body to create a stable point. A momentary brush during a swing does not constitute anchoring.",
    tags: ["anchoring", "incidental contact", "full swing", "not a breach"],
  },

  // --- Rule 4.2: Balls ---

  {
    id: "b6_058",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "Between two holes (after holing out on one green and before teeing off on the next), can you switch to a different brand of golf ball?",
    choices: [
      "Yes — you may always substitute a different ball when starting a new hole",
      "No — you must play the same ball for the entire round",
      "Only if the current ball is damaged",
      "Only if the Committee allows it by Local Rule",
    ],
    correct: 0,
    rule: "Rule 4.2a",
    explanation:
      "Under Rule 4.2a, a player may use any conforming ball when starting a hole. There is no requirement to use the same ball throughout the round. However, the Committee may adopt a Local Rule (the 'One Ball Rule') requiring players to use the same model and manufacturer of ball throughout the round — but this is not a default Rule.",
    tags: ["ball", "substitution", "between holes", "different ball"],
  },
  {
    id: "b6_059",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "The Committee has adopted the 'One Ball' Local Rule. You start the round with a Titleist Pro V1. On the 8th hole, you lose your ball and the only spare you have is a Titleist Pro V1x. What happens if you play the Pro V1x?",
    choices: [
      "You get the general penalty (two strokes) for the first hole played with the wrong model, and disqualification if you do not correct the error before playing from the next tee",
      "No penalty — V1 and V1x are close enough",
      "You are immediately disqualified",
      "One-stroke penalty per hole with the wrong ball",
    ],
    correct: 0,
    rule: "Rule 4.2a, Model Local Rule G-4",
    explanation:
      "Under Model Local Rule G-4 (One Ball Rule), a player must play the same brand and model of ball throughout the round. The Pro V1 and Pro V1x are different models. If a player breaches this Local Rule, the penalty is the general penalty for the first hole and disqualification if not corrected before playing from the next teeing area.",
    tags: ["ball", "one ball rule", "local rule", "wrong model"],
  },
  {
    id: "b6_060",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "During a hole, you notice your ball has a scuff mark on it from hitting a cart path. Can you replace it with a new ball?",
    choices: [
      "No — normal scuffs and scratches do not make a ball unfit for play; only a ball that is visibly cut, cracked, or out of shape can be substituted",
      "Yes — any visible damage allows substitution",
      "Only if your opponent or another player agrees the ball is damaged",
      "Yes — you can replace your ball at any time during a hole",
    ],
    correct: 0,
    rule: "Rule 4.2c",
    explanation:
      "Under Rule 4.2c, a ball is only unfit for play if it is visibly cut, cracked, or out of shape (deformed). Normal wear such as scuffs, scratches, or paint damage does not make a ball unfit. A player may only substitute another ball during a hole if the ball in play is cut, cracked, or out of shape.",
    tags: ["ball", "unfit for play", "scuff", "damage"],
  },
  {
    id: "b6_061",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "You believe your ball might be cracked after it hit a tree. What is the correct procedure to check it?",
    choices: [
      "Announce your intention to lift, mark the ball's position, lift and examine it — but do not clean it beyond what is needed to check for damage",
      "Just pick it up and look at it; no formalities are needed",
      "You must call a referee to examine the ball",
      "You can only check between holes, not during a hole",
    ],
    correct: 0,
    rule: "Rule 4.2c",
    explanation:
      "Under Rule 4.2c, if a player reasonably believes their ball has become cut or cracked during the play of a hole, the player may mark and lift the ball to examine it. Before lifting, the player must announce the intention to another player or marker and give them the opportunity to observe. The ball must not be cleaned beyond what is needed to see if it is damaged.",
    tags: ["ball", "cracked ball", "examination", "procedure"],
  },
  {
    id: "b6_062",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "You lift your ball to check if it is cracked. Upon examination, the ball is not cracked. You then place a new ball on the spot instead of the original ball and play it. What is the ruling?",
    choices: [
      "One penalty stroke — the original ball must have been replaced since it was not unfit for play; substituting when not allowed results in one penalty stroke under Rule 6.3b",
      "No penalty — you can always substitute when you lift the ball",
      "General penalty (two strokes) for the wrong substitution",
      "Disqualification for improper substitution",
    ],
    correct: 0,
    rule: "Rule 6.3b, Rule 4.2c",
    explanation:
      "Under Rule 4.2c, if the ball is found not to be cut or cracked, the original ball must be replaced. If the player substitutes another ball and makes a stroke without correcting the error, the player gets one penalty stroke under Rule 6.3b. The substituted ball becomes the ball in play. If the player realizes the error before making a stroke, they may correct it without penalty under Rule 14.5.",
    tags: ["ball", "substitution", "not damaged", "one-stroke penalty"],
  },
  {
    id: "b6_063",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "Your ball splits into two pieces after you hit it. What happens?",
    choices: [
      "The stroke does not count — you replay the stroke without penalty from the same spot with a new ball",
      "The stroke counts — play the larger piece as it lies",
      "The stroke counts — drop a new ball where the largest piece came to rest",
      "Two-stroke penalty; replay the stroke with a new ball",
    ],
    correct: 0,
    rule: "Rule 4.2c(2)",
    explanation:
      "Under Rule 4.2c(2), if a ball breaks into pieces as a result of a stroke, the stroke does not count. The player must play another ball from the spot where the original stroke was made, without penalty.",
    tags: ["ball", "broken ball", "split", "replay stroke"],
  },
  {
    id: "b6_064",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "During play of a hole, your ball becomes visibly egg-shaped (out of round) after hitting a sprinkler head. What are your options?",
    choices: [
      "Mark and lift the ball, confirm it is out of shape, and substitute a new ball on the original spot without penalty",
      "Play the ball as it lies — you cannot change balls during a hole",
      "Drop a new ball within one club-length of the sprinkler head",
      "Take free relief from the sprinkler head and substitute a new ball",
    ],
    correct: 0,
    rule: "Rule 4.2c",
    explanation:
      "Under Rule 4.2c, if a ball becomes cut, cracked, or out of shape (deformed) during the play of a hole, the player may substitute another ball by placing it on the spot where the original ball lay. There is no penalty for the substitution when the ball is genuinely unfit for play.",
    tags: ["ball", "out of shape", "deformed", "substitution"],
  },
  {
    id: "b6_065",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "You are playing a competition where the List of Conforming Golf Balls is in effect (Local Rule). On the 4th hole, you discover the ball you have been playing is not on the list. What is the ruling?",
    choices: [
      "You are disqualified — using a non-conforming ball when the Local Rule is in effect results in disqualification",
      "Two-stroke penalty for each hole played with the ball",
      "No penalty if you switch to a conforming ball immediately",
      "One-stroke penalty; continue with a conforming ball",
    ],
    correct: 0,
    rule: "Rule 4.2a, Model Local Rule G-3",
    explanation:
      "Under Model Local Rule G-3, when the List of Conforming Golf Balls is in effect, a player who makes a stroke with a ball not on the list is disqualified. This is because using a non-conforming ball undermines the integrity of the competition.",
    tags: ["ball", "conforming ball list", "local rule", "disqualification"],
  },

  // --- Rule 4.3: Use of Equipment ---

  {
    id: "b6_066",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "During a round, can you use a towel to dry your grips when it is raining?",
    choices: [
      "Yes — using a towel to dry equipment is always permitted",
      "No — you must play with equipment in whatever condition it is in",
      "Only between holes, not during a hole",
      "Only if the Committee has declared 'preferred lies'",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, using a towel to dry clubs, grips, or balls is a normal use of equipment and is always permitted. There is no restriction on when a player can dry their equipment during a round.",
    tags: ["equipment", "towel", "rain", "grips"],
  },
  {
    id: "b6_067",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "During a competition round, you place an alignment stick on the ground behind your ball to check your alignment before a shot. You remove it before making the stroke. Is this allowed?",
    choices: [
      "No — setting any object on the ground to help with alignment is not allowed during a round, even if removed before the stroke",
      "Yes — as long as you remove it before the stroke",
      "Only during practice rounds",
      "Only if the alignment stick is one of your 14 clubs",
    ],
    correct: 0,
    rule: "Rule 4.3a(1)",
    explanation:
      "Under Rule 4.3a(1), a player must not set any object on the ground or elsewhere to help with alignment or in any other way to assist with the stroke. This applies even if the object is removed before the stroke is made. The act of using the object for alignment is itself the breach.",
    tags: ["equipment", "alignment stick", "alignment aid", "prohibited"],
  },
  {
    id: "b6_068",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "During a round, you use a smartphone app that recommends which club to use based on your distance to the hole and the wind conditions. You have not checked wind on the app — it only shows club recommendation from the distance. Is this allowed?",
    choices: [
      "No — you must not use equipment to obtain a club recommendation during a round; only measuring distance is permitted",
      "Yes — club recommendation is the same as distance information",
      "Only if the Committee allows distance-measuring devices",
      "Only if you do not follow the recommendation",
    ],
    correct: 0,
    rule: "Rule 4.3a(1)",
    explanation:
      "Under Rule 4.3a(1), while measuring distance only is allowed (by default), a player must not use equipment to obtain a club recommendation. Even if the recommendation is based solely on distance, the act of receiving a club suggestion from a device is a separate prohibited use from merely measuring distance.",
    tags: ["equipment", "club recommendation", "smartphone app", "prohibited"],
  },
  {
    id: "b6_069",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "Can you use a distance-measuring device that also has a slope feature, if you do not use the slope feature during the round?",
    choices: [
      "Yes — if the device can measure slope but the slope function is turned off or not used, you may use it for distance only (unless a Local Rule says otherwise)",
      "No — any device with slope capability is banned regardless",
      "Only if the device has a tournament mode that disables slope",
      "Only in casual rounds",
    ],
    correct: 0,
    rule: "Rule 4.3a(1), Model Local Rule G-5",
    explanation:
      "Under Rule 4.3a(1), distance-measuring devices are allowed by default for distance only. If a device has additional features (like slope), the player must not use those features. Under Model Local Rule G-5, the Committee may require devices to have slope features disabled (e.g., tournament mode). If no such Local Rule is in effect, simply not using the slope feature is sufficient.",
    tags: ["equipment", "rangefinder", "slope", "distance measuring"],
  },
  {
    id: "b6_070",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "During a round, you use the slope feature on your rangefinder by mistake for one shot, then realize the error and turn it off. What is the penalty?",
    choices: [
      "General penalty (two strokes in stroke play, loss of hole in match play) for the first breach",
      "No penalty since it was accidental and you corrected it",
      "Disqualification",
      "Warning for the first offense",
    ],
    correct: 0,
    rule: "Rule 4.3a(1)",
    explanation:
      "Under Rule 4.3a(1), using equipment in a prohibited way (such as using a slope feature) results in the general penalty for the first breach. For a subsequent breach, the player is disqualified. There is no exception for accidental use — the penalty applies once the prohibited feature is actually used during a round.",
    tags: ["equipment", "slope feature", "rangefinder", "penalty"],
  },
  {
    id: "b6_071",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "During a round, you use your smartphone to check a general weather forecast (temperature, chance of rain) from a public weather website. Is this a breach?",
    choices: [
      "No — obtaining weather information that is available from general public sources (like a weather website or app) is permitted",
      "Yes — you cannot use any electronic device for weather during a round",
      "Only if the Committee has allowed electronic devices",
      "Only between holes, not during play of a hole",
    ],
    correct: 0,
    rule: "Rule 4.3a(1)",
    explanation:
      "Under Rule 4.3a(1), a player may obtain weather information from a public forecast that is generally available to anyone. What is prohibited is using equipment to gauge or measure conditions at the specific location (such as a localized wind-speed meter or real-time microclimate data not available publicly).",
    tags: ["equipment", "weather", "smartphone", "public forecast"],
  },
  {
    id: "b6_072",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "During a competition round, you listen to music through earbuds while walking between shots. Is this allowed?",
    choices: [
      "No — listening to music or any audio content is not allowed during a round",
      "Yes — music is fine as long as you remove earbuds before hitting",
      "Only instrumental music without lyrics",
      "Only if the volume is low enough that you can hear other players",
    ],
    correct: 0,
    rule: "Rule 4.3a(4)",
    explanation:
      "Under Rule 4.3a(4), a player must not listen to music or other audio content during a round. The purpose of this Rule is to prevent players from eliminating distractions, creating a desired tempo, or otherwise gaining an advantage from audio. This applies throughout the entire round, not just during strokes.",
    tags: ["equipment", "music", "earbuds", "audio", "prohibited"],
  },
  {
    id: "b6_073",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "You wear compression sleeves on your arms during a round for a medical condition. Another player questions whether this is allowed. What is the ruling?",
    choices: [
      "Medical equipment and compression garments worn for a legitimate medical reason are permitted under Rule 4.3b",
      "Compression sleeves are always prohibited during competition",
      "Only if you have a doctor's note presented to the Committee before the round",
      "Only if the Committee specifically approves each piece of medical equipment",
    ],
    correct: 0,
    rule: "Rule 4.3b",
    explanation:
      "Under Rule 4.3b, there is an exception for medical reasons. A player may use equipment for a medical condition if the Committee determines there is a legitimate medical need and no undue advantage is gained. Compression garments worn for medical reasons (circulation, muscle support) are generally permitted.",
    tags: ["equipment", "medical exception", "compression sleeves", "allowed"],
  },
  {
    id: "b6_074",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "A player with a physical disability uses a modified golf cart with a swivel seat that allows them to hit shots while seated. Is this allowed in competition?",
    choices: [
      "Yes, if the Committee determines it is necessary for the medical condition and does not give the player an undue advantage",
      "No — all players must stand during strokes",
      "Only in events specifically designated for players with disabilities",
      "Only if all other competitors agree",
    ],
    correct: 0,
    rule: "Rule 4.3b",
    explanation:
      "Under Rule 4.3b, the Committee may allow a player to use equipment that would otherwise be prohibited if the player has a medical condition requiring it. This includes specialized carts or seating devices. The Committee must be satisfied the equipment is medically necessary and does not give the player an unfair advantage.",
    tags: ["equipment", "medical exception", "disability", "modified equipment"],
  },
  {
    id: "b6_075",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "During a round, can you use a plumb-bob technique with your putter to read the green (holding the putter up vertically and looking at the line)?",
    choices: [
      "Yes — plumb-bobbing with your putter is permitted; it is not considered an artificial device or unusual use of equipment",
      "No — using a club as a measuring device is prohibited",
      "Only in casual rounds, not competitions",
      "Only if the putter is designed for plumb-bobbing",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, plumb-bobbing (holding a putter vertically to read slope) is a traditional technique that is permitted. The putter is being used as a visual reference, not as a level or measuring device. This has been confirmed in official interpretations as acceptable use of equipment.",
    tags: ["equipment", "plumb bob", "putter", "reading greens"],
  },
  {
    id: "b6_076",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "During a round, you place a small level (spirit level) on the green to help determine the break. Is this allowed?",
    choices: [
      "No — using a level or any device to gauge slope or read the surface is prohibited",
      "Yes — any handheld device is permitted",
      "Only if it is built into your ball marker",
      "Only in practice rounds",
    ],
    correct: 0,
    rule: "Rule 4.3a(1)",
    explanation:
      "Under Rule 4.3a(1), a player must not use equipment to gauge slope or read the surface of the green. A spirit level, whether standalone or incorporated into another object, is specifically prohibited during a round. This includes level apps on a smartphone.",
    tags: ["equipment", "level", "slope", "reading greens", "prohibited"],
  },
  {
    id: "b6_077",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "You wear bifocal glasses during your round. Your lenses have a slight magnification that helps you see the green better. Is this equipment that could breach the Rules?",
    choices: [
      "No — prescription eyeglasses (including bifocals) worn for vision correction are permitted and are not considered equipment that gives an unfair advantage",
      "Yes — any magnifying lens is prohibited equipment",
      "Only if the magnification is less than 2x",
      "Only with a prescription presented to the Committee",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, prescription eyeglasses and contact lenses worn for normal vision correction are permitted. They are not considered equipment that would give an unfair advantage. However, binoculars or magnifying devices beyond normal vision correction would be treated differently.",
    tags: ["equipment", "glasses", "vision", "permitted"],
  },
  {
    id: "b6_078",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "During a cold-weather round, can you use a hand warmer (chemical heat pack) in your pocket?",
    choices: [
      "Yes — hand warmers are permitted equipment during a round",
      "No — artificial warming devices are prohibited",
      "Only if the temperature is below 50 degrees Fahrenheit",
      "Only between holes, not during play of a hole",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, hand warmers are permitted equipment. They are not considered to give an unfair advantage — they simply help the player stay comfortable in cold conditions. Players may keep them in pockets, gloves, or anywhere convenient.",
    tags: ["equipment", "hand warmers", "cold weather", "permitted"],
  },
  {
    id: "b6_079",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "During a round, you use a stretching pole (a device specifically designed as a golf warm-up/stretching aid) between holes to stay loose. Is this allowed?",
    choices: [
      "No — a stretching aid designed for golf is considered a training aid and must not be used during a round",
      "Yes — stretching between holes is always permitted",
      "Only if it is not a club and does not resemble a club",
      "Only during a suspension of play",
    ],
    correct: 0,
    rule: "Rule 4.3a(6)",
    explanation:
      "Under Rule 4.3a(6), a player must not use any type of training or swing aid during a round. A stretching pole or device designed specifically as a golf warm-up aid is considered a training aid. However, generic stretching (without a specialized device) is not a breach.",
    tags: ["equipment", "training aid", "stretching", "prohibited"],
  },
  {
    id: "b6_080",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "During a suspension of play, you go to the driving range and use a swing trainer device to stay warm. Play is then resumed. Is this a breach?",
    choices: [
      "No — a player may use training aids during a suspension of play; the prohibition applies only during the round, and a suspension pauses the round",
      "Yes — you cannot use training aids from the moment your round starts until it ends",
      "Only if the Committee has designated practice areas as off-limits during suspension",
      "Only if you use a club from your bag",
    ],
    correct: 0,
    rule: "Rule 4.3a(6)",
    explanation:
      "Under Rule 4.3a(6), training aids and swing aids are prohibited 'during a round.' During a suspension of play, the round is paused. A player may practice during a suspension (unless the Committee prohibits it) and may use training aids during that practice, since the round is not in active play.",
    tags: ["equipment", "training aid", "suspension", "practice"],
  },
  {
    id: "b6_081",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "Can you wear gloves on both hands while playing?",
    choices: [
      "Yes — there is no Rule limiting the number of gloves; you may wear gloves on both hands",
      "No — you may only wear one glove at a time",
      "Only in cold weather with Committee permission",
      "Only if both gloves conform to the Equipment Rules",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, there is no restriction on wearing gloves on one or both hands. Gloves must conform to the Equipment Rules (e.g., they must not be molded to the grip or have features that give unfair grip assistance beyond normal glove function), but wearing two gloves is permitted.",
    tags: ["equipment", "gloves", "both hands", "permitted"],
  },
  {
    id: "b6_082",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "During a round, you use tape on your fingers to prevent blisters. Another player says this is a prohibited aid. Who is correct?",
    choices: [
      "You are correct — tape for preventing blisters or protecting against injury is permitted",
      "The other player is correct — tape modifies your grip",
      "Tape is only allowed with a medical certificate",
      "Tape is allowed on fingers but not on the palm",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, tape, bandages, and similar items used to prevent or protect against injury are permitted. This is a normal use of equipment for player welfare. The tape must not be applied in a way that gives an unfair advantage (e.g., molding the hand to the grip), but standard finger taping for blisters is always allowed.",
    tags: ["equipment", "tape", "blisters", "permitted", "injury prevention"],
  },
  {
    id: "b6_083",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "A player uses a GPS-enabled watch that vibrates to alert them when they are a certain distance from the green. The vibration provides distance information in a tactile format. Is this allowed?",
    choices: [
      "Yes — if the watch measures distance only, the vibration alert is just another way of communicating that distance information and is permitted",
      "No — vibration feedback constitutes an unfair advantage",
      "Only if the vibration feature is turned off",
      "Only if the Committee specifically allows GPS watches",
    ],
    correct: 0,
    rule: "Rule 4.3a(1)",
    explanation:
      "Under Rule 4.3a(1), distance-measuring devices are allowed by default. A GPS watch that provides distance information via vibration is simply communicating distance in a different format (tactile vs. visual). As long as the device measures distance only and does not gauge slope or provide club recommendations, it is permitted.",
    tags: ["equipment", "GPS watch", "vibration", "distance measuring"],
  },
  {
    id: "b6_084",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "You bring a pair of binoculars to the course to watch golf on a distant hole while waiting on a tee. You also use them to look at the green of the hole you are playing. Is this allowed?",
    choices: [
      "Yes — binoculars may be used to look at the course; they only measure or gather information a player could get by walking to the spot",
      "No — binoculars are prohibited equipment during a round",
      "Only to watch other groups, not your own hole",
      "Only if they do not have a rangefinder built in",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, binoculars may be used during a round because they only allow a player to see what could be seen with normal vision at closer range. They do not gauge or measure conditions. However, if binoculars have a built-in rangefinder or other measuring capability, those features must not be used unless permitted.",
    tags: ["equipment", "binoculars", "viewing course", "permitted"],
  },
  {
    id: "b6_085",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "During a round, you take a video of your swing on your phone to check your technique. You review the video before your next shot. Is this a breach?",
    choices: [
      "Yes — reviewing your swing video during a round to help with your technique is a breach because it is using equipment as a training aid",
      "No — you can record and review your swing at any time",
      "Only if you share the video with someone for coaching advice",
      "Only if you record during the actual stroke, not after",
    ],
    correct: 0,
    rule: "Rule 4.3a(6)",
    explanation:
      "Under Rule 4.3a(6), a player must not use video or other technology during a round to analyze their swing or help with their technique. Reviewing a swing video during the round constitutes using equipment as a training aid, which is prohibited. Recording for non-gameplay purposes (like social media, as long as you do not review it for technique) may be acceptable.",
    tags: ["equipment", "video", "swing analysis", "training aid", "prohibited"],
  },
  {
    id: "b6_086",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "A player applies sunscreen to their hands during the round. Another player claims this gives an unfair grip advantage. Is the sunscreen a breach of the Rules?",
    choices: [
      "No — sunscreen applied for sun protection is permitted, even if it incidentally affects grip; it is a normal use of equipment for health",
      "Yes — any substance on the hands that could affect grip is prohibited",
      "Only if it is not a spray-on type",
      "Only with Committee approval",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, sunscreen is permitted because it is applied for health protection (preventing sunburn), not to gain an unfair advantage. Even if it incidentally makes the hands slightly tacky or slippery, it is a normal use of equipment. Players may apply sunscreen at any time during the round.",
    tags: ["equipment", "sunscreen", "grip", "health", "permitted"],
  },
  {
    id: "b6_087",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "You use a tee that has a built-in brush designed to clean the face of your club. Is this tee allowed?",
    choices: [
      "It depends — a tee must conform to the Equipment Rules; a tee with an integrated brush may be considered non-conforming if it is designed to influence the movement of the ball or assist the player beyond the function of a tee",
      "Yes — any tee is legal as long as it is under 4 inches",
      "No — tees cannot have any additional features",
      "Only in casual rounds",
    ],
    correct: 0,
    rule: "Rule 4.3a, Equipment Rules (Tees)",
    explanation:
      "Under the Equipment Rules for tees, a tee must not be designed or manufactured to indicate the line of play, influence the movement of the ball, or assist the player in any way beyond elevating the ball. A brush feature goes beyond the normal function of a tee. Whether it is conforming depends on its specific design, but many such tees have been ruled non-conforming.",
    tags: ["equipment", "tee", "non-conforming", "brush tee"],
  },
  {
    id: "b6_088",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "During a round, you apply pine tar or a sticky substance to your club grip to improve your hold. Is this allowed?",
    choices: [
      "No — applying any substance to the grip to gain a grip advantage beyond what the grip itself provides is not permitted; however, plain drying agents (like rosin or grip powder) are allowed",
      "Yes — you can put anything on your grips",
      "Only if your glove is worn out",
      "Only between rounds, not during a round",
    ],
    correct: 0,
    rule: "Rule 4.3a(3)",
    explanation:
      "Under Rule 4.3a(3), a player must not apply any material to the grip or club to gain an unfair grip advantage. However, plain resin, powder, or drying agents (like rosin) used to reduce moisture are permitted. Sticky substances like pine tar or glue go beyond what is allowed.",
    tags: ["equipment", "grip substance", "pine tar", "prohibited"],
  },
  {
    id: "b6_089",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "The Committee has prohibited the use of distance-measuring devices by Local Rule. You use a rangefinder on the 3rd hole, forgetting about the Local Rule. What is the penalty?",
    choices: [
      "General penalty (two strokes in stroke play, loss of hole in match play) for the first breach; disqualification for a subsequent breach",
      "Immediate disqualification",
      "Warning for the first offense, then two-stroke penalty",
      "One-stroke penalty per use",
    ],
    correct: 0,
    rule: "Rule 4.3a(1), Model Local Rule G-5",
    explanation:
      "Under Rule 4.3a, when the Committee has prohibited the use of distance-measuring devices by Local Rule, using one results in the general penalty for the first breach. For a subsequent breach during the same round, the player is disqualified. This two-tier penalty structure applies to all equipment breaches under Rule 4.3.",
    tags: ["equipment", "rangefinder", "local rule", "prohibited", "penalty"],
  },
  {
    id: "b6_090",
    category: "FUNDAMENTALS",
    tier: "weekend",
    text: "During a round, you wrap athletic tape around a club grip to make it thicker. Is this allowed?",
    choices: [
      "No — you must not change the playing characteristics of a club by adding material to the grip during a round (other than applying plain drying agents)",
      "Yes — you can modify your grips at any time",
      "Only if you do it between holes",
      "Only if the tape does not add more than 1mm of thickness",
    ],
    correct: 0,
    rule: "Rule 4.1a(3)",
    explanation:
      "Under Rule 4.1a(3), during a round, a player must not make a stroke with a club whose playing characteristics have been deliberately changed during the round. Adding tape to a grip to change its thickness is considered deliberately altering the club's characteristics. The penalty for making a stroke with such a club is disqualification.",
    tags: ["clubs", "grip modification", "during round", "prohibited"],
  },
  {
    id: "b6_091",
    category: "FUNDAMENTALS",
    tier: "competitor",
    text: "During a round, you use a portable fan clipped to your bag to cool yourself. Is this allowed?",
    choices: [
      "Yes — a portable fan for personal comfort is permitted; it is not equipment that would affect play or give an unfair advantage",
      "No — electronic devices for personal comfort are prohibited",
      "Only if the Committee has approved it",
      "Only between holes",
    ],
    correct: 0,
    rule: "Rule 4.3a",
    explanation:
      "Under Rule 4.3a, equipment used for personal comfort (cooling, warmth) that does not assist with play is generally permitted. A portable fan for cooling does not help with play, gauge conditions, or provide an unfair advantage. It is similar to hand warmers, which are explicitly permitted.",
    tags: ["equipment", "portable fan", "comfort", "permitted"],
  },
  {
    id: "b6_092",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "A player uses a custom-made ball with their company's logo, which is not on the List of Conforming Golf Balls. The competition has NOT adopted the conforming ball Local Rule. Is there a breach?",
    choices: [
      "Not necessarily — if the conforming ball Local Rule is not in effect, there is no requirement that the ball be on the list; however, the ball must still meet the overall specifications in the Equipment Rules",
      "Yes — all balls used in competition must be on the conforming ball list",
      "No — any ball is legal if the Local Rule is not in effect",
      "Only the Committee can determine if the ball is legal",
    ],
    correct: 0,
    rule: "Rule 4.2a",
    explanation:
      "Under Rule 4.2a, in a competition where the List of Conforming Golf Balls is NOT in effect, a player may use any ball. However, under the Equipment Rules, the ball must still conform to the specifications for size, weight, symmetry, initial velocity, and distance. A custom-logo ball typically meets these specifications if it is made by a reputable manufacturer.",
    tags: ["ball", "conforming ball", "custom ball", "equipment rules"],
  },
  {
    id: "b6_093",
    category: "FUNDAMENTALS",
    tier: "official",
    text: "In stroke play, you discover on the 10th tee that your playing partner has been using one of your clubs (they mistakenly grabbed it from a shared cart). Your partner has made strokes with it on three holes. What are the penalties?",
    choices: [
      "Your partner gets the general penalty for each hole where the excess club was used (max four strokes); you have no penalty since the club was taken without your knowledge, and you were not over 14 clubs",
      "Both players are disqualified",
      "No penalty for either player since it was an honest mistake",
      "Your partner gets two strokes total; you also get two strokes for not securing your clubs",
    ],
    correct: 0,
    rule: "Rule 4.1b(1), Rule 4.1a",
    explanation:
      "Under Rule 4.1b(1), if a player carries or uses more than 14 clubs, the penalty is two strokes per hole with the breach (max four). Your partner effectively had an extra club and gets penalized accordingly. You did not intentionally share the club and were not over the 14-club limit yourself, so you receive no penalty. The club should be identified and returned.",
    tags: ["clubs", "shared cart", "excess clubs", "partner's club", "stroke play"],
  },
];
